  apiVersion: kustomize.toolkit.fluxcd.io/v1
  kind: Kustomization
  metadata:
    name: variables
    namespace: flux-system
  spec:
    interval: 1m
    sourceRef:
      kind: OCIRepository
      name: flux-system
    path: ./clusters/yes/variables
    prune: true
    wait: true
    decryption:
      provider: sops
      secretRef:
        name: sops-age