package main

import (
	"fmt"
	"sort"
	"strings"
)

const rule = "============================================================"

const subRule = "------------------------------------------------------------"

// applyOverrides reclassifies modules pinned in classificationOverrides to
// their elected license. It returns the adjusted deps (sorted order
// preserved).
func applyOverrides(deps []dependency) []dependency {
	overrides := classificationOverrides()
	out := make([]dependency, len(deps))

	for index, dep := range deps {
		entry, ok := overrides[dep.module]
		if ok {
			dep.license = entry.elected
		}

		out[index] = dep
	}

	return out
}

// render produces the full THIRD_PARTY_LICENSES document. deps must be sorted
// by module and already override-adjusted; texts maps license type →
// representative license text.
func render(deps []dependency, texts map[string]string) string {
	groups := map[string][]string{}
	for _, dep := range deps {
		groups[dep.license] = append(groups[dep.license], dep.module)
	}

	var builder strings.Builder

	writeHeader(&builder, groups, len(deps))
	writeElections(&builder)

	for _, license := range sortedLicenses(groups) {
		if license == unknownLicense {
			writeUnknownSection(&builder, groups[license])

			continue
		}

		writeLicenseSection(&builder, license, groups[license], texts[license])
	}

	return builder.String()
}

func writeHeader(builder *strings.Builder, groups map[string][]string, total int) {
	fmt.Fprintf(builder, `THIRD-PARTY SOFTWARE NOTICES AND INFORMATION
%s

KSail incorporates third-party software components. The
following notices identify the components used, along with
their respective licenses.

KSail itself is licensed under the PolyForm Shield License
1.0.0. See LICENSE in the project root.

GENERATION PROVENANCE
%s
Generated by: scripts/gen-third-party-licenses (go-licenses,
github.com/google/go-licenses/v2)
Scope: all direct and transitive Go module dependencies of
both Go modules (repo root + desktop/)
Regenerate with: make licenses
Regeneration history: see git log for this file (no timestamp
is embedded so an unchanged module graph reproduces the file
byte-identically).

LICENSE SUMMARY
%s
`, rule, subRule, subRule)

	for _, license := range sortedLicenses(groups) {
		name := license
		if license == unknownLicense {
			name = "Unknown (verified, see notes)"
		}

		fmt.Fprintf(builder, "  %s: %d module(s)\n", name, len(groups[license]))
	}

	fmt.Fprintf(builder, "  Total: %d module(s)\n", total)
}

// writeElections documents modules with a pinned/elected classification and
// the reason for each.
func writeElections(builder *strings.Builder) {
	overrides := classificationOverrides()
	if len(overrides) == 0 {
		return
	}

	fmt.Fprintf(builder, "\nLICENSE ELECTIONS AND CLASSIFICATION NOTES\n%s\n", subRule)

	modules := make([]string, 0, len(overrides))
	for module := range overrides {
		modules = append(modules, module)
	}

	sort.Strings(modules)

	for _, module := range modules {
		fmt.Fprintf(builder, "  - %s\n    %s\n", module, overrides[module].note)
	}
}

func writeLicenseSection(builder *strings.Builder, license string, modules []string, text string) {
	fmt.Fprintf(builder, "\n%s\nLicense: %s\n%s\n\nModules:\n", rule, license, rule)

	for _, module := range modules {
		fmt.Fprintf(builder, "  - %s\n", module)
	}

	fmt.Fprintf(builder, "\nLicense text:\n%s\n%s\n", subRule, text)
}

// writeUnknownSection lists modules whose archives bundle no license file,
// each with its manual verification note from verified_unknown.go.
func writeUnknownSection(builder *strings.Builder, modules []string) {
	verified := verifiedUnknown()

	fmt.Fprintf(builder, `
%s
License: Unknown (license file not bundled in Go module)
%s

The modules below are reported as "Unknown" by go-licenses
because their Go module archives do not include a LICENSE
file. Each module's actual license has been manually verified
against its source repository (see
scripts/gen-third-party-licenses/verified_unknown.go):

`, rule, rule)

	for _, module := range modules {
		entry, ok := verified[module]
		if !ok {
			// checkUnknowns guarantees every Unknown module is verified before
			// render runs; surface an invariant violation instead of emitting
			// an empty "Verified: ()" line that reads as vetted.
			fmt.Fprintf(builder,
				"  - %s\n    Verified: UNVERIFIED — generator invariant violated\n",
				module)

			continue
		}

		fmt.Fprintf(builder, "  - %s\n    Verified: %s (%s)\n", module, entry.license, entry.url)
	}

	fmt.Fprint(builder, `
License texts are not reproduced here because the module
archives do not include them. See the linked repositories
for authoritative license terms.
`)
}

func sortedLicenses(groups map[string][]string) []string {
	licenses := make([]string, 0, len(groups))
	for license := range groups {
		licenses = append(licenses, license)
	}

	sort.Strings(licenses)

	return licenses
}
