// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package registry

import (
	"context"

	"github.com/devantler-tech/ksail/v5/pkg/client/docker"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBackend creates a new instance of MockBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackend {
	mock := &MockBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBackend is an autogenerated mock type for the Backend type
type MockBackend struct {
	mock.Mock
}

type MockBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackend) EXPECT() *MockBackend_Expecter {
	return &MockBackend_Expecter{mock: &_m.Mock}
}

// CreateRegistry provides a mock function for the type MockBackend
func (_mock *MockBackend) CreateRegistry(ctx context.Context, config docker.RegistryConfig) error {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for CreateRegistry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, docker.RegistryConfig) error); ok {
		r0 = returnFunc(ctx, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_CreateRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRegistry'
type MockBackend_CreateRegistry_Call struct {
	*mock.Call
}

// CreateRegistry is a helper method to define mock.On call
//   - ctx context.Context
//   - config docker.RegistryConfig
func (_e *MockBackend_Expecter) CreateRegistry(ctx interface{}, config interface{}) *MockBackend_CreateRegistry_Call {
	return &MockBackend_CreateRegistry_Call{Call: _e.mock.On("CreateRegistry", ctx, config)}
}

func (_c *MockBackend_CreateRegistry_Call) Run(run func(ctx context.Context, config docker.RegistryConfig)) *MockBackend_CreateRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 docker.RegistryConfig
		if args[1] != nil {
			arg1 = args[1].(docker.RegistryConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_CreateRegistry_Call) Return(err error) *MockBackend_CreateRegistry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_CreateRegistry_Call) RunAndReturn(run func(ctx context.Context, config docker.RegistryConfig) error) *MockBackend_CreateRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRegistry provides a mock function for the type MockBackend
func (_mock *MockBackend) DeleteRegistry(ctx context.Context, name string, clusterName string, deleteVolume bool, networkName string, volumeName string) error {
	ret := _mock.Called(ctx, name, clusterName, deleteVolume, networkName, volumeName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRegistry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool, string, string) error); ok {
		r0 = returnFunc(ctx, name, clusterName, deleteVolume, networkName, volumeName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_DeleteRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRegistry'
type MockBackend_DeleteRegistry_Call struct {
	*mock.Call
}

// DeleteRegistry is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - clusterName string
//   - deleteVolume bool
//   - networkName string
//   - volumeName string
func (_e *MockBackend_Expecter) DeleteRegistry(ctx interface{}, name interface{}, clusterName interface{}, deleteVolume interface{}, networkName interface{}, volumeName interface{}) *MockBackend_DeleteRegistry_Call {
	return &MockBackend_DeleteRegistry_Call{Call: _e.mock.On("DeleteRegistry", ctx, name, clusterName, deleteVolume, networkName, volumeName)}
}

func (_c *MockBackend_DeleteRegistry_Call) Run(run func(ctx context.Context, name string, clusterName string, deleteVolume bool, networkName string, volumeName string)) *MockBackend_DeleteRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockBackend_DeleteRegistry_Call) Return(err error) *MockBackend_DeleteRegistry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_DeleteRegistry_Call) RunAndReturn(run func(ctx context.Context, name string, clusterName string, deleteVolume bool, networkName string, volumeName string) error) *MockBackend_DeleteRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// GetRegistryPort provides a mock function for the type MockBackend
func (_mock *MockBackend) GetRegistryPort(ctx context.Context, name string) (int, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetRegistryPort")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_GetRegistryPort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegistryPort'
type MockBackend_GetRegistryPort_Call struct {
	*mock.Call
}

// GetRegistryPort is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockBackend_Expecter) GetRegistryPort(ctx interface{}, name interface{}) *MockBackend_GetRegistryPort_Call {
	return &MockBackend_GetRegistryPort_Call{Call: _e.mock.On("GetRegistryPort", ctx, name)}
}

func (_c *MockBackend_GetRegistryPort_Call) Run(run func(ctx context.Context, name string)) *MockBackend_GetRegistryPort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_GetRegistryPort_Call) Return(n int, err error) *MockBackend_GetRegistryPort_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockBackend_GetRegistryPort_Call) RunAndReturn(run func(ctx context.Context, name string) (int, error)) *MockBackend_GetRegistryPort_Call {
	_c.Call.Return(run)
	return _c
}

// ListRegistries provides a mock function for the type MockBackend
func (_mock *MockBackend) ListRegistries(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRegistries")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_ListRegistries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRegistries'
type MockBackend_ListRegistries_Call struct {
	*mock.Call
}

// ListRegistries is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBackend_Expecter) ListRegistries(ctx interface{}) *MockBackend_ListRegistries_Call {
	return &MockBackend_ListRegistries_Call{Call: _e.mock.On("ListRegistries", ctx)}
}

func (_c *MockBackend_ListRegistries_Call) Run(run func(ctx context.Context)) *MockBackend_ListRegistries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBackend_ListRegistries_Call) Return(strings []string, err error) *MockBackend_ListRegistries_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockBackend_ListRegistries_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockBackend_ListRegistries_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForRegistriesReady provides a mock function for the type MockBackend
func (_mock *MockBackend) WaitForRegistriesReady(ctx context.Context, registryIPs map[string]string) error {
	ret := _mock.Called(ctx, registryIPs)

	if len(ret) == 0 {
		panic("no return value specified for WaitForRegistriesReady")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string) error); ok {
		r0 = returnFunc(ctx, registryIPs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_WaitForRegistriesReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForRegistriesReady'
type MockBackend_WaitForRegistriesReady_Call struct {
	*mock.Call
}

// WaitForRegistriesReady is a helper method to define mock.On call
//   - ctx context.Context
//   - registryIPs map[string]string
func (_e *MockBackend_Expecter) WaitForRegistriesReady(ctx interface{}, registryIPs interface{}) *MockBackend_WaitForRegistriesReady_Call {
	return &MockBackend_WaitForRegistriesReady_Call{Call: _e.mock.On("WaitForRegistriesReady", ctx, registryIPs)}
}

func (_c *MockBackend_WaitForRegistriesReady_Call) Run(run func(ctx context.Context, registryIPs map[string]string)) *MockBackend_WaitForRegistriesReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_WaitForRegistriesReady_Call) Return(err error) *MockBackend_WaitForRegistriesReady_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_WaitForRegistriesReady_Call) RunAndReturn(run func(ctx context.Context, registryIPs map[string]string) error) *MockBackend_WaitForRegistriesReady_Call {
	_c.Call.Return(run)
	return _c
}
