version: "2"
run:
  allow-parallel-runners: true
  modules-download-mode: readonly
  go: "1.25.4"
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
linters:
  default: all
  enable:
    - wsl_v5
  disable:
    - exhaustruct
    - wsl
  exclusions:
    paths:
      - ".*mocks.*\\.go$"
    rules:
      - linters:
          - ireturn
        path: pkg/io/config-manager/loader/loader.go
      - linters:
          - ireturn
        path: pkg/client/docker/engine.go
      - linters:
          - ireturn
        path: pkg/cli/helpers/flags.go
      - linters:
          - ireturn
        path: pkg/svc/provisioner/cluster/factory.go
      - linters:
          - ireturn
        path: pkg/svc/provisioner/registry/local_registry_service.go
      - linters:
          - ireturn
        path: pkg/svc/installer/cni/base.go
      - linters:
          - ireturn
        path: pkg/client/oci/service.go
      - linters:
          - ireturn
        path: pkg/client/flux/client.go
      - linters:
          - ireturn
        path: pkg/client/kubectl/client.go
      - linters:
          - ireturn
        path: pkg/svc/installer/flux/fluxinstance_types.go
      - linters:
          - ireturn
        path: pkg/client/oci/builder_impl.go
      - linters:
          - ireturn
        path: pkg/client/kubeconform/client.go
      - linters:
          - ireturn
        path: pkg/svc/installer/flux/resources.go
      - linters:
          - ireturn
        path: pkg/svc/installer/flux/resources_test.go
      - linters:
          - ireturn
        path: pkg/cli/cmd/cipher/encrypt.go
      - linters:
          - ireturn
        path: pkg/cli/cmd/cluster/create_test.go
      - linters:
          - ireturn
        path: pkg/cli/cmd/cluster/list_test.go
      - linters:
          - ireturn
        path: pkg/cli/cmd/cluster/delete.go
      - linters:
          - ireturn
        path: pkg/client/argocd/reconciler.go
      - linters:
          - ireturn
        path: pkg/client/flux/reconciler.go
      - linters:
          - ireturn
        path: pkg/k8s/apiserver_test.go
      - linters:
          - ireturn
        path: pkg/svc/reconciler/base.go
      - linters:
          - paralleltest
        path: pkg/cli/cmd/cipher/import_test.go
      # Chat package exclusions - legitimate CLI tool behavior
      - linters:
          - gosec
        text: "G304|G204"
        path: pkg/svc/chat/
      - linters:
          - gosec
        text: "G304|G204"
        path: pkg/cli/cmd/chat.go
      # Chat package exclusions - acceptable for CLI interactive code
      - linters:
          - cyclop
        path: pkg/cli/cmd/chat.go
      - linters:
          - err113
        path: pkg/cli/cmd/chat.go
      - linters:
          - errcheck
        path: pkg/cli/cmd/chat.go
      - linters:
          - funlen
        path: pkg/cli/cmd/chat.go
      - linters:
          - exhaustive
        path: pkg/cli/cmd/chat.go
      - linters:
          - errorlint
        path: pkg/cli/cmd/chat.go
      - linters:
          - mnd
        path: pkg/cli/cmd/chat.go
      - linters:
          - modernize
        path: pkg/cli/cmd/chat.go
      - linters:
          - nlreturn
        path: pkg/cli/cmd/chat.go
      - linters:
          - perfsprint
        path: pkg/cli/cmd/chat.go
      - linters:
          - wrapcheck
        path: pkg/cli/cmd/chat.go
      - linters:
          - wsl_v5
        path: pkg/cli/cmd/chat.go
      # Chat TUI package exclusions - acceptable for TUI code
      - linters:
          - containedctx
        path: pkg/cli/ui/chat/
      - linters:
          - cyclop
        path: pkg/cli/ui/chat/
      - linters:
          - err113
        path: pkg/cli/ui/chat/
      - linters:
          - errcheck
        path: pkg/cli/ui/chat/
      - linters:
          - funlen
        path: pkg/cli/ui/chat/
      - linters:
          - exhaustive
        path: pkg/cli/ui/chat/
      - linters:
          - gochecknoglobals
        path: pkg/cli/ui/chat/
      - linters:
          - gocognit
        path: pkg/cli/ui/chat/
      - linters:
          - goconst
        path: pkg/cli/ui/chat/
      - linters:
          - gocritic
        path: pkg/cli/ui/chat/
      - linters:
          - ireturn
        path: pkg/cli/ui/chat/
      - linters:
          - mnd
        path: pkg/cli/ui/chat/
      - linters:
          - modernize
        path: pkg/cli/ui/chat/
      - linters:
          - nlreturn
        path: pkg/cli/ui/chat/
      - linters:
          - noinlineerr
        path: pkg/cli/ui/chat/
      - linters:
          - perfsprint
        path: pkg/cli/ui/chat/
      - linters:
          - recvcheck
        path: pkg/cli/ui/chat/
      - linters:
          - varnamelen
        path: pkg/cli/ui/chat/
      - linters:
          - wrapcheck
        path: pkg/cli/ui/chat/
      - linters:
          - wsl_v5
        path: pkg/cli/ui/chat/
      - linters:
          - cyclop
        path: pkg/svc/chat/
      - linters:
          - err113
        path: pkg/svc/chat/
      - linters:
          - funlen
        path: pkg/svc/chat/
      - linters:
          - noinlineerr
        path: pkg/svc/chat/
      - linters:
          - mirror
        path: pkg/svc/chat/
      - linters:
          - nilerr
        path: pkg/svc/chat/
      - linters:
          - modernize
        text: stringsseq
        path: pkg/svc/chat/
      - linters:
          - perfsprint
        path: pkg/svc/chat/
      - linters:
          - funlen
        path: pkg/svc/provisioner/registry/local_registry_service_test.go
      - linters:
          - tagalign
        path: pkg/apis/cluster/v1alpha1/types.go
      - linters:
          - tagalign
        path: pkg/apis/cluster/v1alpha1/options.go
      - linters:
          - revive
        text: "var-naming: avoid package names that conflict with Go standard library package names"
        path: pkg/io/
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"
        path: pkg/utils/doc.go
      - linters:
          - nolintlint
        text: "directive `//nolint:staticcheck // WatchProgress is deprecated but simpler than WaitForFunc` is unused"
        path: pkg/svc/provider/hetzner/provider.go
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    depguard:
      rules:
        main:
          files:
            - "$all"
            - "!$test"
          list-mode: strict
          allow:
            - $gostd
            - github.com/atotto
            - github.com/devantler-tech
            - github.com/charmbracelet
            - github.com/derailed/k9s
            - github.com/fluxcd
            - github.com/getsops/sops
            - github.com/github/copilot-sdk
            - github.com/go-viper/mapstructure/v2
            - github.com/google/go-containerregistry
            - github.com/hetznercloud
            - github.com/invopop/jsonschema
            - github.com/Masterminds/semver
            - github.com/mitchellh
            - github.com/wk8/go-ordered-map
            - github.com/samber/do/v2
            - github.com/containerd
            - github.com/docker
            - github.com/fatih/color
            - github.com/fluxcd
            - github.com/gkampitakis/go-snaps
            - github.com/jinzhu/copier
            - github.com/k3d-io
            - github.com/rancher
            - github.com/mittwald
            - github.com/modelcontextprotocol
            - github.com/spf13/cobra
            - github.com/spf13/pflag
            - github.com/spf13/viper
            - github.com/stretchr/testify
            - github.com/siderolabs
            - github.com/sirupsen/logrus
            - github.com/yannh
            - filippo.io/age
            - golang.design/x
            - golang.org/x/sync
            - golang.org/x/term
            - golang.org/x/text
            - helm.sh/helm
            - k8s.io
            - sigs.k8s.io
