version: "2"
run:
  allow-parallel-runners: true
  modules-download-mode: readonly
  go: "1.26.0"
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
linters:
  default: all
  enable:
    - wsl_v5
  disable:
    - exhaustruct
    - wsl
    - ireturn
  exclusions:
    paths:
      - ".*mocks.*\\.go$"
    rules:
      # Tests that modify env vars cannot run in parallel
      - linters:
          - paralleltest
        path: pkg/cli/cmd/cipher/import_test.go
      # Bubbletea requires context in the Model struct
      - linters:
          - containedctx
        path: pkg/cli/ui/chat/
      # lipgloss style variables must be package-level globals
      - linters:
          - gochecknoglobals
        path: pkg/cli/ui/chat/
      # Package names that conflict with stdlib or are too generic cannot be renamed without breaking changes
      - linters:
          - revive
        text: "var-naming: avoid package names that conflict with Go standard library package names"
        path: pkg/io/
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"
        path: pkg/utils/doc.go
  settings:
    tagalign:
      align: false
      sort: true
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    depguard:
      rules:
        main:
          files:
            - "$all"
            - "!$test"
          list-mode: strict
          allow:
            - $gostd
            - github.com/atotto
            - github.com/devantler-tech
            - github.com/charmbracelet
            - github.com/derailed/k9s
            - github.com/fluxcd
            - github.com/getsops/sops
            - github.com/github/copilot-sdk
            - github.com/go-viper/mapstructure/v2
            - github.com/google/go-containerregistry
            - github.com/hetznercloud
            - github.com/invopop/jsonschema
            - github.com/Masterminds/semver
            - github.com/mitchellh
            - github.com/wk8/go-ordered-map
            - github.com/samber/do/v2
            - github.com/containerd
            - github.com/docker
            - github.com/fatih/color
            - github.com/fluxcd
            - github.com/gkampitakis/go-snaps
            - github.com/jinzhu/copier
            - github.com/k3d-io
            - github.com/rancher
            - github.com/mittwald
            - github.com/modelcontextprotocol
            - github.com/spf13/cobra
            - github.com/spf13/pflag
            - github.com/spf13/viper
            - github.com/stretchr/testify
            - github.com/siderolabs
            - github.com/sirupsen/logrus
            - github.com/yannh
            - filippo.io/age
            - golang.design/x
            - golang.org/x/sync
            - golang.org/x/term
            - golang.org/x/text
            - helm.sh/helm
            - k8s.io
            - sigs.k8s.io
