version: 2

before:
  hooks:
    - go mod tidy

builds:
  - binary: ksail
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
    env:
      - CGO_ENABLED=0

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]

brews:
  - name: ksail
    homepage: "https://github.com/devantler-tech/ksail"
    description: "CLI tool to manage clusters and workloads"
    license: "Apache-2.0"
    directory: Formula
    url_template: "https://github.com/devantler-tech/ksail/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    repository:
      owner: devantler-tech
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_GITHUB_API_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: goreleaserbot@users.noreply.github.com
    custom_block: |
      def install
        bin.install "ksail"
      end

      test do
        system bin/"ksail", "--help"
      end

homebrew_casks:
  - name: ksail
    homepage: "https://github.com/devantler-tech/ksail"
    description: "CLI tool to manage clusters and workloads"
    license: "Apache-2.0"
    directory: Casks
    repository:
      owner: devantler-tech
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_GITHUB_API_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: goreleaserbot@users.noreply.github.com
    commit_msg_template: "Cask update for {{ .ProjectName }} version {{ .Tag }}"
    url:
      template: "https://github.com/devantler-tech/ksail/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      verified: "github.com/devantler-tech/ksail"
    binaries:
      - ksail
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ksail"]
          end

dockers_v2:
  - images:
      - "ghcr.io/devantler-tech/ksail"
    tags:
      - "{{ .Tag }}"
      - "latest"
    labels:
      "org.opencontainers.image.description": "KSail is a CLI tool to manage clusters and workloads."
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.licenses": "Apache-2.0"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^chore"
      - "^ci"
      - "^build"
      - "^style"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: "Breaking Changes"
      regexp: '^.*?((feat|fix|perf|refactor)(\(.+\))?!:|BREAKING CHANGE:)'
      order: 0
    - title: "Features"
      regexp: '^.*?feat(\(.+\))?:'
      order: 1
    - title: "Bug Fixes"
      regexp: '^.*?fix(\(.+\))?:'
      order: 2
    - title: "Performance Improvements"
      regexp: '^.*?perf(\(.+\))?:'
      order: 3
    - title: "Refactoring"
      regexp: '^.*?refactor(\(.+\))?:'
      order: 4
    - title: "Other Changes"
      order: 999

release:
  footer: |
    ## Quick Start

    **Homebrew Cask** (macOS):
    ```bash
    brew install --cask devantler-tech/formulas/ksail
    ```
    > Note: Since the binary is not signed/notarized, you may need to use `--no-quarantine`:
    > `brew install --cask --no-quarantine devantler-tech/formulas/ksail`

    **Homebrew Formula** (macOS/Linux):
    ```bash
    brew install devantler-tech/tap/ksail
    ```

    **Go Install**:
    ```bash
    go install github.com/devantler-tech/ksail/v5@{{ .Tag }}
    ```

    **Download Binary**: Choose your platform from the assets above

    **Docker**:
    ```bash
    docker pull ghcr.io/devantler-tech/ksail:{{ .Tag }}
    # or use :latest for the latest release
    ```

    ---
    **Full Changelog**: https://github.com/devantler-tech/ksail/compare/{{ .PreviousTag }}...{{ .Tag }}
