version: 2

before:
  hooks:
    - go mod tidy

builds:
  - binary: ksail
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
    env:
      - CGO_ENABLED=0

archives:
  - formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]

dockers_v2:
  - images:
      - "ghcr.io/devantler-tech/ksail-go"
    tags:
      - "{{ .Tag }}"
      - "latest"
    labels:
      "org.opencontainers.image.description": "KSail is a CLI tool to manage clusters and workloads."
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.licenses": "Apache-2.0"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^chore"
      - "^ci"
      - "^build"
      - "^style"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: "Breaking Changes"
      regexp: "^.*!:"
      order: 0
    - title: "Features"
      regexp: '^.*?feat(\(.+\))?!?:'
      order: 1
    - title: "Bug Fixes"
      regexp: '^.*?fix(\(.+\))?!?:'
      order: 2
    - title: "Performance Improvements"
      regexp: '^.*?perf(\(.+\))?!?:'
      order: 3
    - title: "Refactoring"
      regexp: '^.*?refactor(\(.+\))?!?:'
      order: 4
    - title: "Other Changes"
      order: 999

release:
  footer: |
    ## Quick Start

    **Homebrew** (macOS/Linux):
    ```bash
    brew install devantler-tech/taps/ksail
    ```

    **Go Install**:
    ```bash
    go install github.com/devantler-tech/ksail-go@{{ .Tag }}
    ```

    **Download Binary**: Choose your platform from the assets above

    **Docker**:
    ```bash
    docker pull ghcr.io/devantler-tech/ksail-go:{{ .Tag }}
    # or use :latest for the latest release
    ```

    ---
    **Full Changelog**: https://github.com/devantler-tech/ksail-go/compare/{{ .PreviousTag }}...{{ .Tag }}
