version: 2

before:
  hooks:
    - go mod tidy

builds:
  - binary: ksail
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
    env:
      - CGO_ENABLED=0

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]

homebrew_casks:
  - name: ksail
    repository:
      owner: devantler-tech
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_GITHUB_API_TOKEN }}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ksail"]
          end
    commit_author:
      signing:
        enabled: true
        key: "{{ .Env.GPG_PRIVATE_KEY }}"
        program: gpg2
        format: openpgp

dockers_v2:
  - images:
      - "ghcr.io/devantler-tech/ksail"
    tags:
      - "{{ .Tag }}"
      - "latest"
    labels:
      "org.opencontainers.image.description": "KSail is a CLI tool to manage clusters and workloads."
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.licenses": "Apache-2.0"

changelog:
  sort: asc
  filters:
    exclude:
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: "Breaking Changes"
      regexp: '^.*?((feat|fix|perf|refactor)(\(.+\))?!:|BREAKING CHANGE:)'
      order: 0
    - title: "Features"
      regexp: '^.*?feat(\(.+\))?:'
      order: 1
    - title: "Bug Fixes"
      regexp: '^.*?fix(\(.+\))?:'
      order: 2
    - title: "Performance Improvements"
      regexp: '^.*?perf(\(.+\))?:'
      order: 3
    - title: "Refactoring"
      regexp: '^.*?refactor(\(.+\))?:'
      order: 4
    - title: "Other Changes"
      order: 999

release:
  draft: true
  footer: |
    ## Quick Start

    **Homebrew Cask** (macOS):

    ```bash
    # Standard installation:
    brew install --cask devantler-tech/tap/ksail

    # If you encounter macOS quarantine issues:
    brew install --cask --no-quarantine devantler-tech/tap/ksail
    ```

    **Go Install**:

    ```bash
    go install github.com/devantler-tech/ksail/v5@{{ .Tag }}
    ```

    **Download Binary**: Choose your platform from the assets above

    **Docker**:

    ```bash
    docker pull ghcr.io/devantler-tech/ksail:{{ .Tag }}
    ```

    ---
    **Full Changelog**: https://github.com/devantler-tech/ksail/compare/{{ .PreviousTag }}...{{ .Tag }}
