# CONFIGURATION
APPLY_FIXES: all
FLAVOR_SUGGESTIONS: false
IGNORE_GITIGNORED_FILES: true
REPORTERS_MARKDOWN_SUMMARY_TYPE: sections
LINTER_RULES_PATH: .
DISABLE_LINTERS:
  - GO_GOLANGCI_LINT # Disabled: MegaLinter container has Go 1.24.7, but project requires Go 1.26.0. CI runs golangci-lint separately with correct Go version.
  - GO_REVIVE
  - REPOSITORY_CHECKOV
  - REPOSITORY_GITLEAKS
  - REPOSITORY_GRYPE
  - REPOSITORY_SECRETLINT
  - REPOSITORY_TRIVY
  - SPELL_CSPELL

# EXCLUDE FILTERS
EXCLUDED_DIRECTORIES:
  - megalinter-reports
  - report
  - .github/agents
  - .github/prompts
  - .jscpd
  - schemas
ACTION_ACTIONLINT_FILTER_REGEX_EXCLUDE: .github/workflows/.*\.lock\.yml
FILTER_REGEX_EXCLUDE: megalinter-reports/.*
JSON_V8R_FILTER_REGEX_EXCLUDE: .github/workflows/.*\.lock\.yml
MARKDOWN_MARKDOWN_TABLE_FORMATTER_FILTER_REGEX_EXCLUDE: .github/(agents|prompts)
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: .github/(agents|prompts)
SPELL_LYCHEE_FILTER_REGEX_EXCLUDE: (.github/copilot-instructions\.md|.*\.mdx)
YAML_V8R_FILTER_REGEX_EXCLUDE: .github/workflows/.*\.lock\.yml
