// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package helm

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	mock := &MockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter {
	return &MockInterface_Expecter{mock: &_m.Mock}
}

// AddRepository provides a mock function for the type MockInterface
func (_mock *MockInterface) AddRepository(ctx context.Context, entry *RepositoryEntry, timeout time.Duration) error {
	ret := _mock.Called(ctx, entry, timeout)

	if len(ret) == 0 {
		panic("no return value specified for AddRepository")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *RepositoryEntry, time.Duration) error); ok {
		r0 = returnFunc(ctx, entry, timeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_AddRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRepository'
type MockInterface_AddRepository_Call struct {
	*mock.Call
}

// AddRepository is a helper method to define mock.On call
//   - ctx context.Context
//   - entry *RepositoryEntry
//   - timeout time.Duration
func (_e *MockInterface_Expecter) AddRepository(ctx interface{}, entry interface{}, timeout interface{}) *MockInterface_AddRepository_Call {
	return &MockInterface_AddRepository_Call{Call: _e.mock.On("AddRepository", ctx, entry, timeout)}
}

func (_c *MockInterface_AddRepository_Call) Run(run func(ctx context.Context, entry *RepositoryEntry, timeout time.Duration)) *MockInterface_AddRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *RepositoryEntry
		if args[1] != nil {
			arg1 = args[1].(*RepositoryEntry)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInterface_AddRepository_Call) Return(err error) *MockInterface_AddRepository_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_AddRepository_Call) RunAndReturn(run func(ctx context.Context, entry *RepositoryEntry, timeout time.Duration) error) *MockInterface_AddRepository_Call {
	_c.Call.Return(run)
	return _c
}

// GetReleaseStorageLabels provides a mock function for the type MockInterface
func (_mock *MockInterface) GetReleaseStorageLabels(ctx context.Context, releaseName string, namespace string) (map[string]string, error) {
	ret := _mock.Called(ctx, releaseName, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetReleaseStorageLabels")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (map[string]string, error)); ok {
		return returnFunc(ctx, releaseName, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) map[string]string); ok {
		r0 = returnFunc(ctx, releaseName, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, releaseName, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_GetReleaseStorageLabels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReleaseStorageLabels'
type MockInterface_GetReleaseStorageLabels_Call struct {
	*mock.Call
}

// GetReleaseStorageLabels is a helper method to define mock.On call
//   - ctx context.Context
//   - releaseName string
//   - namespace string
func (_e *MockInterface_Expecter) GetReleaseStorageLabels(ctx interface{}, releaseName interface{}, namespace interface{}) *MockInterface_GetReleaseStorageLabels_Call {
	return &MockInterface_GetReleaseStorageLabels_Call{Call: _e.mock.On("GetReleaseStorageLabels", ctx, releaseName, namespace)}
}

func (_c *MockInterface_GetReleaseStorageLabels_Call) Run(run func(ctx context.Context, releaseName string, namespace string)) *MockInterface_GetReleaseStorageLabels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInterface_GetReleaseStorageLabels_Call) Return(stringToString map[string]string, err error) *MockInterface_GetReleaseStorageLabels_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockInterface_GetReleaseStorageLabels_Call) RunAndReturn(run func(ctx context.Context, releaseName string, namespace string) (map[string]string, error)) *MockInterface_GetReleaseStorageLabels_Call {
	_c.Call.Return(run)
	return _c
}

// GetReleaseStorageMetadata provides a mock function for the type MockInterface
func (_mock *MockInterface) GetReleaseStorageMetadata(ctx context.Context, releaseName string, namespace string) (*ReleaseStorageMetadata, error) {
	ret := _mock.Called(ctx, releaseName, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetReleaseStorageMetadata")
	}

	var r0 *ReleaseStorageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*ReleaseStorageMetadata, error)); ok {
		return returnFunc(ctx, releaseName, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *ReleaseStorageMetadata); ok {
		r0 = returnFunc(ctx, releaseName, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ReleaseStorageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, releaseName, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_GetReleaseStorageMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReleaseStorageMetadata'
type MockInterface_GetReleaseStorageMetadata_Call struct {
	*mock.Call
}

// GetReleaseStorageMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - releaseName string
//   - namespace string
func (_e *MockInterface_Expecter) GetReleaseStorageMetadata(ctx interface{}, releaseName interface{}, namespace interface{}) *MockInterface_GetReleaseStorageMetadata_Call {
	return &MockInterface_GetReleaseStorageMetadata_Call{Call: _e.mock.On("GetReleaseStorageMetadata", ctx, releaseName, namespace)}
}

func (_c *MockInterface_GetReleaseStorageMetadata_Call) Run(run func(ctx context.Context, releaseName string, namespace string)) *MockInterface_GetReleaseStorageMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInterface_GetReleaseStorageMetadata_Call) Return(releaseStorageMetadata *ReleaseStorageMetadata, err error) *MockInterface_GetReleaseStorageMetadata_Call {
	_c.Call.Return(releaseStorageMetadata, err)
	return _c
}

func (_c *MockInterface_GetReleaseStorageMetadata_Call) RunAndReturn(run func(ctx context.Context, releaseName string, namespace string) (*ReleaseStorageMetadata, error)) *MockInterface_GetReleaseStorageMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetReleaseValues provides a mock function for the type MockInterface
func (_mock *MockInterface) GetReleaseValues(ctx context.Context, releaseName string, namespace string) (map[string]any, error) {
	ret := _mock.Called(ctx, releaseName, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetReleaseValues")
	}

	var r0 map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (map[string]any, error)); ok {
		return returnFunc(ctx, releaseName, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) map[string]any); ok {
		r0 = returnFunc(ctx, releaseName, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, releaseName, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_GetReleaseValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReleaseValues'
type MockInterface_GetReleaseValues_Call struct {
	*mock.Call
}

// GetReleaseValues is a helper method to define mock.On call
//   - ctx context.Context
//   - releaseName string
//   - namespace string
func (_e *MockInterface_Expecter) GetReleaseValues(ctx interface{}, releaseName interface{}, namespace interface{}) *MockInterface_GetReleaseValues_Call {
	return &MockInterface_GetReleaseValues_Call{Call: _e.mock.On("GetReleaseValues", ctx, releaseName, namespace)}
}

func (_c *MockInterface_GetReleaseValues_Call) Run(run func(ctx context.Context, releaseName string, namespace string)) *MockInterface_GetReleaseValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInterface_GetReleaseValues_Call) Return(stringToV map[string]any, err error) *MockInterface_GetReleaseValues_Call {
	_c.Call.Return(stringToV, err)
	return _c
}

func (_c *MockInterface_GetReleaseValues_Call) RunAndReturn(run func(ctx context.Context, releaseName string, namespace string) (map[string]any, error)) *MockInterface_GetReleaseValues_Call {
	_c.Call.Return(run)
	return _c
}

// InstallChart provides a mock function for the type MockInterface
func (_mock *MockInterface) InstallChart(ctx context.Context, spec *ChartSpec) (*ReleaseInfo, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for InstallChart")
	}

	var r0 *ReleaseInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ChartSpec) (*ReleaseInfo, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ChartSpec) *ReleaseInfo); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ReleaseInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ChartSpec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_InstallChart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallChart'
type MockInterface_InstallChart_Call struct {
	*mock.Call
}

// InstallChart is a helper method to define mock.On call
//   - ctx context.Context
//   - spec *ChartSpec
func (_e *MockInterface_Expecter) InstallChart(ctx interface{}, spec interface{}) *MockInterface_InstallChart_Call {
	return &MockInterface_InstallChart_Call{Call: _e.mock.On("InstallChart", ctx, spec)}
}

func (_c *MockInterface_InstallChart_Call) Run(run func(ctx context.Context, spec *ChartSpec)) *MockInterface_InstallChart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ChartSpec
		if args[1] != nil {
			arg1 = args[1].(*ChartSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInterface_InstallChart_Call) Return(releaseInfo *ReleaseInfo, err error) *MockInterface_InstallChart_Call {
	_c.Call.Return(releaseInfo, err)
	return _c
}

func (_c *MockInterface_InstallChart_Call) RunAndReturn(run func(ctx context.Context, spec *ChartSpec) (*ReleaseInfo, error)) *MockInterface_InstallChart_Call {
	_c.Call.Return(run)
	return _c
}

// InstallOrUpgradeChart provides a mock function for the type MockInterface
func (_mock *MockInterface) InstallOrUpgradeChart(ctx context.Context, spec *ChartSpec) (*ReleaseInfo, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for InstallOrUpgradeChart")
	}

	var r0 *ReleaseInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ChartSpec) (*ReleaseInfo, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ChartSpec) *ReleaseInfo); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ReleaseInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ChartSpec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_InstallOrUpgradeChart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallOrUpgradeChart'
type MockInterface_InstallOrUpgradeChart_Call struct {
	*mock.Call
}

// InstallOrUpgradeChart is a helper method to define mock.On call
//   - ctx context.Context
//   - spec *ChartSpec
func (_e *MockInterface_Expecter) InstallOrUpgradeChart(ctx interface{}, spec interface{}) *MockInterface_InstallOrUpgradeChart_Call {
	return &MockInterface_InstallOrUpgradeChart_Call{Call: _e.mock.On("InstallOrUpgradeChart", ctx, spec)}
}

func (_c *MockInterface_InstallOrUpgradeChart_Call) Run(run func(ctx context.Context, spec *ChartSpec)) *MockInterface_InstallOrUpgradeChart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ChartSpec
		if args[1] != nil {
			arg1 = args[1].(*ChartSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInterface_InstallOrUpgradeChart_Call) Return(releaseInfo *ReleaseInfo, err error) *MockInterface_InstallOrUpgradeChart_Call {
	_c.Call.Return(releaseInfo, err)
	return _c
}

func (_c *MockInterface_InstallOrUpgradeChart_Call) RunAndReturn(run func(ctx context.Context, spec *ChartSpec) (*ReleaseInfo, error)) *MockInterface_InstallOrUpgradeChart_Call {
	_c.Call.Return(run)
	return _c
}

// ListReleases provides a mock function for the type MockInterface
func (_mock *MockInterface) ListReleases(ctx context.Context) ([]ReleaseInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListReleases")
	}

	var r0 []ReleaseInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ReleaseInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ReleaseInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ReleaseInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_ListReleases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReleases'
type MockInterface_ListReleases_Call struct {
	*mock.Call
}

// ListReleases is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInterface_Expecter) ListReleases(ctx interface{}) *MockInterface_ListReleases_Call {
	return &MockInterface_ListReleases_Call{Call: _e.mock.On("ListReleases", ctx)}
}

func (_c *MockInterface_ListReleases_Call) Run(run func(ctx context.Context)) *MockInterface_ListReleases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInterface_ListReleases_Call) Return(releaseInfos []ReleaseInfo, err error) *MockInterface_ListReleases_Call {
	_c.Call.Return(releaseInfos, err)
	return _c
}

func (_c *MockInterface_ListReleases_Call) RunAndReturn(run func(ctx context.Context) ([]ReleaseInfo, error)) *MockInterface_ListReleases_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshDiscovery provides a mock function for the type MockInterface
func (_mock *MockInterface) RefreshDiscovery() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RefreshDiscovery")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_RefreshDiscovery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshDiscovery'
type MockInterface_RefreshDiscovery_Call struct {
	*mock.Call
}

// RefreshDiscovery is a helper method to define mock.On call
func (_e *MockInterface_Expecter) RefreshDiscovery() *MockInterface_RefreshDiscovery_Call {
	return &MockInterface_RefreshDiscovery_Call{Call: _e.mock.On("RefreshDiscovery")}
}

func (_c *MockInterface_RefreshDiscovery_Call) Run(run func()) *MockInterface_RefreshDiscovery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInterface_RefreshDiscovery_Call) Return(err error) *MockInterface_RefreshDiscovery_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_RefreshDiscovery_Call) RunAndReturn(run func() error) *MockInterface_RefreshDiscovery_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseExists provides a mock function for the type MockInterface
func (_mock *MockInterface) ReleaseExists(ctx context.Context, releaseName string, namespace string) (bool, error) {
	ret := _mock.Called(ctx, releaseName, namespace)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, releaseName, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, releaseName, namespace)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, releaseName, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_ReleaseExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseExists'
type MockInterface_ReleaseExists_Call struct {
	*mock.Call
}

// ReleaseExists is a helper method to define mock.On call
//   - ctx context.Context
//   - releaseName string
//   - namespace string
func (_e *MockInterface_Expecter) ReleaseExists(ctx interface{}, releaseName interface{}, namespace interface{}) *MockInterface_ReleaseExists_Call {
	return &MockInterface_ReleaseExists_Call{Call: _e.mock.On("ReleaseExists", ctx, releaseName, namespace)}
}

func (_c *MockInterface_ReleaseExists_Call) Run(run func(ctx context.Context, releaseName string, namespace string)) *MockInterface_ReleaseExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInterface_ReleaseExists_Call) Return(b bool, err error) *MockInterface_ReleaseExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockInterface_ReleaseExists_Call) RunAndReturn(run func(ctx context.Context, releaseName string, namespace string) (bool, error)) *MockInterface_ReleaseExists_Call {
	_c.Call.Return(run)
	return _c
}

// TemplateChart provides a mock function for the type MockInterface
func (_mock *MockInterface) TemplateChart(ctx context.Context, spec *ChartSpec) (string, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for TemplateChart")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ChartSpec) (string, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ChartSpec) string); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ChartSpec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_TemplateChart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TemplateChart'
type MockInterface_TemplateChart_Call struct {
	*mock.Call
}

// TemplateChart is a helper method to define mock.On call
//   - ctx context.Context
//   - spec *ChartSpec
func (_e *MockInterface_Expecter) TemplateChart(ctx interface{}, spec interface{}) *MockInterface_TemplateChart_Call {
	return &MockInterface_TemplateChart_Call{Call: _e.mock.On("TemplateChart", ctx, spec)}
}

func (_c *MockInterface_TemplateChart_Call) Run(run func(ctx context.Context, spec *ChartSpec)) *MockInterface_TemplateChart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ChartSpec
		if args[1] != nil {
			arg1 = args[1].(*ChartSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInterface_TemplateChart_Call) Return(s string, err error) *MockInterface_TemplateChart_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockInterface_TemplateChart_Call) RunAndReturn(run func(ctx context.Context, spec *ChartSpec) (string, error)) *MockInterface_TemplateChart_Call {
	_c.Call.Return(run)
	return _c
}

// UninstallRelease provides a mock function for the type MockInterface
func (_mock *MockInterface) UninstallRelease(ctx context.Context, releaseName string, namespace string) error {
	ret := _mock.Called(ctx, releaseName, namespace)

	if len(ret) == 0 {
		panic("no return value specified for UninstallRelease")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, releaseName, namespace)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_UninstallRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UninstallRelease'
type MockInterface_UninstallRelease_Call struct {
	*mock.Call
}

// UninstallRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - releaseName string
//   - namespace string
func (_e *MockInterface_Expecter) UninstallRelease(ctx interface{}, releaseName interface{}, namespace interface{}) *MockInterface_UninstallRelease_Call {
	return &MockInterface_UninstallRelease_Call{Call: _e.mock.On("UninstallRelease", ctx, releaseName, namespace)}
}

func (_c *MockInterface_UninstallRelease_Call) Run(run func(ctx context.Context, releaseName string, namespace string)) *MockInterface_UninstallRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInterface_UninstallRelease_Call) Return(err error) *MockInterface_UninstallRelease_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_UninstallRelease_Call) RunAndReturn(run func(ctx context.Context, releaseName string, namespace string) error) *MockInterface_UninstallRelease_Call {
	_c.Call.Return(run)
	return _c
}
