name: Cache KSail Binary
description: Restore or build the KSail binary from cache, handling path variations for different jobs.
author: Devantler Tech Platform Team

inputs:
  go-version:
    description: Go version from setup-go output, used to compute cache key.
    required: true
  source-hash:
    description: Hash of source files (from hashFiles() in workflow).
    required: true
  output-path:
    description: Target path for the binary. Can be relative (e.g., 'ksail') or absolute (e.g., '/usr/local/bin/ksail').
    required: false
    default: ksail

outputs:
  cache-hit:
    description: Whether the cache was hit ('true' or 'false').
    value: ${{ steps.ksail-cache.outputs.cache-hit }}
  binary-path:
    description: Absolute path to the prepared binary.
    value: ${{ steps.prepare.outputs.binary-path }}
  output-path-normalized:
    description: Normalized relative path to the binary (with leading './' stripped).
    value: ${{ steps.prepare.outputs.output-path-normalized }}

runs:
  using: composite
  steps:
    - name: 🔑 Compute ksail cache key
      id: ksail-cache-key
      shell: bash
      env:
        GO_VERSION: ${{ inputs.go-version }}
        SOURCE_HASH: ${{ inputs.source-hash }}
      run: |
        KSAIL_CACHE_KEY="${RUNNER_OS}-ksail-bin-${GO_VERSION}-${SOURCE_HASH}"
        printf 'value=%s\n' "$KSAIL_CACHE_KEY" >> "$GITHUB_OUTPUT"

    - name: ♻️ Restore cached ksail binary
      id: ksail-cache
      uses: actions/cache/restore@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: ./.cache/ksail
        key: ${{ steps.ksail-cache-key.outputs.value }}

    - name: 📦 Cache KSail Binary
      id: prepare
      shell: bash
      env:
        # Use pipe (|) instead of comma (,) so Go falls through to direct on ANY proxy
        # error (including 403), not just 404/410. Hardens CI against transient
        # proxy.golang.org outages. go.sum still verifies module integrity.
        GOPROXY: "https://proxy.golang.org|direct"
        CACHE_HIT: ${{ steps.ksail-cache.outputs.cache-hit }}
        OUTPUT_PATH: ${{ inputs.output-path }}
      run: |
        set -Eeuo pipefail

        # Validate output path does not escape repository with relative traversal
        if [[ "$OUTPUT_PATH" == ".." ]] || [[ "$OUTPUT_PATH" == ../* ]] || [[ "$OUTPUT_PATH" == */../* ]] || [[ "$OUTPUT_PATH" == */.. ]]; then
          echo "Error: output-path must not traverse parent directories (../), got: $OUTPUT_PATH" >&2
          exit 1
        fi

        # Handle absolute vs relative paths
        if [[ "$OUTPUT_PATH" = /* ]]; then
          # Absolute path - use as-is
          output_target="$OUTPUT_PATH"
        else
          # Relative path - strip leading './' for cleaner path construction
          output_target="${OUTPUT_PATH#./}"
        fi

        # Create output directory (use sudo for system paths)
        output_dir=$(dirname "$output_target")
        if [[ "$output_dir" = /usr* ]] || [[ "$output_dir" = /opt* ]] || [[ "$output_dir" = /bin* ]] || [[ "$output_dir" = /sbin* ]]; then
          sudo mkdir -p "$output_dir"
        else
          mkdir -p "$output_dir"
        fi

        if [ "$CACHE_HIT" = "true" ] && [ -f ./.cache/ksail ]; then
          # Use cached binary
          if [[ "$output_target" = /* ]]; then
            sudo cp ./.cache/ksail "$output_target"
            sudo chmod +x "$output_target"
          else
            cp ./.cache/ksail "$output_target"
            chmod +x "$output_target"
          fi
        else
          # Build binary (first generate embedded docs)
          mkdir -p ./.cache
          go generate ./pkg/svc/chat/...
          go build -ldflags="-s -w" -o ./.cache/ksail .
          # Copy to target location
          if [[ "$output_target" = /* ]]; then
            sudo cp ./.cache/ksail "$output_target"
            sudo chmod +x "$output_target"
          else
            cp ./.cache/ksail "$output_target"
            chmod +x "$output_target"
          fi
        fi

        # Output absolute path and normalized path
        if [[ "$output_target" = /* ]]; then
          echo "binary-path=$output_target" >> "$GITHUB_OUTPUT"
          echo "output-path-normalized=$output_target" >> "$GITHUB_OUTPUT"
        else
          echo "binary-path=$(realpath "$output_target")" >> "$GITHUB_OUTPUT"
          echo "output-path-normalized=$output_target" >> "$GITHUB_OUTPUT"
        fi

    - name: ♻️ Save ksail binary cache
      if: steps.ksail-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: ./.cache/ksail
        key: ${{ steps.ksail-cache-key.outputs.value }}
