name: Cache Cluster Images
description: |
  Caches container images from a KSail cluster's containerd runtime using
  ksail workload export/import commands and Docker daemon for efficient caching.

  The 'preload' operation loads images into the Docker daemon BEFORE cluster
  creation, allowing Kind and K3d to use locally cached images instead of
  pulling from the internet. This significantly reduces cluster creation time.

  The 'restore' operation (legacy) imports images AFTER cluster creation.
  The 'save' operation exports images from a running cluster for caching.

  Note: This action only supports Vanilla (Kind) and K3s (K3d) distributions.
  Talos clusters are not supported because the Talos Machine API does not
  expose image export functionality.

inputs:
  distribution:
    description: |
      Kubernetes distribution (Vanilla, K3s, Talos).
      Talos is silently skipped since it doesn't support image export/import.
    required: true
  operation:
    description: |
      Cache operation to perform:
      - 'preload': Restore cached images and load into Docker daemon (before cluster creation)
      - 'restore': Restore cached images and import to cluster (after cluster creation)
      - 'save': Export images from cluster and save to cache
    required: true
  cache-version:
    description: |
      Version salt for cache key. Bump this to invalidate all caches.
    required: false
    default: "v1"

outputs:
  cache-hit:
    description: Whether the cache was restored successfully
    value: ${{ steps.restore-cache-preload.outputs.cache-hit || steps.restore-cache.outputs.cache-hit || 'false' }}
  skipped:
    description: Whether the operation was skipped (e.g., Talos distribution)
    value: ${{ steps.check-support.outputs.skipped || 'false' }}

runs:
  using: composite
  steps:
    - name: ðŸ” Check distribution support
      id: check-support
      shell: bash
      env:
        DISTRIBUTION: ${{ inputs.distribution }}
        CACHE_VERSION: ${{ inputs.cache-version }}
        RUNNER_OS: ${{ runner.os }}
        RUNNER_ARCH: ${{ runner.arch }}
      run: |
        DIST_LOWER=$(echo "$DISTRIBUTION" | tr '[:upper:]' '[:lower:]')

        # Talos doesn't support image export/import via its Machine API
        if [[ "$DIST_LOWER" == "talos" ]]; then
          echo "â­ï¸ Skipping image cache for Talos (not supported by Talos API)"
          echo "skipped=true" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "skipped=false" >> "$GITHUB_OUTPUT"

        # Generate cache key based on distribution
        # Using distribution-only key allows sharing across providers
        CACHE_KEY="cluster-images-${CACHE_VERSION}-${DIST_LOWER}-${RUNNER_OS}-${RUNNER_ARCH}"
        echo "cache-key=$CACHE_KEY" >> "$GITHUB_OUTPUT"
        echo "ðŸ“¦ Cache key: $CACHE_KEY"

    # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    # PRELOAD operation: Download cached images and load into Docker daemon
    # (before cluster creation)
    # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

    - name: ðŸ“¥ Restore image cache for preload
      if: inputs.operation == 'preload' && steps.check-support.outputs.skipped != 'true'
      id: restore-cache-preload
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: /tmp/ksail-image-cache
        key: ${{ steps.check-support.outputs.cache-key }}
        restore-keys: |
          cluster-images-${{ inputs.cache-version }}-${{ inputs.distribution }}-${{ runner.os }}-

    - name: ðŸ“¥ Load cached images into Docker daemon
      if: inputs.operation == 'preload' && steps.check-support.outputs.skipped != 'true' && steps.restore-cache-preload.outputs.cache-hit == 'true'
      shell: bash
      run: |
        ARCHIVE="/tmp/ksail-image-cache/images.tar"
        if [[ -f "$ARCHIVE" ]]; then
          echo "ðŸ“¦ Loading cached images into Docker daemon from $ARCHIVE"
          docker load -i "$ARCHIVE" || {
            echo "âš ï¸ Docker load failed (non-fatal), cluster will pull images normally"
          }
        else
          echo "âš ï¸ Cache archive not found at $ARCHIVE"
        fi

    # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    # RESTORE operation: Download cached images and import to cluster
    # (after cluster creation - legacy method, kept for compatibility)
    # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

    - name: ðŸ“¥ Restore image cache
      if: inputs.operation == 'restore' && steps.check-support.outputs.skipped != 'true'
      id: restore-cache
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: /tmp/ksail-image-cache
        key: ${{ steps.check-support.outputs.cache-key }}
        restore-keys: |
          cluster-images-${{ inputs.cache-version }}-${{ inputs.distribution }}-${{ runner.os }}-

    - name: ðŸ“¥ Import cached images to cluster
      if: inputs.operation == 'restore' && steps.check-support.outputs.skipped != 'true' && steps.restore-cache.outputs.cache-hit == 'true'
      shell: bash
      run: |
        ARCHIVE="/tmp/ksail-image-cache/images.tar"
        if [[ -f "$ARCHIVE" ]]; then
          echo "ðŸ“¦ Importing cached images from $ARCHIVE"
          ksail workload import "$ARCHIVE" || {
            echo "âš ï¸ Image import failed (non-fatal), cluster will pull images normally"
          }
        else
          echo "âš ï¸ Cache archive not found at $ARCHIVE"
        fi

    # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    # SAVE operation: Export images from cluster and save to cache
    # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

    - name: ðŸ“¤ Export images from cluster
      if: inputs.operation == 'save' && steps.check-support.outputs.skipped != 'true'
      id: export-images
      shell: bash
      run: |
        mkdir -p /tmp/ksail-image-cache
        ARCHIVE="/tmp/ksail-image-cache/images.tar"

        echo "ðŸ“¦ Exporting cluster images to $ARCHIVE"
        ksail workload export "$ARCHIVE" || {
          echo "âš ï¸ Image export failed (non-fatal)"
          echo "export-failed=true" >> "$GITHUB_OUTPUT"
          exit 0
        }

        if [[ -f "$ARCHIVE" ]]; then
          SIZE=$(du -h "$ARCHIVE" | cut -f1)
          echo "âœ… Exported images archive: $SIZE"
          echo "export-failed=false" >> "$GITHUB_OUTPUT"
        else
          echo "âš ï¸ Export completed but archive not found"
          echo "export-failed=true" >> "$GITHUB_OUTPUT"
        fi

    - name: ðŸ’¾ Save image cache
      if: inputs.operation == 'save' && steps.check-support.outputs.skipped != 'true' && steps.export-images.outputs.export-failed != 'true'
      uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: /tmp/ksail-image-cache
        key: ${{ steps.check-support.outputs.cache-key }}
