name: Cache Cluster Images
description: |
  Caches container images from a KSail cluster's containerd runtime using
  ksail workload image export/import commands. This reduces image pull times
  and avoids flaky pulls in CI.

  Note: This action only supports Vanilla (Kind) and K3s (K3d) distributions.
  Talos clusters are not supported because the Talos Machine API does not
  expose image export functionality.

inputs:
  distribution:
    description: |
      Kubernetes distribution (Vanilla, K3s, Talos).
      Talos is silently skipped since it doesn't support image export/import.
    required: true
  operation:
    description: |
      Cache operation to perform:
      - 'restore': Restore cached images and import to cluster
      - 'save': Export images from cluster and save to cache
    required: true
  cache-version:
    description: |
      Version salt for cache key. Bump this to invalidate all caches.
    required: false
    default: "v1"

outputs:
  cache-hit:
    description: Whether the cache was restored successfully
    value: ${{ steps.restore-cache.outputs.cache-hit || 'false' }}
  skipped:
    description: Whether the operation was skipped (e.g., Talos distribution)
    value: ${{ steps.check-support.outputs.skipped || 'false' }}

runs:
  using: composite
  steps:
    - name: ðŸ” Check distribution support
      id: check-support
      shell: bash
      env:
        DISTRIBUTION: ${{ inputs.distribution }}
      run: |
        DIST_LOWER=$(echo "$DISTRIBUTION" | tr '[:upper:]' '[:lower:]')

        # Talos doesn't support image export/import via its Machine API
        if [[ "$DIST_LOWER" == "talos" ]]; then
          echo "â­ï¸ Skipping image cache for Talos (not supported by Talos API)"
          echo "skipped=true" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "skipped=false" >> "$GITHUB_OUTPUT"

        # Generate cache key based on distribution
        # Using distribution-only key allows sharing across providers
        CACHE_KEY="cluster-images-${{ inputs.cache-version }}-${DIST_LOWER}-${{ runner.os }}-${{ runner.arch }}"
        echo "cache-key=$CACHE_KEY" >> "$GITHUB_OUTPUT"
        echo "ðŸ“¦ Cache key: $CACHE_KEY"

    # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    # RESTORE operation: Download cached images and import to cluster
    # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

    - name: ðŸ“¥ Restore image cache
      if: inputs.operation == 'restore' && steps.check-support.outputs.skipped != 'true'
      id: restore-cache
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: /tmp/ksail-image-cache
        key: ${{ steps.check-support.outputs.cache-key }}
        restore-keys: |
          cluster-images-${{ inputs.cache-version }}-${{ inputs.distribution }}-${{ runner.os }}-

    - name: ðŸ“¥ Import cached images to cluster
      if: inputs.operation == 'restore' && steps.check-support.outputs.skipped != 'true' && steps.restore-cache.outputs.cache-hit == 'true'
      shell: bash
      run: |
        ARCHIVE="/tmp/ksail-image-cache/images.tar"
        if [[ -f "$ARCHIVE" ]]; then
          echo "ðŸ“¦ Importing cached images from $ARCHIVE"
          ksail workload image import "$ARCHIVE" || {
            echo "âš ï¸ Image import failed (non-fatal), cluster will pull images normally"
          }
        else
          echo "âš ï¸ Cache archive not found at $ARCHIVE"
        fi

    # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    # SAVE operation: Export images from cluster and save to cache
    # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

    - name: ðŸ“¤ Export images from cluster
      if: inputs.operation == 'save' && steps.check-support.outputs.skipped != 'true'
      id: export-images
      shell: bash
      run: |
        mkdir -p /tmp/ksail-image-cache
        ARCHIVE="/tmp/ksail-image-cache/images.tar"

        echo "ðŸ“¦ Exporting cluster images to $ARCHIVE"
        ksail workload image export "$ARCHIVE" || {
          echo "âš ï¸ Image export failed (non-fatal)"
          echo "export-failed=true" >> "$GITHUB_OUTPUT"
          exit 0
        }

        if [[ -f "$ARCHIVE" ]]; then
          SIZE=$(du -h "$ARCHIVE" | cut -f1)
          echo "âœ… Exported images archive: $SIZE"
          echo "export-failed=false" >> "$GITHUB_OUTPUT"
        else
          echo "âš ï¸ Export completed but archive not found"
          echo "export-failed=true" >> "$GITHUB_OUTPUT"
        fi

    - name: ðŸ’¾ Save image cache
      if: inputs.operation == 'save' && steps.check-support.outputs.skipped != 'true' && steps.export-images.outputs.export-failed != 'true'
      uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: /tmp/ksail-image-cache
        key: ${{ steps.check-support.outputs.cache-key }}
