package docker

import (
	"context"
	"io"

	"github.com/docker/docker/api/types"
	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/image"
	"github.com/docker/docker/api/types/network"
	"github.com/docker/docker/api/types/volume"
	"github.com/docker/docker/client"
	ocispec "github.com/opencontainers/image-spec/specs-go/v1"
)

// Client is the narrow subset of the upstream Docker Engine API that KSail
// actually uses. It exists so production signatures and generated mocks surface
// only the ~25 methods KSail calls, instead of the full 122-method
// github.com/docker/docker/client.APIClient.
//
// The concrete *client.Client returned by GetDockerClient satisfies this
// interface (see the compile-time assertion below). Callers that genuinely need
// the concrete type (the Kind and VCluster SDK injection points) use
// GetConcreteDockerClient instead.
//
// The interface deliberately lists the ~25 Docker Engine API methods KSail
// actually calls; narrowing the 122-method upstream APIClient is the whole
// point, so the method count is the floor, not bloat.
//
//nolint:interfacebloat // Intentionally mirrors only the Docker methods KSail uses.
type Client interface {
	// Close releases the resources held by the Docker client.
	Close() error

	// ContainerCreate creates a new container based on the given configuration.
	ContainerCreate(
		ctx context.Context,
		config *container.Config,
		hostConfig *container.HostConfig,
		networkingConfig *network.NetworkingConfig,
		platform *ocispec.Platform,
		containerName string,
	) (container.CreateResponse, error)
	// ContainerExecAttach attaches to an exec process in a running container.
	ContainerExecAttach(
		ctx context.Context,
		execID string,
		options container.ExecAttachOptions,
	) (types.HijackedResponse, error)
	// ContainerExecCreate creates a new exec configuration for a container.
	ContainerExecCreate(
		ctx context.Context,
		container string,
		options container.ExecOptions,
	) (container.ExecCreateResponse, error)
	// ContainerExecInspect returns information about a specific exec process.
	ContainerExecInspect(ctx context.Context, execID string) (container.ExecInspect, error)
	// ContainerInspect returns the container information for the given container ID.
	ContainerInspect(ctx context.Context, container string) (container.InspectResponse, error)
	// ContainerList returns the list of containers matching the given options.
	ContainerList(ctx context.Context, options container.ListOptions) ([]container.Summary, error)
	// ContainerLogs returns the logs generated by a container as a read closer.
	ContainerLogs(
		ctx context.Context,
		container string,
		options container.LogsOptions,
	) (io.ReadCloser, error)
	// ContainerRemove removes a container from the host.
	ContainerRemove(ctx context.Context, container string, options container.RemoveOptions) error
	// ContainerStart starts a container.
	ContainerStart(ctx context.Context, container string, options container.StartOptions) error
	// ContainerStop stops a container.
	ContainerStop(ctx context.Context, container string, options container.StopOptions) error
	// CopyFromContainer copies a resource out of a container.
	CopyFromContainer(
		ctx context.Context,
		container, srcPath string,
	) (io.ReadCloser, container.PathStat, error)
	// CopyToContainer copies content into a container at the given path.
	CopyToContainer(
		ctx context.Context,
		container, path string,
		content io.Reader,
		options container.CopyToContainerOptions,
	) error

	// ImageInspect returns the image information for the given image reference.
	ImageInspect(
		ctx context.Context,
		image string,
		inspectOpts ...client.ImageInspectOption,
	) (image.InspectResponse, error)
	// ImagePull pulls an image from a registry.
	ImagePull(ctx context.Context, ref string, options image.PullOptions) (io.ReadCloser, error)

	// NetworkConnect connects a container to an existing network.
	NetworkConnect(
		ctx context.Context,
		network, container string,
		config *network.EndpointSettings,
	) error
	// NetworkCreate creates a new network.
	NetworkCreate(
		ctx context.Context,
		name string,
		options network.CreateOptions,
	) (network.CreateResponse, error)
	// NetworkDisconnect disconnects a container from a network.
	NetworkDisconnect(ctx context.Context, network, container string, force bool) error
	// NetworkInspect returns information about a specific network.
	NetworkInspect(
		ctx context.Context,
		network string,
		options network.InspectOptions,
	) (network.Inspect, error)
	// NetworkList returns the list of networks matching the given options.
	NetworkList(ctx context.Context, options network.ListOptions) ([]network.Summary, error)
	// NetworkRemove removes an existing network.
	NetworkRemove(ctx context.Context, network string) error

	// Ping pings the Docker server and returns its capabilities.
	Ping(ctx context.Context) (types.Ping, error)

	// VolumeCreate creates a new volume.
	VolumeCreate(ctx context.Context, options volume.CreateOptions) (volume.Volume, error)
	// VolumeInspect returns information about a specific volume.
	VolumeInspect(ctx context.Context, volumeID string) (volume.Volume, error)
	// VolumeRemove removes an existing volume.
	VolumeRemove(ctx context.Context, volumeID string, force bool) error
}

// Compile-time assertion that the concrete upstream Docker client satisfies the
// narrow Client interface. If a future Docker SDK bump changes a signature this
// fails to build here instead of at every call site.
var _ Client = (*client.Client)(nil)
