package k3sbootstrap_test

import (
	"strings"
	"testing"

	k3sbootstrap "github.com/devantler-tech/ksail/v7/pkg/svc/bootstrap/k3s"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

// parsedConfig mirrors the k3s config.yaml subset Render emits, so tests assert
// on the parsed document rather than on brittle substrings.
type parsedConfig struct {
	ClusterInit bool     `yaml:"cluster-init"` //nolint:tagliatelle // k3s schema mandates the kebab-case key.
	Server      string   `yaml:"server"`
	Token       string   `yaml:"token"`
	TLSSAN      []string `yaml:"tls-san"` //nolint:tagliatelle // k3s schema mandates the kebab-case key.
	Disable     []string `yaml:"disable"`
	//nolint:tagliatelle // k3s schema mandates the kebab-case key.
	WriteKubeconfigMode string `yaml:"write-kubeconfig-mode"`
}

// parse asserts the document carries the managed-file header and is valid YAML,
// returning the decoded subset.
func parse(t *testing.T, config string) parsedConfig {
	t.Helper()

	require.True(t,
		strings.HasPrefix(config, "# Generated by ksail"),
		"config must begin with the managed-file header",
	)

	var cfg parsedConfig

	require.NoError(t, yaml.Unmarshal([]byte(config), &cfg), "config must be valid YAML")

	return cfg
}

func TestRenderServerInit(t *testing.T) {
	t.Parallel()

	config, err := k3sbootstrap.RenderConfig(k3sbootstrap.NodeConfig{
		Role:                k3sbootstrap.RoleServerInit,
		Token:               "shared-secret",
		TLSSANs:             []string{"k8s.example.com"},
		Disable:             []string{"traefik"},
		WriteKubeconfigMode: "0644",
	})
	require.NoError(t, err)

	cfg := parse(t, config)

	assert.True(t, cfg.ClusterInit, "the cluster-initialising server sets cluster-init")
	assert.Empty(t, cfg.Server, "the cluster-initialising server joins no existing server")
	assert.Equal(t, "shared-secret", cfg.Token)
	assert.Equal(t, []string{"k8s.example.com"}, cfg.TLSSAN)
	assert.Equal(t, []string{"traefik"}, cfg.Disable)
	assert.Equal(t, "0644", cfg.WriteKubeconfigMode)
}

func TestRenderServer(t *testing.T) {
	t.Parallel()

	config, err := k3sbootstrap.RenderConfig(k3sbootstrap.NodeConfig{
		Role:      k3sbootstrap.RoleServer,
		Token:     "shared-secret",
		ServerURL: "https://10.0.0.1:6443",
		Disable:   []string{"servicelb"},
	})
	require.NoError(t, err)

	cfg := parse(t, config)

	assert.False(t, cfg.ClusterInit, "an additional server joins rather than initialises")
	assert.Equal(t, "https://10.0.0.1:6443", cfg.Server)
	assert.Equal(t, "shared-secret", cfg.Token)
	assert.Equal(t, []string{"servicelb"}, cfg.Disable)
}

func TestRenderAgent(t *testing.T) {
	t.Parallel()

	config, err := k3sbootstrap.RenderConfig(k3sbootstrap.NodeConfig{
		Role:      k3sbootstrap.RoleAgent,
		Token:     "shared-secret",
		ServerURL: "https://10.0.0.1:6443",
	})
	require.NoError(t, err)

	cfg := parse(t, config)

	assert.False(t, cfg.ClusterInit)
	assert.Equal(t, "https://10.0.0.1:6443", cfg.Server)
	assert.Equal(t, "shared-secret", cfg.Token)
	assert.Empty(t, cfg.TLSSAN, "an agent renders no server-only keys")
	assert.Empty(t, cfg.Disable)
	assert.Empty(t, cfg.WriteKubeconfigMode)
}

func TestRenderSortsAndDropsEmptyListEntries(t *testing.T) {
	t.Parallel()

	config, err := k3sbootstrap.RenderConfig(k3sbootstrap.NodeConfig{
		Role:    k3sbootstrap.RoleServerInit,
		Token:   "shared-secret",
		TLSSANs: []string{"z.example.com", "", "a.example.com"},
		Disable: []string{"traefik", "servicelb"},
	})
	require.NoError(t, err)

	cfg := parse(t, config)

	assert.Equal(t, []string{"a.example.com", "z.example.com"}, cfg.TLSSAN,
		"TLS SANs are sorted and empty entries dropped for deterministic output")
	assert.Equal(t, []string{"servicelb", "traefik"}, cfg.Disable,
		"disabled components are sorted for deterministic output")
}

func TestRenderIsDeterministic(t *testing.T) {
	t.Parallel()

	cfg := k3sbootstrap.NodeConfig{
		Role:    k3sbootstrap.RoleServerInit,
		Token:   "shared-secret",
		TLSSANs: []string{"b", "a"},
		Disable: []string{"traefik"},
	}

	first, err := k3sbootstrap.RenderConfig(cfg)
	require.NoError(t, err)
	second, err := k3sbootstrap.RenderConfig(cfg)
	require.NoError(t, err)

	assert.Equal(t, first, second, "Render is pure: the same input yields byte-identical output")
}

type validationCase struct {
	cfg     k3sbootstrap.NodeConfig
	wantErr error
}

// validationErrorCases enumerates each per-role rule Render rejects, keyed by a
// readable subtest name. It lives apart from the test so the test body stays a
// thin loop over the cases.
func validationErrorCases() map[string]validationCase {
	return map[string]validationCase{
		"unknown role": {
			cfg:     k3sbootstrap.NodeConfig{Role: "worker", Token: "t"},
			wantErr: k3sbootstrap.ErrUnknownRole,
		},
		"missing token": {
			cfg:     k3sbootstrap.NodeConfig{Role: k3sbootstrap.RoleServerInit},
			wantErr: k3sbootstrap.ErrMissingToken,
		},
		"server-init with server url": {
			cfg: k3sbootstrap.NodeConfig{
				Role: k3sbootstrap.RoleServerInit, Token: "t", ServerURL: "https://10.0.0.1:6443",
			},
			wantErr: k3sbootstrap.ErrUnexpectedServerURL,
		},
		"joining server without url": {
			cfg:     k3sbootstrap.NodeConfig{Role: k3sbootstrap.RoleServer, Token: "t"},
			wantErr: k3sbootstrap.ErrMissingServerURL,
		},
		"agent without url": {
			cfg:     k3sbootstrap.NodeConfig{Role: k3sbootstrap.RoleAgent, Token: "t"},
			wantErr: k3sbootstrap.ErrMissingServerURL,
		},
		"non-https server url": {
			cfg: k3sbootstrap.NodeConfig{
				Role: k3sbootstrap.RoleAgent, Token: "t", ServerURL: "http://10.0.0.1:6443",
			},
			wantErr: k3sbootstrap.ErrInvalidServerURL,
		},
		"server url without host": {
			cfg: k3sbootstrap.NodeConfig{
				Role: k3sbootstrap.RoleAgent, Token: "t", ServerURL: "https://",
			},
			wantErr: k3sbootstrap.ErrInvalidServerURL,
		},
		"agent with tls sans": {
			cfg: k3sbootstrap.NodeConfig{
				Role: k3sbootstrap.RoleAgent, Token: "t",
				ServerURL: "https://10.0.0.1:6443", TLSSANs: []string{"k8s.example.com"},
			},
			wantErr: k3sbootstrap.ErrAgentServerOnlyOption,
		},
		"agent with disabled component": {
			cfg: k3sbootstrap.NodeConfig{
				Role: k3sbootstrap.RoleAgent, Token: "t",
				ServerURL: "https://10.0.0.1:6443", Disable: []string{"traefik"},
			},
			wantErr: k3sbootstrap.ErrAgentServerOnlyOption,
		},
		"agent with kubeconfig mode": {
			cfg: k3sbootstrap.NodeConfig{
				Role: k3sbootstrap.RoleAgent, Token: "t",
				ServerURL: "https://10.0.0.1:6443", WriteKubeconfigMode: "0644",
			},
			wantErr: k3sbootstrap.ErrAgentServerOnlyOption,
		},
	}
}

func TestRenderValidationErrors(t *testing.T) {
	t.Parallel()

	for name, testCase := range validationErrorCases() {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			config, err := k3sbootstrap.RenderConfig(testCase.cfg)
			require.ErrorIs(t, err, testCase.wantErr)
			assert.Empty(t, config, "no document is returned on a validation error")
		})
	}
}
