package k3sbootstrap

import (
	"fmt"
	"net/url"
	"sort"

	"gopkg.in/yaml.v3"
)

// header is prepended to every rendered config so an operator inspecting a node
// can see the file is ksail-managed rather than hand-written.
const header = "# Generated by ksail — k3s node configuration. Do not edit.\n"

// Role is a k3s node's role within the cluster. It selects the shape of the
// rendered config: which keys are emitted and which inputs are valid.
type Role string

const (
	// RoleServerInit is the first control-plane node, which initialises a new
	// cluster (config.yaml `cluster-init: true`) and joins no existing server.
	RoleServerInit Role = "server-init"
	// RoleServer is an additional control-plane node that joins the cluster the
	// RoleServerInit node started, via its ServerURL.
	RoleServer Role = "server"
	// RoleAgent is a worker node that joins the cluster via its ServerURL and runs
	// no control-plane components.
	RoleAgent Role = "agent"
)

// NodeConfig is the typed input for [Render]: everything needed to render one
// k3s node's /etc/rancher/k3s/config.yaml. It performs no I/O.
type NodeConfig struct {
	// Role is the node's role in the cluster (required). It governs which other
	// fields are valid — see the per-field notes and the package's sentinel errors.
	Role Role
	// Token is the shared cluster token every node uses to establish or join the
	// cluster (required for all roles).
	Token string
	// ServerURL is the https URL of an existing server to register against.
	// Required for RoleServer and RoleAgent; must be empty for RoleServerInit
	// (which starts the cluster).
	ServerURL string
	// TLSSANs are extra Subject Alternative Names added to the API server
	// certificate (e.g. a load-balancer hostname or floating IP). Server-only:
	// must be empty for RoleAgent. Rendered in sorted order for determinism.
	TLSSANs []string
	// Disable lists bundled components to switch off (e.g. "traefik",
	// "servicelb"). Server-only: must be empty for RoleAgent. Rendered in sorted
	// order for determinism.
	Disable []string
	// WriteKubeconfigMode is the file mode for the generated kubeconfig (e.g.
	// "0644"). Server-only: must be empty for RoleAgent.
	WriteKubeconfigMode string
}

// renderedConfig is the subset of the k3s config.yaml schema this package emits.
// Keys are k3s's kebab-case flag names; omitempty keeps each node's config to
// exactly the keys that apply to its role.
type renderedConfig struct {
	//nolint:tagliatelle // k3s's config schema mandates the kebab-case key "cluster-init".
	ClusterInit bool   `yaml:"cluster-init,omitempty"`
	Server      string `yaml:"server,omitempty"`
	Token       string `yaml:"token,omitempty"`
	//nolint:tagliatelle // k3s's config schema mandates the kebab-case key "tls-san".
	TLSSAN  []string `yaml:"tls-san,omitempty"`
	Disable []string `yaml:"disable,omitempty"`
	//nolint:tagliatelle // k3s's config schema mandates the kebab-case key "write-kubeconfig-mode".
	WriteKubeconfigMode string `yaml:"write-kubeconfig-mode,omitempty"`
}

// Render maps cfg to the content of /etc/rancher/k3s/config.yaml for that node.
// The returned string is a complete YAML document (prefixed with a managed-file
// header) suitable for delivery via cloud-init write_files.
//
// Render is pure and never returns a partially-valid document: any configuration
// error (see the package's sentinel errors) is reported instead. Because the
// output is YAML rather than a shell command, values are encoded by the YAML
// marshaller and carry no shell-quoting or injection surface.
func Render(cfg NodeConfig) (string, error) {
	err := cfg.validate()
	if err != nil {
		return "", err
	}

	rendered := renderedConfig{Token: cfg.Token}

	if cfg.Role == RoleServerInit {
		rendered.ClusterInit = true
	} else {
		rendered.Server = cfg.ServerURL
	}

	// Server-only options are validated empty for agents, so copying them
	// unconditionally for the two server roles is sufficient.
	if cfg.Role != RoleAgent {
		rendered.TLSSAN = sortedCopy(cfg.TLSSANs)
		rendered.Disable = sortedCopy(cfg.Disable)
		rendered.WriteKubeconfigMode = cfg.WriteKubeconfigMode
	}

	out, err := yaml.Marshal(rendered)
	if err != nil {
		// Unreachable in practice: renderedConfig is a fixed struct of strings,
		// bools and string slices, which yaml.Marshal cannot fail to encode.
		// Surfaced rather than dropped so a future schema change that breaks this is
		// not silently ignored.
		return "", fmt.Errorf("marshalling k3s config: %w", err)
	}

	return header + string(out), nil
}

// validate enforces the per-role rules before rendering: a token is always
// required; the cluster-initialising server joins nothing while the other roles
// must name a valid https server; and an agent may not carry server-only options.
func (cfg NodeConfig) validate() error {
	if !cfg.Role.valid() {
		return ErrInvalidRole
	}

	if cfg.Token == "" {
		return ErrMissingToken
	}

	err := cfg.validateServerURLForRole()
	if err != nil {
		return err
	}

	if cfg.Role == RoleAgent && cfg.hasServerOnlyOptions() {
		return ErrAgentServerOnlyOption
	}

	return nil
}

// valid reports whether r is one of the three recognised node roles.
func (r Role) valid() bool {
	switch r {
	case RoleServerInit, RoleServer, RoleAgent:
		return true
	default:
		return false
	}
}

// validateServerURLForRole applies the per-role server-URL rule: the
// cluster-initialising server must name no server (it starts the cluster), while
// a joining node must name a valid one.
func (cfg NodeConfig) validateServerURLForRole() error {
	if cfg.Role == RoleServerInit {
		if cfg.ServerURL != "" {
			return ErrServerInitWithServerURL
		}

		return nil
	}

	return validateServerURL(cfg.ServerURL)
}

// hasServerOnlyOptions reports whether cfg carries any control-plane-only option,
// none of which an agent may set.
func (cfg NodeConfig) hasServerOnlyOptions() bool {
	return len(cfg.TLSSANs) > 0 || len(cfg.Disable) > 0 || cfg.WriteKubeconfigMode != ""
}

// validateServerURL requires a joining node's server URL to be a well-formed
// https URL with a host, so a node is never rendered with a URL it could not
// connect to.
func validateServerURL(serverURL string) error {
	if serverURL == "" {
		return ErrMissingServerURL
	}

	parsed, err := url.Parse(serverURL)
	if err != nil || parsed.Scheme != "https" || parsed.Host == "" {
		return ErrInvalidServerURL
	}

	return nil
}

// sortedCopy returns a sorted copy of values with empty entries dropped, so the
// rendered list is deterministic and free of blank items. It never mutates the
// caller's slice and returns nil for an all-empty input so the key is omitted.
func sortedCopy(values []string) []string {
	out := make([]string, 0, len(values))

	for _, value := range values {
		if value != "" {
			out = append(out, value)
		}
	}

	if len(out) == 0 {
		return nil
	}

	sort.Strings(out)

	return out
}
