package k3sbootstrap

import (
	"fmt"
	"net/url"

	"github.com/devantler-tech/ksail/v7/pkg/svc/bootstrap/internal/sliceutil"
	"gopkg.in/yaml.v3"
)

// configHeader is prepended to every rendered config so an operator inspecting a
// node can see the file is ksail-managed rather than hand-written.
const configHeader = "# Generated by ksail — k3s node configuration. Do not edit.\n"

// NodeConfig is the typed input for [RenderConfig]: everything needed to render
// one k3s node's /etc/rancher/k3s/config.yaml. It performs no I/O. It is the
// declarative-file counterpart to [InstallConfig] (which renders the install
// *command*): the config file carries the node's standing settings, and both use
// the same [Role] values.
type NodeConfig struct {
	// Role is the node's role in the cluster (required). It governs which other
	// fields are valid — see the per-field notes and the package's sentinel errors.
	Role Role
	// Token is the shared cluster token every node uses to establish or join the
	// cluster (required for all roles).
	Token string
	// ServerURL is the https URL of an existing server to register against.
	// Required for RoleServer and RoleAgent; must be empty for RoleServerInit
	// (which starts the cluster).
	ServerURL string
	// TLSSANs are extra Subject Alternative Names added to the API server
	// certificate (e.g. a load-balancer hostname or floating IP). Server-only:
	// must be empty for RoleAgent. Rendered in sorted order for determinism.
	TLSSANs []string
	// Disable lists bundled components to switch off (e.g. "traefik",
	// "servicelb"). Server-only: must be empty for RoleAgent. Rendered in sorted
	// order for determinism.
	Disable []string
	// WriteKubeconfigMode is the file mode for the generated kubeconfig (e.g.
	// "0644"). Server-only: must be empty for RoleAgent.
	WriteKubeconfigMode string
}

// renderedConfig is the subset of the k3s config.yaml schema this package emits.
// Keys are k3s's kebab-case flag names; omitempty keeps each node's config to
// exactly the keys that apply to its role.
type renderedConfig struct {
	//nolint:tagliatelle // k3s's config schema mandates the kebab-case key "cluster-init".
	ClusterInit bool   `yaml:"cluster-init,omitempty"`
	Server      string `yaml:"server,omitempty"`
	Token       string `yaml:"token,omitempty"`
	//nolint:tagliatelle // k3s's config schema mandates the kebab-case key "tls-san".
	TLSSAN  []string `yaml:"tls-san,omitempty"`
	Disable []string `yaml:"disable,omitempty"`
	//nolint:tagliatelle // k3s's config schema mandates the kebab-case key "write-kubeconfig-mode".
	WriteKubeconfigMode string `yaml:"write-kubeconfig-mode,omitempty"`
}

// RenderConfig maps cfg to the content of /etc/rancher/k3s/config.yaml for that
// node. The returned string is a complete YAML document (prefixed with a
// managed-file header) suitable for delivery via cloud-init write_files.
//
// RenderConfig is pure and never returns a partially-valid document: any
// configuration error (see the package's sentinel errors) is reported instead.
// Because the output is YAML rather than a shell command, values are encoded by
// the YAML marshaller and carry no shell-quoting or injection surface.
func RenderConfig(cfg NodeConfig) (string, error) {
	err := cfg.validate()
	if err != nil {
		return "", err
	}

	rendered := renderedConfig{Token: cfg.Token}

	if cfg.Role == RoleServerInit {
		rendered.ClusterInit = true
	} else {
		rendered.Server = cfg.ServerURL
	}

	// Server-only options are validated empty for agents, so copying them
	// unconditionally for the two server roles is sufficient.
	if cfg.Role != RoleAgent {
		rendered.TLSSAN = sliceutil.SortedNonEmpty(cfg.TLSSANs)
		rendered.Disable = sliceutil.SortedNonEmpty(cfg.Disable)
		rendered.WriteKubeconfigMode = cfg.WriteKubeconfigMode
	}

	out, err := yaml.Marshal(rendered)
	if err != nil {
		// Unreachable in practice: renderedConfig is a fixed struct of strings,
		// bools and string slices, which yaml.Marshal cannot fail to encode.
		// Surfaced rather than dropped so a future schema change that breaks this is
		// not silently ignored.
		return "", fmt.Errorf("marshalling k3s config: %w", err)
	}

	return configHeader + string(out), nil
}

// validate enforces the per-role rules before rendering: a token is always
// required; the cluster-initialising server joins nothing while the other roles
// must name a valid https server; and an agent may not carry server-only options.
// The sentinels are shared with the install-command renderer ([InstallConfig])
// wherever the rule is the same.
func (cfg NodeConfig) validate() error {
	if !cfg.Role.valid() {
		return ErrUnknownRole
	}

	if cfg.Token == "" {
		return ErrMissingToken
	}

	err := cfg.validateServerURLForRole()
	if err != nil {
		return err
	}

	if cfg.Role == RoleAgent && cfg.hasServerOnlyOptions() {
		return ErrAgentServerOnlyOption
	}

	return nil
}

// valid reports whether r is one of the three recognised node roles.
func (r Role) valid() bool {
	switch r {
	case RoleServerInit, RoleServer, RoleAgent:
		return true
	default:
		return false
	}
}

// validateServerURLForRole applies the per-role server-URL rule: the
// cluster-initialising server must name no server (it starts the cluster), while
// a joining node must name a valid one.
func (cfg NodeConfig) validateServerURLForRole() error {
	if cfg.Role == RoleServerInit {
		if cfg.ServerURL != "" {
			return ErrUnexpectedServerURL
		}

		return nil
	}

	return validateServerURL(cfg.ServerURL)
}

// hasServerOnlyOptions reports whether cfg carries any control-plane-only option,
// none of which an agent may set.
func (cfg NodeConfig) hasServerOnlyOptions() bool {
	return len(cfg.TLSSANs) > 0 || len(cfg.Disable) > 0 || cfg.WriteKubeconfigMode != ""
}

// validateServerURL requires a joining node's server URL to be a well-formed
// https URL with a host, so a node is never rendered with a URL it could not
// connect to.
func validateServerURL(serverURL string) error {
	if serverURL == "" {
		return ErrMissingServerURL
	}

	parsed, err := url.Parse(serverURL)
	if err != nil || parsed.Scheme != "https" || parsed.Host == "" {
		return ErrInvalidServerURL
	}

	return nil
}
