package k3sbootstrap_test

import (
	"strings"
	"testing"

	k3sbootstrap "github.com/devantler-tech/ksail/v7/pkg/svc/bootstrap/k3s"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

// parsedConfig mirrors the k3s config.yaml subset Render emits, so tests assert
// on the parsed document rather than on brittle substrings.
type parsedConfig struct {
	ClusterInit bool     `yaml:"cluster-init"` //nolint:tagliatelle // k3s schema mandates the kebab-case key.
	Server      string   `yaml:"server"`
	Token       string   `yaml:"token"`
	TLSSAN      []string `yaml:"tls-san"` //nolint:tagliatelle // k3s schema mandates the kebab-case key.
	Disable     []string `yaml:"disable"`
	//nolint:tagliatelle // k3s schema mandates the kebab-case key.
	WriteKubeconfigMode string `yaml:"write-kubeconfig-mode"`
}

// parse asserts the document carries the managed-file header and is valid YAML,
// returning the decoded subset.
func parse(t *testing.T, config string) parsedConfig {
	t.Helper()

	require.True(t,
		strings.HasPrefix(config, "# Generated by ksail"),
		"config must begin with the managed-file header",
	)

	var cfg parsedConfig

	require.NoError(t, yaml.Unmarshal([]byte(config), &cfg), "config must be valid YAML")

	return cfg
}

func TestRenderServerInit(t *testing.T) {
	t.Parallel()

	config, err := k3sbootstrap.Render(k3sbootstrap.NodeConfig{
		Role:                k3sbootstrap.RoleServerInit,
		Token:               "shared-secret",
		TLSSANs:             []string{"k8s.example.com"},
		Disable:             []string{"traefik"},
		WriteKubeconfigMode: "0644",
	})
	require.NoError(t, err)

	cfg := parse(t, config)

	assert.True(t, cfg.ClusterInit, "the cluster-initialising server sets cluster-init")
	assert.Empty(t, cfg.Server, "the cluster-initialising server joins no existing server")
	assert.Equal(t, "shared-secret", cfg.Token)
	assert.Equal(t, []string{"k8s.example.com"}, cfg.TLSSAN)
	assert.Equal(t, []string{"traefik"}, cfg.Disable)
	assert.Equal(t, "0644", cfg.WriteKubeconfigMode)
}

func TestRenderServer(t *testing.T) {
	t.Parallel()

	config, err := k3sbootstrap.Render(k3sbootstrap.NodeConfig{
		Role:      k3sbootstrap.RoleServer,
		Token:     "shared-secret",
		ServerURL: "https://10.0.0.1:6443",
		Disable:   []string{"servicelb"},
	})
	require.NoError(t, err)

	cfg := parse(t, config)

	assert.False(t, cfg.ClusterInit, "an additional server joins rather than initialises")
	assert.Equal(t, "https://10.0.0.1:6443", cfg.Server)
	assert.Equal(t, "shared-secret", cfg.Token)
	assert.Equal(t, []string{"servicelb"}, cfg.Disable)
}

func TestRenderAgent(t *testing.T) {
	t.Parallel()

	config, err := k3sbootstrap.Render(k3sbootstrap.NodeConfig{
		Role:      k3sbootstrap.RoleAgent,
		Token:     "shared-secret",
		ServerURL: "https://10.0.0.1:6443",
	})
	require.NoError(t, err)

	cfg := parse(t, config)

	assert.False(t, cfg.ClusterInit)
	assert.Equal(t, "https://10.0.0.1:6443", cfg.Server)
	assert.Equal(t, "shared-secret", cfg.Token)
	assert.Empty(t, cfg.TLSSAN, "an agent renders no server-only keys")
	assert.Empty(t, cfg.Disable)
	assert.Empty(t, cfg.WriteKubeconfigMode)
}

func TestRenderSortsAndDropsEmptyListEntries(t *testing.T) {
	t.Parallel()

	config, err := k3sbootstrap.Render(k3sbootstrap.NodeConfig{
		Role:    k3sbootstrap.RoleServerInit,
		Token:   "shared-secret",
		TLSSANs: []string{"z.example.com", "", "a.example.com"},
		Disable: []string{"traefik", "servicelb"},
	})
	require.NoError(t, err)

	cfg := parse(t, config)

	assert.Equal(t, []string{"a.example.com", "z.example.com"}, cfg.TLSSAN,
		"TLS SANs are sorted and empty entries dropped for deterministic output")
	assert.Equal(t, []string{"servicelb", "traefik"}, cfg.Disable,
		"disabled components are sorted for deterministic output")
}

func TestRenderIsDeterministic(t *testing.T) {
	t.Parallel()

	cfg := k3sbootstrap.NodeConfig{
		Role:    k3sbootstrap.RoleServerInit,
		Token:   "shared-secret",
		TLSSANs: []string{"b", "a"},
		Disable: []string{"traefik"},
	}

	first, err := k3sbootstrap.Render(cfg)
	require.NoError(t, err)
	second, err := k3sbootstrap.Render(cfg)
	require.NoError(t, err)

	assert.Equal(t, first, second, "Render is pure: the same input yields byte-identical output")
}

type validationCase struct {
	cfg     k3sbootstrap.NodeConfig
	wantErr error
}

// validationErrorCases enumerates each per-role rule Render rejects, keyed by a
// readable subtest name. It lives apart from the test so the test body stays a
// thin loop over the cases.
func validationErrorCases() map[string]validationCase {
	return map[string]validationCase{
		"unknown role": {
			cfg:     k3sbootstrap.NodeConfig{Role: "worker", Token: "t"},
			wantErr: k3sbootstrap.ErrInvalidRole,
		},
		"missing token": {
			cfg:     k3sbootstrap.NodeConfig{Role: k3sbootstrap.RoleServerInit},
			wantErr: k3sbootstrap.ErrMissingToken,
		},
		"server-init with server url": {
			cfg: k3sbootstrap.NodeConfig{
				Role: k3sbootstrap.RoleServerInit, Token: "t", ServerURL: "https://10.0.0.1:6443",
			},
			wantErr: k3sbootstrap.ErrServerInitWithServerURL,
		},
		"joining server without url": {
			cfg:     k3sbootstrap.NodeConfig{Role: k3sbootstrap.RoleServer, Token: "t"},
			wantErr: k3sbootstrap.ErrMissingServerURL,
		},
		"agent without url": {
			cfg:     k3sbootstrap.NodeConfig{Role: k3sbootstrap.RoleAgent, Token: "t"},
			wantErr: k3sbootstrap.ErrMissingServerURL,
		},
		"non-https server url": {
			cfg: k3sbootstrap.NodeConfig{
				Role: k3sbootstrap.RoleAgent, Token: "t", ServerURL: "http://10.0.0.1:6443",
			},
			wantErr: k3sbootstrap.ErrInvalidServerURL,
		},
		"server url without host": {
			cfg: k3sbootstrap.NodeConfig{
				Role: k3sbootstrap.RoleAgent, Token: "t", ServerURL: "https://",
			},
			wantErr: k3sbootstrap.ErrInvalidServerURL,
		},
		"agent with tls sans": {
			cfg: k3sbootstrap.NodeConfig{
				Role: k3sbootstrap.RoleAgent, Token: "t",
				ServerURL: "https://10.0.0.1:6443", TLSSANs: []string{"k8s.example.com"},
			},
			wantErr: k3sbootstrap.ErrAgentServerOnlyOption,
		},
		"agent with disabled component": {
			cfg: k3sbootstrap.NodeConfig{
				Role: k3sbootstrap.RoleAgent, Token: "t",
				ServerURL: "https://10.0.0.1:6443", Disable: []string{"traefik"},
			},
			wantErr: k3sbootstrap.ErrAgentServerOnlyOption,
		},
		"agent with kubeconfig mode": {
			cfg: k3sbootstrap.NodeConfig{
				Role: k3sbootstrap.RoleAgent, Token: "t",
				ServerURL: "https://10.0.0.1:6443", WriteKubeconfigMode: "0644",
			},
			wantErr: k3sbootstrap.ErrAgentServerOnlyOption,
		},
	}
}

func TestRenderValidationErrors(t *testing.T) {
	t.Parallel()

	for name, testCase := range validationErrorCases() {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			config, err := k3sbootstrap.Render(testCase.cfg)
			require.ErrorIs(t, err, testCase.wantErr)
			assert.Empty(t, config, "no document is returned on a validation error")
		})
	}
}

func TestRenderServerInitMinimal(t *testing.T) {
	t.Parallel()

	// A cluster-initialising server needs only a role and a token; all optional
	// keys must be absent from the output when not supplied.
	config, err := k3sbootstrap.Render(k3sbootstrap.NodeConfig{
		Role:  k3sbootstrap.RoleServerInit,
		Token: "secret",
	})
	require.NoError(t, err)

	cfg := parse(t, config)

	assert.True(t, cfg.ClusterInit)
	assert.Equal(t, "secret", cfg.Token)
	assert.Empty(t, cfg.Server)
	assert.Empty(t, cfg.TLSSAN, "tls-san must be absent when not provided")
	assert.Empty(t, cfg.Disable, "disable must be absent when not provided")
	assert.Empty(t, cfg.WriteKubeconfigMode, "write-kubeconfig-mode must be absent when not provided")
}

func TestRenderServerWithAllOptions(t *testing.T) {
	t.Parallel()

	// A joining server may carry every optional server-only option; all of them
	// must appear in the rendered output.
	config, err := k3sbootstrap.Render(k3sbootstrap.NodeConfig{
		Role:                k3sbootstrap.RoleServer,
		Token:               "shared-secret",
		ServerURL:           "https://10.0.0.1:6443",
		TLSSANs:             []string{"lb.example.com", "10.0.0.2"},
		Disable:             []string{"traefik", "servicelb"},
		WriteKubeconfigMode: "0640",
	})
	require.NoError(t, err)

	cfg := parse(t, config)

	assert.False(t, cfg.ClusterInit)
	assert.Equal(t, "https://10.0.0.1:6443", cfg.Server)
	assert.Equal(t, "shared-secret", cfg.Token)
	// Both lists are sorted by Render.
	assert.Equal(t, []string{"10.0.0.2", "lb.example.com"}, cfg.TLSSAN)
	assert.Equal(t, []string{"servicelb", "traefik"}, cfg.Disable)
	assert.Equal(t, "0640", cfg.WriteKubeconfigMode)
}

func TestRenderServerInitEmptyOptionalSlicesOmitted(t *testing.T) {
	t.Parallel()

	// Supplying an explicitly empty (non-nil) slice for TLSSANs or Disable must
	// produce the same output as omitting the field — the YAML must not carry
	// empty list keys.
	config, err := k3sbootstrap.Render(k3sbootstrap.NodeConfig{
		Role:    k3sbootstrap.RoleServerInit,
		Token:   "tok",
		TLSSANs: []string{},
		Disable: []string{},
	})
	require.NoError(t, err)

	cfg := parse(t, config)

	assert.Empty(t, cfg.TLSSAN, "empty TLSSANs slice must not appear in rendered YAML")
	assert.Empty(t, cfg.Disable, "empty Disable slice must not appear in rendered YAML")
	// And the raw YAML must not contain the keys at all.
	assert.NotContains(t, config, "tls-san")
	assert.NotContains(t, config, "disable")
}

func TestRenderServerInitAllBlankTLSSANsDropped(t *testing.T) {
	t.Parallel()

	// A TLSSANs slice containing only empty strings must be treated as if no
	// SANs were provided: the key is omitted from the output.
	config, err := k3sbootstrap.Render(k3sbootstrap.NodeConfig{
		Role:    k3sbootstrap.RoleServerInit,
		Token:   "tok",
		TLSSANs: []string{"", "", ""},
	})
	require.NoError(t, err)

	cfg := parse(t, config)

	assert.Empty(t, cfg.TLSSAN)
	assert.NotContains(t, config, "tls-san")
}

func TestRenderRoleConstants(t *testing.T) {
	t.Parallel()

	// The exported Role constants must carry the exact string values k3s expects
	// in its config schema, since they are used as the role identifier.
	assert.Equal(t, k3sbootstrap.Role("server-init"), k3sbootstrap.RoleServerInit)
	assert.Equal(t, k3sbootstrap.Role("server"), k3sbootstrap.RoleServer)
	assert.Equal(t, k3sbootstrap.Role("agent"), k3sbootstrap.RoleAgent)
}

func TestRenderEmptyRoleIsInvalid(t *testing.T) {
	t.Parallel()

	// A zero-value Role (empty string) must be rejected as ErrInvalidRole.
	config, err := k3sbootstrap.Render(k3sbootstrap.NodeConfig{
		Role:  k3sbootstrap.Role(""),
		Token: "tok",
	})
	require.ErrorIs(t, err, k3sbootstrap.ErrInvalidRole)
	assert.Empty(t, config)
}

func TestRenderServerURLWithPathIsValid(t *testing.T) {
	t.Parallel()

	// A server URL that contains a path component is still a valid https URL
	// with a host and must be accepted — k3s accepts such URLs.
	config, err := k3sbootstrap.Render(k3sbootstrap.NodeConfig{
		Role:      k3sbootstrap.RoleAgent,
		Token:     "tok",
		ServerURL: "https://10.0.0.1:6443/api",
	})
	require.NoError(t, err)

	cfg := parse(t, config)

	assert.Equal(t, "https://10.0.0.1:6443/api", cfg.Server)
}

func TestRenderHeaderIsPresent(t *testing.T) {
	t.Parallel()

	// Every rendered config must start with the managed-file comment so an
	// operator can identify ksail-managed files at a glance.
	config, err := k3sbootstrap.Render(k3sbootstrap.NodeConfig{
		Role:  k3sbootstrap.RoleServerInit,
		Token: "tok",
	})
	require.NoError(t, err)

	assert.True(t, strings.HasPrefix(config, "# Generated by ksail"),
		"rendered config must begin with the managed-file header")
}

func TestRenderAgentDoesNotSetClusterInit(t *testing.T) {
	t.Parallel()

	// An agent node must never emit cluster-init: true, even though the YAML
	// unmarshaller defaults the bool to false when the key is absent.
	config, err := k3sbootstrap.Render(k3sbootstrap.NodeConfig{
		Role:      k3sbootstrap.RoleAgent,
		Token:     "tok",
		ServerURL: "https://10.0.0.1:6443",
	})
	require.NoError(t, err)

	assert.NotContains(t, config, "cluster-init",
		"agent config must not contain cluster-init key")
}

func TestRenderServerDoesNotSetClusterInit(t *testing.T) {
	t.Parallel()

	// A joining server must not emit cluster-init: it joins an existing cluster
	// rather than initialising one.
	config, err := k3sbootstrap.Render(k3sbootstrap.NodeConfig{
		Role:      k3sbootstrap.RoleServer,
		Token:     "tok",
		ServerURL: "https://10.0.0.1:6443",
	})
	require.NoError(t, err)

	assert.NotContains(t, config, "cluster-init",
		"joining server config must not contain cluster-init key")
}

func TestRenderTokenWithSpecialCharacters(t *testing.T) {
	t.Parallel()

	// A token containing YAML-special characters must survive the marshal/unmarshal
	// round-trip intact; the YAML encoder handles quoting as needed.
	token := "abc:def@ghi!jkl#mno$pqr%stu^vwx&yz"

	config, err := k3sbootstrap.Render(k3sbootstrap.NodeConfig{
		Role:  k3sbootstrap.RoleServerInit,
		Token: token,
	})
	require.NoError(t, err)

	cfg := parse(t, config)

	assert.Equal(t, token, cfg.Token,
		"token with special characters must round-trip through YAML encoding unchanged")
}
