//nolint:funlen // Table-driven tests are naturally long.
package cluster_test

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"os"
	"path/filepath"
	"testing"

	cluster "github.com/devantler-tech/ksail/v6/pkg/cli/cmd/cluster"
	"github.com/devantler-tech/ksail/v6/pkg/svc/provisioner/cluster/clusterupdate"
	"github.com/spf13/cobra"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

func TestPrepareOutputPath(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		path    string
		wantErr bool
	}{
		{
			name:    "simple file in current dir",
			path:    filepath.Join(t.TempDir(), "backup.tar.gz"),
			wantErr: false,
		},
		{
			name:    "nested directory creation",
			path:    filepath.Join(t.TempDir(), "sub", "dir", "backup.tar.gz"),
			wantErr: false,
		},
		{
			name:    "current directory",
			path:    "backup.tar.gz",
			wantErr: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result, err := cluster.ExportPrepareOutputPath(tt.path)
			if tt.wantErr {
				require.Error(t, err)
			} else {
				require.NoError(t, err)
				assert.NotEmpty(t, result)
			}
		})
	}
}

func TestPrintBackupSummary(t *testing.T) {
	t.Parallel()

	t.Run("existing file", func(t *testing.T) {
		t.Parallel()

		tmpFile := filepath.Join(t.TempDir(), "test.tar.gz")
		require.NoError(t, os.WriteFile(tmpFile, []byte("test data"), 0o600))

		var buf bytes.Buffer
		cluster.ExportPrintBackupSummary(&buf, tmpFile)

		output := buf.String()
		assert.Contains(t, output, "Backup completed successfully")
		assert.Contains(t, output, "Archive size:")
	})

	t.Run("nonexistent file", func(t *testing.T) {
		t.Parallel()

		var buf bytes.Buffer
		cluster.ExportPrintBackupSummary(&buf, "/nonexistent/path")

		output := buf.String()
		assert.Contains(t, output, "Backup completed successfully")
		assert.NotContains(t, output, "Archive size:")
	})
}

func TestClusterScopedResourceTypes(t *testing.T) {
	t.Parallel()

	types := cluster.ExportClusterScopedResourceTypes()
	assert.True(t, types["customresourcedefinitions"])
	assert.True(t, types["namespaces"])
	assert.True(t, types["storageclasses"])
	assert.True(t, types["persistentvolumes"])
	assert.True(t, types["clusterroles"])
	assert.True(t, types["clusterrolebindings"])
	assert.False(t, types["pods"])
	assert.False(t, types["deployments"])
	assert.Len(t, types, 6)
}

func TestRemoveAutoGeneratedJobLabels(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name          string
		labels        map[string]string
		expectLabels  map[string]string
		expectRemoved bool
	}{
		{
			name: "removes batch controller-uid",
			labels: map[string]string{
				"batch.kubernetes.io/controller-uid": "abc123",
				"app":                                "myapp",
			},
			expectLabels: map[string]string{
				"app": "myapp",
			},
		},
		{
			name: "removes controller-uid",
			labels: map[string]string{
				"controller-uid": "abc123",
				"app":            "myapp",
			},
			expectLabels: map[string]string{
				"app": "myapp",
			},
		},
		{
			name: "removes both auto-generated labels",
			labels: map[string]string{
				"batch.kubernetes.io/controller-uid": "abc123",
				"controller-uid":                     "def456",
				"app":                                "myapp",
			},
			expectLabels: map[string]string{
				"app": "myapp",
			},
		},
		{
			name: "removes entire labels field when empty after cleanup",
			labels: map[string]string{
				"batch.kubernetes.io/controller-uid": "abc123",
				"controller-uid":                     "def456",
			},
			expectRemoved: true,
		},
		{
			name:     "no labels to remove",
			labels:   map[string]string{"app": "myapp"},
			expectLabels: map[string]string{"app": "myapp"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			obj := &unstructured.Unstructured{Object: map[string]interface{}{
				"metadata": map[string]interface{}{
					"labels": convertLabels(tt.labels),
				},
			}}

			cluster.ExportRemoveAutoGeneratedJobLabels(obj, "metadata", "labels")

			if tt.expectRemoved {
				labels, found, _ := unstructured.NestedStringMap(obj.Object, "metadata", "labels")
				assert.True(t, !found || len(labels) == 0)
			} else if tt.expectLabels != nil {
				labels, _, _ := unstructured.NestedStringMap(obj.Object, "metadata", "labels")
				assert.Equal(t, tt.expectLabels, labels)
			}
		})
	}
}

func convertLabels(m map[string]string) map[string]interface{} {
	result := make(map[string]interface{}, len(m))
	for k, v := range m {
		result[k] = v
	}

	return result
}

func TestRemoveAutoGeneratedJobLabels_NoLabels(t *testing.T) {
	t.Parallel()

	obj := &unstructured.Unstructured{Object: map[string]interface{}{
		"metadata": map[string]interface{}{},
	}}

	// Should not panic
	cluster.ExportRemoveAutoGeneratedJobLabels(obj, "metadata", "labels")
}

func TestRemoveServiceClusterIPs(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		spec       map[string]interface{}
		expectSpec map[string]interface{}
	}{
		{
			name: "removes clusterIP and clusterIPs",
			spec: map[string]interface{}{
				"clusterIP":  "10.0.0.1",
				"clusterIPs": []interface{}{"10.0.0.1"},
				"type":       "ClusterIP",
			},
			expectSpec: map[string]interface{}{
				"type": "ClusterIP",
			},
		},
		{
			name: "preserves headless service",
			spec: map[string]interface{}{
				"clusterIP":  "None",
				"clusterIPs": []interface{}{"None"},
				"type":       "ClusterIP",
			},
			expectSpec: map[string]interface{}{
				"clusterIP":  "None",
				"clusterIPs": []interface{}{"None"},
				"type":       "ClusterIP",
			},
		},
		{
			name: "no clusterIP field",
			spec: map[string]interface{}{
				"type": "ClusterIP",
			},
			expectSpec: map[string]interface{}{
				"type": "ClusterIP",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			obj := &unstructured.Unstructured{Object: map[string]interface{}{
				"spec": tt.spec,
			}}

			cluster.ExportRemoveServiceClusterIPs(obj)

			spec, _, _ := unstructured.NestedMap(obj.Object, "spec")
			assert.Equal(t, tt.expectSpec, spec)
		})
	}
}

func TestCategoryIcon(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		category clusterupdate.ChangeCategory
		want     string
	}{
		{"recreate", clusterupdate.ChangeCategoryRecreateRequired, "🔴"},
		{"reboot", clusterupdate.ChangeCategoryRebootRequired, "🟡"},
		{"in-place", clusterupdate.ChangeCategoryInPlace, "🟢"},
		{"unknown", clusterupdate.ChangeCategory(99), "⚪"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			assert.Equal(t, tt.want, cluster.ExportCategoryIcon(tt.category))
		})
	}
}

func TestCommitTarball(t *testing.T) {
	t.Parallel()

	t.Run("successful commit", func(t *testing.T) {
		t.Parallel()

		tmpDir := t.TempDir()
		tmpPath := filepath.Join(tmpDir, "temp.tar.gz")
		targetPath := filepath.Join(tmpDir, "final.tar.gz")

		outFile, err := os.Create(tmpPath)
		require.NoError(t, err)

		gzipWriter := gzip.NewWriter(outFile)
		tarWriter := tar.NewWriter(gzipWriter)

		err = cluster.ExportCommitTarball(tarWriter, gzipWriter, outFile, tmpPath, targetPath)
		require.NoError(t, err)

		_, err = os.Stat(targetPath)
		assert.NoError(t, err)

		_, err = os.Stat(tmpPath)
		assert.True(t, os.IsNotExist(err))
	})

	t.Run("overwrites existing target", func(t *testing.T) {
		t.Parallel()

		tmpDir := t.TempDir()
		tmpPath := filepath.Join(tmpDir, "temp.tar.gz")
		targetPath := filepath.Join(tmpDir, "final.tar.gz")

		// Create existing target
		require.NoError(t, os.WriteFile(targetPath, []byte("old"), 0o600))

		outFile, err := os.Create(tmpPath)
		require.NoError(t, err)

		gzipWriter := gzip.NewWriter(outFile)
		tarWriter := tar.NewWriter(gzipWriter)

		err = cluster.ExportCommitTarball(tarWriter, gzipWriter, outFile, tmpPath, targetPath)
		require.NoError(t, err)

		_, err = os.Stat(targetPath)
		assert.NoError(t, err)
	})
}

func TestAllDistributions(t *testing.T) {
	t.Parallel()

	dists := cluster.ExportAllDistributions()
	assert.NotEmpty(t, dists)
	assert.GreaterOrEqual(t, len(dists), 4)
}

func TestAllProviders(t *testing.T) {
	t.Parallel()

	providers := cluster.ExportAllProviders()
	assert.NotEmpty(t, providers)
	assert.GreaterOrEqual(t, len(providers), 3)
}

func TestGetOutputFormat(t *testing.T) {
	t.Parallel()

	t.Run("default is text", func(t *testing.T) {
		t.Parallel()

		cmd := &cobra.Command{}
		cmd.Flags().String("output", "text", "")

		format := cluster.ExportGetOutputFormat(cmd)
		assert.Equal(t, "text", format)
	})

	t.Run("json format", func(t *testing.T) {
		t.Parallel()

		cmd := &cobra.Command{}
		cmd.Flags().String("output", "json", "")

		format := cluster.ExportGetOutputFormat(cmd)
		assert.Equal(t, "json", format)
	})

	t.Run("no flag returns text default", func(t *testing.T) {
		t.Parallel()

		cmd := &cobra.Command{}
		format := cluster.ExportGetOutputFormat(cmd)
		assert.Equal(t, cluster.ExportOutputFormatText, format)
	})
}

func TestDiffToJSON_EmptyDiff(t *testing.T) {
	t.Parallel()

	diff := &clusterupdate.UpdateResult{}
	out := cluster.ExportDiffToJSON(diff)

	assert.Equal(t, 0, out.TotalChanges)
	assert.Empty(t, out.InPlaceChanges)
	assert.Empty(t, out.RebootRequired)
	assert.Empty(t, out.RecreateRequired)
	assert.False(t, out.RequiresConfirmation)
}

func TestDiffToJSON_AllCategories(t *testing.T) {
	t.Parallel()

	diff := &clusterupdate.UpdateResult{
		InPlaceChanges: []clusterupdate.Change{
			{Field: "cni", OldValue: "cilium", NewValue: "calico", Category: clusterupdate.ChangeCategoryInPlace, Reason: "component swap"},
		},
		RebootRequired: []clusterupdate.Change{
			{Field: "nodeCount", OldValue: "1", NewValue: "3", Category: clusterupdate.ChangeCategoryRebootRequired, Reason: "scaling"},
		},
		RecreateRequired: []clusterupdate.Change{
			{Field: "distribution", OldValue: "Vanilla", NewValue: "K3s", Category: clusterupdate.ChangeCategoryRecreateRequired, Reason: "distribution change"},
		},
	}

	out := cluster.ExportDiffToJSON(diff)
	assert.Equal(t, 3, out.TotalChanges)
	assert.Len(t, out.InPlaceChanges, 1)
	assert.Len(t, out.RebootRequired, 1)
	assert.Len(t, out.RecreateRequired, 1)
	assert.True(t, out.RequiresConfirmation)
	assert.Equal(t, "cni", out.InPlaceChanges[0].Field)
	assert.Equal(t, "component swap", out.InPlaceChanges[0].Reason)
}

func TestDisplayChangesSummary_EmptyChanges(t *testing.T) {
	t.Parallel()

	diff := &clusterupdate.UpdateResult{}
	cmd := &cobra.Command{}

	var buf bytes.Buffer
	cmd.SetOut(&buf)

	cluster.ExportDisplayChangesSummary(cmd, diff)

	output := buf.String()
	assert.Empty(t, output, "empty changes should produce no output")
}
