// Package kyvernopolicy evaluates a GitOps source's own Kyverno policies
// against its rendered manifests offline, so `ksail workload validate` can
// report the admission denials a cluster running Kyverno would otherwise only
// raise at deploy time (issue #5355). It uses Kyverno's policy engine in
// process, with no cluster connection. Like celrules, it is decoupled from the
// render pipeline and CLI: callers hand it decoded documents.
//
// Scope: validate rules of kyverno.io/v1 ClusterPolicy and Policy. CEL-based
// policies.kyverno.io policies are not evaluated here.
package kyvernopolicy

import (
	"context"
	"errors"
	"fmt"

	"github.com/go-logr/logr"
	kyvernov1 "github.com/kyverno/kyverno/api/kyverno/v1"
	"github.com/kyverno/kyverno/pkg/config"
	"github.com/kyverno/kyverno/pkg/engine"
	engineapi "github.com/kyverno/kyverno/pkg/engine/api"
	"github.com/kyverno/kyverno/pkg/engine/factories"
	"github.com/kyverno/kyverno/pkg/engine/jmespath"
	"github.com/kyverno/kyverno/pkg/engine/policycontext"
	imageverifycache "github.com/kyverno/kyverno/pkg/image/verification/cache"
	engineutils "github.com/kyverno/kyverno/pkg/utils/engine"
	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	corev1listers "k8s.io/client-go/listers/core/v1"
	"k8s.io/client-go/tools/cache"
)

const (
	policyAPIVersion  = "kyverno.io/v1"
	kindClusterPolicy = "ClusterPolicy"
	kindPolicy        = "Policy"
)

var errDecodePolicy = errors.New("decode Kyverno policy")

// Violation reports one validate rule failing, or erroring, against one
// document.
type Violation struct {
	// Policy is the policy's name; namespaced policies are prefixed with
	// their namespace.
	Policy string
	// Rule is the failing rule's name as evaluated (Kyverno may rename
	// autogenerated pod-controller rules).
	Rule string
	// Message is the rule's message as reported by the engine.
	Message string
	// Error is true when the engine could not evaluate the rule, rather
	// than the document failing it.
	Error bool
	// Blocking is true when a cluster enforcing this policy would reject the
	// document: Kyverno resolves an Enforce action for the failing rule, or
	// the policy is enforcing and its failurePolicy is Fail for an error.
	Blocking bool
	// Unsupported is true when the policy could not be evaluated offline;
	// Message says why. It is never Blocking.
	Unsupported bool
}

// IsPolicy reports whether doc is a Kyverno policy this package evaluates.
func IsPolicy(doc map[string]any) bool {
	apiVersion, _ := doc["apiVersion"].(string)
	kind, _ := doc["kind"].(string)

	return apiVersion == policyAPIVersion && (kind == kindClusterPolicy || kind == kindPolicy)
}

// DecodePolicy converts a document for which IsPolicy is true into a typed
// policy. A document that is not a policy, or does not decode, is an error.
func DecodePolicy(doc map[string]any) (kyvernov1.PolicyInterface, error) {
	if !IsPolicy(doc) {
		return nil, fmt.Errorf("%w: not a kyverno.io/v1 ClusterPolicy or Policy", errDecodePolicy)
	}

	var policy kyvernov1.PolicyInterface

	if doc["kind"] == kindClusterPolicy {
		policy = &kyvernov1.ClusterPolicy{}
	} else {
		policy = &kyvernov1.Policy{}
	}

	err := runtime.DefaultUnstructuredConverter.FromUnstructuredWithValidation(doc, policy, true)
	if err != nil {
		name, _, _ := unstructured.NestedString(doc, "metadata", "name")

		return nil, fmt.Errorf("%w %q: %w", errDecodePolicy, name, err)
	}

	return policy, nil
}

// Engine evaluates a fixed set of policies against documents.
type Engine struct {
	policies   []kyvernov1.PolicyInterface
	namespaces corev1listers.NamespaceLister
	config     config.Configuration
	jp         jmespath.Interface
	engine     engineapi.Engine
}

// NewEngine returns an Engine for the given policies. As at admission, it
// keeps only policies with validate rules and admission processing enabled.
// namespaces are the source's rendered documents; the Namespace documents
// among them supply the labels that namespaceSelector matches and
// failure-action overrides are resolved against.
func NewEngine(policies []kyvernov1.PolicyInterface, namespaces []map[string]any) *Engine {
	cfg := config.NewDefaultConfiguration(false)
	jmesPath := jmespath.New(cfg)
	isCluster := false

	validating := make([]kyvernov1.PolicyInterface, 0, len(policies))

	for _, policy := range policies {
		if policy.GetSpec().HasValidate() && policy.AdmissionProcessingEnabled() {
			validating = append(validating, policy)
		}
	}

	return &Engine{
		policies:   validating,
		namespaces: namespaceLister(namespaces),
		config:     cfg,
		jp:         jmesPath,
		engine: engine.NewEngine(
			cfg,
			jmesPath,
			nil,
			nil,
			imageverifycache.DisabledImageVerifyCache(),
			factories.DefaultContextLoaderFactory(nil),
			nil,
			&isCluster,
		),
	}
}

// namespaceLister indexes the Namespace documents among docs.
func namespaceLister(docs []map[string]any) corev1listers.NamespaceLister {
	indexer := cache.NewIndexer(cache.MetaNamespaceKeyFunc, cache.Indexers{})

	for _, doc := range docs {
		if doc["apiVersion"] != "v1" || doc["kind"] != "Namespace" {
			continue
		}

		name, _, _ := unstructured.NestedString(doc, "metadata", "name")
		labels, _, _ := unstructured.NestedStringMap(doc, "metadata", "labels")

		_ = indexer.Add(&corev1.Namespace{
			ObjectMeta: metav1.ObjectMeta{Name: name, Labels: labels},
		})
	}

	return corev1listers.NewNamespaceLister(indexer)
}

// Evaluate applies every validating policy to doc, simulating its creation,
// and returns the failing and erroring rules. As in a cluster, the engine
// applies a namespaced Policy only to documents in its own namespace. A rule
// that selects on namespace labels, for a document whose Namespace is not
// among the rendered documents, is reported as Unsupported instead of being
// evaluated against labels it cannot see; the policy's other rules are still
// evaluated.
//
// doc's namespace is used as given. For a namespaced kind the namespace a
// cluster admits it into is chosen by whatever applies it (a Flux
// targetNamespace, a kubectl context), not by the document, and the engine has
// no API discovery to tell namespaced kinds from cluster-scoped ones, so the
// caller sets the namespace the applier would use before evaluating.
func (e *Engine) Evaluate(ctx context.Context, doc map[string]any) ([]Violation, error) {
	resource := unstructured.Unstructured{Object: doc}

	var violations []Violation

	for _, policy := range e.policies {
		namespaceLabels, err := e.namespaceLabels(resource, policy)
		if apierrors.IsNotFound(err) {
			evaluable, unsupported, splitErr := e.splitOnUnknownNamespace(resource, policy)
			if splitErr != nil {
				return nil, splitErr
			}

			violations = append(violations, unsupported...)

			if evaluable == nil {
				continue
			}

			// The remaining rules select on no namespace labels, so none are needed.
			policy, namespaceLabels, err = evaluable, nil, nil
		}

		if err != nil {
			return nil, fmt.Errorf("resolve namespace labels for %s: %w", policyName(policy), err)
		}

		policyContext, err := policycontext.NewPolicyContext(
			e.jp, resource, kyvernov1.Create, nil, e.config,
		)
		if err != nil {
			return nil, fmt.Errorf("build policy context for %s: %w", policyName(policy), err)
		}

		response := e.engine.Validate(
			ctx,
			policyContext.WithNamespaceLabels(namespaceLabels).WithPolicy(policy),
		)
		violations = append(violations, collect(ctx, policy, response)...)
	}

	return violations, nil
}

// namespaceLabels resolves the labels of resource's Namespace when policy selects
// on them. It returns a NotFound error when policy needs labels of a Namespace
// that is not among the rendered documents.
func (e *Engine) namespaceLabels(
	resource unstructured.Unstructured,
	policy kyvernov1.PolicyInterface,
) (map[string]string, error) {
	labels, err := engineutils.GetNamespaceSelectorsFromNamespaceLister(
		resource.GetKind(),
		resource.GetNamespace(),
		e.namespaces,
		[]kyvernov1.PolicyInterface{policy},
		logr.Discard(),
	)
	if err != nil {
		return nil, fmt.Errorf("get namespace selectors: %w", err)
	}

	return labels, nil
}

// splitOnUnknownNamespace handles a policy whose namespace labels are unknown one
// rule at a time, so a rule that selects on those labels does not hide the
// results of the rules that do not. It returns a copy of policy holding only the
// rules that need no namespace labels (nil when there are none), and an
// Unsupported violation for each rule that does.
func (e *Engine) splitOnUnknownNamespace(
	resource unstructured.Unstructured,
	policy kyvernov1.PolicyInterface,
) (kyvernov1.PolicyInterface, []Violation, error) {
	rules := policy.GetSpec().Rules

	var (
		evaluable   []kyvernov1.Rule
		unsupported []Violation
	)

	for i := range rules {
		single := policy.CreateDeepCopy()
		single.GetSpec().Rules = []kyvernov1.Rule{rules[i]}

		_, err := e.namespaceLabels(resource, single)

		switch {
		case apierrors.IsNotFound(err):
			unsupported = append(unsupported, Violation{
				Policy: policyName(policy),
				Rule:   rules[i].Name,
				Message: fmt.Sprintf(
					"namespace %q is not among the rendered documents, so its labels are unknown "+
						"and this rule's namespaceSelector cannot be evaluated offline",
					resource.GetNamespace(),
				),
				Unsupported: true,
			})
		case err != nil:
			return nil, nil, fmt.Errorf(
				"resolve namespace labels for %s rule %s: %w", policyName(policy), rules[i].Name, err,
			)
		default:
			evaluable = append(evaluable, rules[i])
		}
	}

	if len(evaluable) == 0 {
		return nil, unsupported, nil
	}

	remaining := policy.CreateDeepCopy()
	remaining.GetSpec().Rules = evaluable

	return remaining, unsupported, nil
}

// collect converts a response into violations. A failure blocks when Kyverno
// resolves an Enforce action for its rule. An error blocks, as in Kyverno's
// admission handler, only for a policy on the enforcing path whose
// failurePolicy is Fail; the handler aggregates failurePolicy across the
// request's enforcing policies, and this evaluates it per policy.
func collect(
	ctx context.Context,
	policy kyvernov1.PolicyInterface,
	response engineapi.EngineResponse,
) []Violation {
	errorBlocking := enforcing(policy.GetSpec()) &&
		policy.GetSpec().GetFailurePolicy(ctx) == kyvernov1.Fail

	var violations []Violation

	for i := range response.PolicyResponse.Rules {
		rule := &response.PolicyResponse.Rules[i]

		switch rule.Status() {
		case engineapi.RuleStatusFail:
			violations = append(violations, Violation{
				Policy:   policyName(policy),
				Rule:     rule.Name(),
				Message:  rule.Message(),
				Blocking: enforcedFailure(response, *rule),
			})
		case engineapi.RuleStatusError:
			violations = append(violations, Violation{
				Policy:   policyName(policy),
				Rule:     rule.Name(),
				Message:  rule.Message(),
				Error:    true,
				Blocking: errorBlocking,
			})
		case engineapi.RuleStatusPass, engineapi.RuleStatusWarn, engineapi.RuleStatusSkip:
		}
	}

	return violations
}

// enforcedFailure reports whether Kyverno resolves an Enforce action for this
// one failing rule. HasEnforcedFailure answers for the whole response, so it is
// asked about a copy holding only this rule; otherwise an Audit failure beside
// an enforced failure would be reported as blocking.
func enforcedFailure(response engineapi.EngineResponse, rule engineapi.RuleResponse) bool {
	response.PolicyResponse.Rules = []engineapi.RuleResponse{rule}

	return response.HasEnforcedFailure()
}

// enforcing reports whether Kyverno's policy cache places the policy on the
// enforcing validation path: any Enforce action, at the policy or rule level,
// including in failure-action overrides.
func enforcing(spec *kyvernov1.Spec) bool {
	if spec.ValidationFailureAction.Enforce() {
		return true
	}

	for _, override := range spec.ValidationFailureActionOverrides {
		if override.Action.Enforce() {
			return true
		}
	}

	for _, rule := range spec.GetRules() {
		if !rule.HasValidate() {
			continue
		}

		if action := rule.Validation.FailureAction; action != nil && action.Enforce() {
			return true
		}

		for _, override := range rule.Validation.FailureActionOverrides {
			if override.Action.Enforce() {
				return true
			}
		}
	}

	return false
}

func policyName(policy kyvernov1.PolicyInterface) string {
	if policy.IsNamespaced() {
		return policy.GetNamespace() + "/" + policy.GetName()
	}

	return policy.GetName()
}
