// Package kyvernopolicy evaluates a GitOps source's own Kyverno policies
// against its rendered manifests offline, so `ksail workload validate` can
// report the admission denials a cluster running Kyverno would otherwise only
// raise at deploy time (issue #5355). It uses Kyverno's policy engine in
// process, with no cluster connection. Like celrules, it is decoupled from the
// render pipeline and CLI: callers hand it decoded documents.
//
// Scope: validate rules of kyverno.io/v1 ClusterPolicy and Policy. CEL-based
// policies.kyverno.io policies are not evaluated here.
package kyvernopolicy

import (
	"context"
	"errors"
	"fmt"

	kyvernov1 "github.com/kyverno/kyverno/api/kyverno/v1"
	"github.com/kyverno/kyverno/pkg/config"
	"github.com/kyverno/kyverno/pkg/engine"
	engineapi "github.com/kyverno/kyverno/pkg/engine/api"
	"github.com/kyverno/kyverno/pkg/engine/factories"
	"github.com/kyverno/kyverno/pkg/engine/jmespath"
	"github.com/kyverno/kyverno/pkg/engine/policycontext"
	imageverifycache "github.com/kyverno/kyverno/pkg/image/verification/cache"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
)

const (
	policyAPIVersion  = "kyverno.io/v1"
	kindClusterPolicy = "ClusterPolicy"
	kindPolicy        = "Policy"
)

var errDecodePolicy = errors.New("decode Kyverno policy")

// Violation reports one validate rule failing, or erroring, against one
// document.
type Violation struct {
	// Policy is the policy's name; namespaced policies are prefixed with
	// their namespace.
	Policy string
	// Rule is the failing rule's name as evaluated (Kyverno may rename
	// autogenerated pod-controller rules).
	Rule string
	// Message is the rule's message as reported by the engine.
	Message string
	// Error is true when the engine could not evaluate the rule, rather
	// than the document failing it.
	Error bool
	// Blocking is true when a cluster enforcing this policy would reject the
	// document: the policy has an Enforce failure for it.
	Blocking bool
}

// IsPolicy reports whether doc is a Kyverno policy this package evaluates.
func IsPolicy(doc map[string]any) bool {
	apiVersion, _ := doc["apiVersion"].(string)
	kind, _ := doc["kind"].(string)

	return apiVersion == policyAPIVersion && (kind == kindClusterPolicy || kind == kindPolicy)
}

// DecodePolicy converts a document for which IsPolicy is true into a typed
// policy. A document that is not a policy, or does not decode, is an error.
func DecodePolicy(doc map[string]any) (kyvernov1.PolicyInterface, error) {
	if !IsPolicy(doc) {
		return nil, fmt.Errorf("%w: not a kyverno.io/v1 ClusterPolicy or Policy", errDecodePolicy)
	}

	var policy kyvernov1.PolicyInterface

	if doc["kind"] == kindClusterPolicy {
		policy = &kyvernov1.ClusterPolicy{}
	} else {
		policy = &kyvernov1.Policy{}
	}

	err := runtime.DefaultUnstructuredConverter.FromUnstructuredWithValidation(doc, policy, true)
	if err != nil {
		name, _, _ := unstructured.NestedString(doc, "metadata", "name")

		return nil, fmt.Errorf("%w %q: %w", errDecodePolicy, name, err)
	}

	return policy, nil
}

// Engine evaluates a fixed set of policies against documents.
type Engine struct {
	policies []kyvernov1.PolicyInterface
	config   config.Configuration
	jp       jmespath.Interface
	engine   engineapi.Engine
}

// NewEngine returns an Engine for the given policies. Policies without
// validate rules are ignored.
func NewEngine(policies []kyvernov1.PolicyInterface) *Engine {
	cfg := config.NewDefaultConfiguration(false)
	jmesPath := jmespath.New(cfg)
	isCluster := false

	validating := make([]kyvernov1.PolicyInterface, 0, len(policies))

	for _, policy := range policies {
		if policy.GetSpec().HasValidate() {
			validating = append(validating, policy)
		}
	}

	return &Engine{
		policies: validating,
		config:   cfg,
		jp:       jmesPath,
		engine: engine.NewEngine(
			cfg,
			jmesPath,
			nil,
			nil,
			imageverifycache.DisabledImageVerifyCache(),
			factories.DefaultContextLoaderFactory(nil),
			nil,
			&isCluster,
		),
	}
}

// Evaluate applies every validating policy to doc, simulating its creation,
// and returns the failing and erroring rules. As in a cluster, the engine
// applies a namespaced Policy only to documents in its own namespace.
func (e *Engine) Evaluate(ctx context.Context, doc map[string]any) ([]Violation, error) {
	resource := unstructured.Unstructured{Object: doc}

	var violations []Violation

	for _, policy := range e.policies {
		policyContext, err := policycontext.NewPolicyContext(
			e.jp, resource, kyvernov1.Create, nil, e.config,
		)
		if err != nil {
			return nil, fmt.Errorf("build policy context for %s: %w", policyName(policy), err)
		}

		response := e.engine.Validate(ctx, policyContext.WithPolicy(policy))
		violations = append(violations, collect(policy, response)...)
	}

	return violations, nil
}

func collect(policy kyvernov1.PolicyInterface, response engineapi.EngineResponse) []Violation {
	blocking := response.HasEnforcedFailure()
	enforceable := policy.GetSpec().HasValidateEnforce()

	var violations []Violation

	for i := range response.PolicyResponse.Rules {
		rule := &response.PolicyResponse.Rules[i]

		switch rule.Status() {
		case engineapi.RuleStatusFail:
			violations = append(violations, Violation{
				Policy:   policyName(policy),
				Rule:     rule.Name(),
				Message:  rule.Message(),
				Blocking: blocking,
			})
		case engineapi.RuleStatusError:
			violations = append(violations, Violation{
				Policy:   policyName(policy),
				Rule:     rule.Name(),
				Message:  rule.Message(),
				Error:    true,
				Blocking: enforceable,
			})
		case engineapi.RuleStatusPass, engineapi.RuleStatusWarn, engineapi.RuleStatusSkip:
		}
	}

	return violations
}

func policyName(policy kyvernov1.PolicyInterface) string {
	if policy.IsNamespaced() {
		return policy.GetNamespace() + "/" + policy.GetName()
	}

	return policy.GetName()
}
