---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: <name>
  namespace: <namespace>
spec:
  interval: 10m
  chart:
    spec:
      chart: <chart>
      sourceRef:
        kind: HelmRepository
        name: <name>
