---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: <name>
  namespace: <namespace>
spec:
  egress:
  - to: []
  ingress:
  - from: []
  podSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
  - Egress
