package containerdbootstrap_test

import (
	"strings"
	"testing"

	"github.com/BurntSushi/toml"
	containerdbootstrap "github.com/devantler-tech/ksail/v7/pkg/svc/bootstrap/containerd"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// criPluginKey is the TOML table key containerd's CRI plugin decodes to (the
// quotes in the rendered header are TOML string quoting, not part of the key).
const criPluginKey = "io.containerd.grpc.v1.cri"

// parsedConfig mirrors the subset of containerd's v2 config this package renders,
// so tests decode the output and assert on parsed values rather than on brittle
// substrings — and, by decoding at all, prove the rendered document is valid TOML.
type parsedConfig struct {
	Version int                     `toml:"version"`
	Plugins map[string]parsedCRIPlg `toml:"plugins"`
}

// parsedCRIPlg mirrors the CRI plugin block Render emits.
type parsedCRIPlg struct {
	SandboxImage string `toml:"sandbox_image"`
	Containerd   struct {
		Runtimes struct {
			Runc struct {
				RuntimeType string `toml:"runtime_type"`
				Options     struct {
					SystemdCgroup bool `toml:"SystemdCgroup"`
				} `toml:"options"`
			} `toml:"runc"`
		} `toml:"runtimes"`
	} `toml:"containerd"`
}

// decode asserts the stream carries the managed-file header, parses as TOML, and
// returns the CRI plugin block, so tests assert on parsed values.
func decode(t *testing.T, stream string) parsedCRIPlg {
	t.Helper()

	require.True(t,
		strings.HasPrefix(stream, "# Generated by ksail — containerd"),
		"stream must begin with the managed-file header",
	)

	var cfg parsedConfig

	_, err := toml.Decode(stream, &cfg)
	require.NoError(t, err, "rendered config must be valid TOML")

	assert.Equal(t, 2, cfg.Version, "containerd config schema version must be 2")

	plugin, found := cfg.Plugins[criPluginKey]
	require.True(t, found, "the CRI plugin table must be present")

	return plugin
}

// TestRenderContainerdConfigEnablesSystemdCgroup is the core guarantee: the
// runtime is configured for the systemd cgroup driver so it agrees with the way
// kubeadm configures the kubelet.
func TestRenderContainerdConfigEnablesSystemdCgroup(t *testing.T) {
	t.Parallel()

	stream, err := containerdbootstrap.RenderContainerdConfig(
		containerdbootstrap.ContainerdConfig{},
	)
	require.NoError(t, err)

	plugin := decode(t, stream)

	assert.True(t,
		plugin.Containerd.Runtimes.Runc.Options.SystemdCgroup,
		"SystemdCgroup must be true so the runtime matches kubeadm's kubelet cgroup driver",
	)
	assert.Equal(t,
		"io.containerd.runc.v2",
		plugin.Containerd.Runtimes.Runc.RuntimeType,
		"the runc runtime handler must be pinned",
	)
}

// TestRenderContainerdConfigPinsSandboxImage verifies a supplied sandbox image is
// rendered, and an empty one is omitted so containerd keeps its default.
func TestRenderContainerdConfigPinsSandboxImage(t *testing.T) {
	t.Parallel()

	const image = "registry.k8s.io/pause:3.10"

	withImage, err := containerdbootstrap.RenderContainerdConfig(
		containerdbootstrap.ContainerdConfig{SandboxImage: image},
	)
	require.NoError(t, err)
	assert.Equal(
		t,
		image,
		decode(t, withImage).SandboxImage,
		"sandbox image must be pinned when supplied",
	)

	without, err := containerdbootstrap.RenderContainerdConfig(
		containerdbootstrap.ContainerdConfig{},
	)
	require.NoError(t, err)
	assert.Empty(
		t,
		decode(t, without).SandboxImage,
		"sandbox image must be absent when not supplied",
	)
	assert.NotContains(t, without, "sandbox_image",
		"the sandbox_image key must be omitted entirely, not rendered empty")
}

// TestRenderContainerdConfigIsDeterministic guards the byte-for-byte determinism
// callers (and a generated-artifact drift check) rely on.
func TestRenderContainerdConfigIsDeterministic(t *testing.T) {
	t.Parallel()

	cfg := containerdbootstrap.ContainerdConfig{SandboxImage: "registry.k8s.io/pause:3.10"}

	first, err := containerdbootstrap.RenderContainerdConfig(cfg)
	require.NoError(t, err)

	second, err := containerdbootstrap.RenderContainerdConfig(cfg)
	require.NoError(t, err)

	assert.Equal(t, first, second, "the same input must render byte-identical output")
}

// TestRenderContainerdConfigRejectsMalformedSandboxImage verifies a set-but-
// malformed sandbox image is caught at render time and no config is returned.
func TestRenderContainerdConfigRejectsMalformedSandboxImage(t *testing.T) {
	t.Parallel()

	cases := map[string]string{
		"space":          "registry.k8s.io/pause 3.10",
		"embedded-quote": `registry.k8s.io/"pause":3.10`,
		"newline":        "registry.k8s.io/pause:3.10\n",
		"tab":            "registry.k8s.io/pause:\t3.10",
		"control-char":   "registry.k8s.io/pause:3.10\x00",
	}

	for name, image := range cases {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			stream, err := containerdbootstrap.RenderContainerdConfig(
				containerdbootstrap.ContainerdConfig{SandboxImage: image},
			)

			require.ErrorIs(t, err, containerdbootstrap.ErrInvalidSandboxImage)
			assert.Empty(t, stream, "no config must be returned on a validation error")
		})
	}
}
