package containerdbootstrap

import (
	"strings"
	"unicode"
)

// header is prepended to the rendered config so an operator inspecting a node
// can see the file is ksail-managed rather than hand-written. It mirrors the
// managed-file header the sibling kubeadmbootstrap renderer emits.
const header = "# Generated by ksail — containerd runtime configuration. Do not edit.\n"

// criPlugin is the fully-qualified TOML table key of containerd's CRI plugin in
// the version-2 config schema. Every CRI setting this package renders lives under
// it, so both the sandbox_image key and the runc runtime sub-tables are addressed
// relative to it.
const criPlugin = `plugins."io.containerd.grpc.v1.cri"`

// runcRuntimeType is the CRI runtime handler for runc under containerd's v2
// runtime API. kubeadm nodes run the runc handler, so it is pinned explicitly
// rather than relying on containerd's built-in default staying constant.
const runcRuntimeType = "io.containerd.runc.v2"

// ContainerdConfig is the typed input for [RenderContainerdConfig]. It performs
// no I/O. The zero value renders a valid config that enables the systemd cgroup
// driver and leaves containerd's default sandbox image in place.
type ContainerdConfig struct {
	// SandboxImage optionally pins containerd's CRI "pause" sandbox image (e.g.
	// "registry.k8s.io/pause:3.10") to the one the node's kubeadm/kubelet expects,
	// avoiding an extra pull and a version-mismatch warning per pod sandbox. When
	// empty the sandbox_image key is omitted and containerd uses its built-in
	// default. When set it must be a single-line image reference free of spaces,
	// control characters, and double quotes (see [ErrInvalidSandboxImage]).
	SandboxImage string
}

// RenderContainerdConfig renders the /etc/containerd/config.toml for a kubeadm
// (Vanilla) node. The returned document is a complete containerd version-2
// config, prefixed with a managed-file header, that enables the systemd cgroup
// driver (SystemdCgroup = true on the CRI runc runtime) so the runtime agrees
// with the way kubeadm configures the kubelet — without which the node never
// reaches Ready. SandboxImage is pinned when supplied.
//
// The cgroup driver is fixed to systemd rather than made configurable: kubeadm
// defaults the kubelet to the systemd driver, so a ksail-provisioned kubeadm
// node must match it, and exposing a knob that could only ever be set to systemd
// would invite a misconfiguration.
//
// RenderContainerdConfig is pure and deterministic: no I/O, no network, and the
// same input always yields byte-identical output. The result is suitable for
// delivery via cloud-init write_files. It returns [ErrInvalidSandboxImage] when
// SandboxImage is set but malformed, and never returns a partially-valid config.
func RenderContainerdConfig(cfg ContainerdConfig) (string, error) {
	err := validateSandboxImage(cfg.SandboxImage)
	if err != nil {
		return "", err
	}

	var builder strings.Builder

	builder.WriteString(header)
	builder.WriteString("version = 2\n")

	if cfg.SandboxImage != "" {
		builder.WriteString("\n[")
		builder.WriteString(criPlugin)
		builder.WriteString("]\n")
		builder.WriteString(`sandbox_image = "`)
		builder.WriteString(cfg.SandboxImage)
		builder.WriteString("\"\n")
	}

	builder.WriteString("\n[")
	builder.WriteString(criPlugin)
	builder.WriteString(".containerd.runtimes.runc]\n")
	builder.WriteString(`runtime_type = "`)
	builder.WriteString(runcRuntimeType)
	builder.WriteString("\"\n")

	builder.WriteString("\n[")
	builder.WriteString(criPlugin)
	builder.WriteString(".containerd.runtimes.runc.options]\n")
	builder.WriteString("SystemdCgroup = true\n")

	return builder.String(), nil
}

// validateSandboxImage accepts an empty image (the sandbox_image key is omitted)
// and otherwise rejects any reference that carries a space, a control character
// (including a newline), or a double quote — none of which a valid image
// reference contains, and any of which would break the quoted TOML string the
// value is embedded in.
func validateSandboxImage(image string) error {
	if image == "" {
		return nil
	}

	for _, char := range image {
		if char == '"' || unicode.IsSpace(char) || unicode.IsControl(char) {
			return ErrInvalidSandboxImage
		}
	}

	return nil
}
