---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- patch: |-
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: all
    spec:
      postBuild:
        substituteFrom:
        - kind: ConfigMap
          name: variables-cluster
        - kind: Secret
          name: variables-sensitive-cluster
  target:
    kind: Kustomization
    labelSelector: kustomize.toolkit.fluxcd.io/post-build-variables=enabled
