//go:build !ignore_autogenerated

// Copyright (c) KSail contributors. All rights reserved.
// Licensed under the PolyForm Shield License 1.0.0. See LICENSE in the project root.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalerConfig) DeepCopyInto(out *AutoscalerConfig) {
	*out = *in
	out.Pod = in.Pod
	in.Node.DeepCopyInto(&out.Node)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalerConfig.
func (in *AutoscalerConfig) DeepCopy() *AutoscalerConfig {
	if in == nil {
		return nil
	}
	out := new(AutoscalerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in AutoscalerExpanderList) DeepCopyInto(out *AutoscalerExpanderList) {
	{
		in := &in
		*out = make(AutoscalerExpanderList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalerExpanderList.
func (in AutoscalerExpanderList) DeepCopy() AutoscalerExpanderList {
	if in == nil {
		return nil
	}
	out := new(AutoscalerExpanderList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChatSpec) DeepCopyInto(out *ChatSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChatSpec.
func (in *ChatSpec) DeepCopy() *ChatSpec {
	if in == nil {
		return nil
	}
	out := new(ChatSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterList) DeepCopyInto(out *ClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterList.
func (in *ClusterList) DeepCopy() *ClusterList {
	if in == nil {
		return nil
	}
	out := new(ClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpec) DeepCopyInto(out *ClusterSpec) {
	*out = *in
	out.Connection = in.Connection
	out.LocalRegistry = in.LocalRegistry
	in.SOPS.DeepCopyInto(&out.SOPS)
	in.Autoscaler.DeepCopyInto(&out.Autoscaler)
	in.OIDC.DeepCopyInto(&out.OIDC)
	out.Vanilla = in.Vanilla
	in.Talos.DeepCopyInto(&out.Talos)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpec.
func (in *ClusterSpec) DeepCopy() *ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KubeconfigSecretRef != nil {
		in, out := &in.KubeconfigSecretRef, &out.KubeconfigSecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.GitOps != nil {
		in, out := &in.GitOps, &out.GitOps
		*out = new(GitOpsStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]ComponentStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentStatus.
func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Connection) DeepCopyInto(out *Connection) {
	*out = *in
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Connection.
func (in *Connection) DeepCopy() *Connection {
	if in == nil {
		return nil
	}
	out := new(Connection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxConfig) DeepCopyInto(out *FluxConfig) {
	*out = *in
	in.Verify.DeepCopyInto(&out.Verify)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxConfig.
func (in *FluxConfig) DeepCopy() *FluxConfig {
	if in == nil {
		return nil
	}
	out := new(FluxConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxKustomization) DeepCopyInto(out *FluxKustomization) {
	*out = *in
	out.Metadata = in.Metadata
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxKustomization.
func (in *FluxKustomization) DeepCopy() *FluxKustomization {
	if in == nil {
		return nil
	}
	out := new(FluxKustomization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxKustomizationSourceRef) DeepCopyInto(out *FluxKustomizationSourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxKustomizationSourceRef.
func (in *FluxKustomizationSourceRef) DeepCopy() *FluxKustomizationSourceRef {
	if in == nil {
		return nil
	}
	out := new(FluxKustomizationSourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxKustomizationSpec) DeepCopyInto(out *FluxKustomizationSpec) {
	*out = *in
	out.Interval = in.Interval
	out.SourceRef = in.SourceRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxKustomizationSpec.
func (in *FluxKustomizationSpec) DeepCopy() *FluxKustomizationSpec {
	if in == nil {
		return nil
	}
	out := new(FluxKustomizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxKustomizationStatus) DeepCopyInto(out *FluxKustomizationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxKustomizationStatus.
func (in *FluxKustomizationStatus) DeepCopy() *FluxKustomizationStatus {
	if in == nil {
		return nil
	}
	out := new(FluxKustomizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxOCIRepository) DeepCopyInto(out *FluxOCIRepository) {
	*out = *in
	out.Metadata = in.Metadata
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxOCIRepository.
func (in *FluxOCIRepository) DeepCopy() *FluxOCIRepository {
	if in == nil {
		return nil
	}
	out := new(FluxOCIRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxOCIRepositoryRef) DeepCopyInto(out *FluxOCIRepositoryRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxOCIRepositoryRef.
func (in *FluxOCIRepositoryRef) DeepCopy() *FluxOCIRepositoryRef {
	if in == nil {
		return nil
	}
	out := new(FluxOCIRepositoryRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxOCIRepositorySpec) DeepCopyInto(out *FluxOCIRepositorySpec) {
	*out = *in
	out.Interval = in.Interval
	out.Ref = in.Ref
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxOCIRepositorySpec.
func (in *FluxOCIRepositorySpec) DeepCopy() *FluxOCIRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(FluxOCIRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxOCIRepositoryStatus) DeepCopyInto(out *FluxOCIRepositoryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxOCIRepositoryStatus.
func (in *FluxOCIRepositoryStatus) DeepCopy() *FluxOCIRepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(FluxOCIRepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxObjectMeta) DeepCopyInto(out *FluxObjectMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxObjectMeta.
func (in *FluxObjectMeta) DeepCopy() *FluxObjectMeta {
	if in == nil {
		return nil
	}
	out := new(FluxObjectMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxVerifyOIDCIdentity) DeepCopyInto(out *FluxVerifyOIDCIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxVerifyOIDCIdentity.
func (in *FluxVerifyOIDCIdentity) DeepCopy() *FluxVerifyOIDCIdentity {
	if in == nil {
		return nil
	}
	out := new(FluxVerifyOIDCIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxVerifySecretRef) DeepCopyInto(out *FluxVerifySecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxVerifySecretRef.
func (in *FluxVerifySecretRef) DeepCopy() *FluxVerifySecretRef {
	if in == nil {
		return nil
	}
	out := new(FluxVerifySecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxVerifySpec) DeepCopyInto(out *FluxVerifySpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.MatchOIDCIdentity != nil {
		in, out := &in.MatchOIDCIdentity, &out.MatchOIDCIdentity
		*out = make([]FluxVerifyOIDCIdentity, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxVerifySpec.
func (in *FluxVerifySpec) DeepCopy() *FluxVerifySpec {
	if in == nil {
		return nil
	}
	out := new(FluxVerifySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsStatus) DeepCopyInto(out *GitOpsStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsStatus.
func (in *GitOpsStatus) DeepCopy() *GitOpsStatus {
	if in == nil {
		return nil
	}
	out := new(GitOpsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesPersistence) DeepCopyInto(out *KubernetesPersistence) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesPersistence.
func (in *KubernetesPersistence) DeepCopy() *KubernetesPersistence {
	if in == nil {
		return nil
	}
	out := new(KubernetesPersistence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalRegistry) DeepCopyInto(out *LocalRegistry) {
	*out = *in
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalRegistry.
func (in *LocalRegistry) DeepCopy() *LocalRegistry {
	if in == nil {
		return nil
	}
	out := new(LocalRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAutoscalerConfig) DeepCopyInto(out *NodeAutoscalerConfig) {
	*out = *in
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]NodePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Expander != nil {
		in, out := &in.Expander, &out.Expander
		*out = make(AutoscalerExpanderList, len(*in))
		copy(*out, *in)
	}
	if in.SkipNodesWithLocalStorage != nil {
		in, out := &in.SkipNodesWithLocalStorage, &out.SkipNodesWithLocalStorage
		*out = new(bool)
		**out = **in
	}
	if in.SkipNodesWithSystemPods != nil {
		in, out := &in.SkipNodesWithSystemPods, &out.SkipNodesWithSystemPods
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAutoscalerConfig.
func (in *NodeAutoscalerConfig) DeepCopy() *NodeAutoscalerConfig {
	if in == nil {
		return nil
	}
	out := new(NodeAutoscalerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePool) DeepCopyInto(out *NodePool) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]NodePoolTaint, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePool.
func (in *NodePool) DeepCopy() *NodePool {
	if in == nil {
		return nil
	}
	out := new(NodePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolTaint) DeepCopyInto(out *NodePoolTaint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolTaint.
func (in *NodePoolTaint) DeepCopy() *NodePoolTaint {
	if in == nil {
		return nil
	}
	out := new(NodePoolTaint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIArtifact) DeepCopyInto(out *OCIArtifact) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIArtifact.
func (in *OCIArtifact) DeepCopy() *OCIArtifact {
	if in == nil {
		return nil
	}
	out := new(OCIArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIRegistry) DeepCopyInto(out *OCIRegistry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIRegistry.
func (in *OCIRegistry) DeepCopy() *OCIRegistry {
	if in == nil {
		return nil
	}
	out := new(OCIRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCSpec) DeepCopyInto(out *OIDCSpec) {
	*out = *in
	if in.ExtraScopes != nil {
		in, out := &in.ExtraScopes, &out.ExtraScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCSpec.
func (in *OIDCSpec) DeepCopy() *OIDCSpec {
	if in == nil {
		return nil
	}
	out := new(OIDCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptionsAWS) DeepCopyInto(out *OptionsAWS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptionsAWS.
func (in *OptionsAWS) DeepCopy() *OptionsAWS {
	if in == nil {
		return nil
	}
	out := new(OptionsAWS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptionsAzure) DeepCopyInto(out *OptionsAzure) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptionsAzure.
func (in *OptionsAzure) DeepCopy() *OptionsAzure {
	if in == nil {
		return nil
	}
	out := new(OptionsAzure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptionsGCP) DeepCopyInto(out *OptionsGCP) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptionsGCP.
func (in *OptionsGCP) DeepCopy() *OptionsGCP {
	if in == nil {
		return nil
	}
	out := new(OptionsGCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptionsHetzner) DeepCopyInto(out *OptionsHetzner) {
	*out = *in
	if in.FallbackLocations != nil {
		in, out := &in.FallbackLocations, &out.FallbackLocations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedCIDRs != nil {
		in, out := &in.AllowedCIDRs, &out.AllowedCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WorkerPublicIPv4 != nil {
		in, out := &in.WorkerPublicIPv4, &out.WorkerPublicIPv4
		*out = new(bool)
		**out = **in
	}
	if in.WorkerPublicIPv6 != nil {
		in, out := &in.WorkerPublicIPv6, &out.WorkerPublicIPv6
		*out = new(bool)
		**out = **in
	}
	if in.ControlPlanePublicIPv4 != nil {
		in, out := &in.ControlPlanePublicIPv4, &out.ControlPlanePublicIPv4
		*out = new(bool)
		**out = **in
	}
	if in.ControlPlanePublicIPv6 != nil {
		in, out := &in.ControlPlanePublicIPv6, &out.ControlPlanePublicIPv6
		*out = new(bool)
		**out = **in
	}
	if in.AutoscalerNodePoolNames != nil {
		in, out := &in.AutoscalerNodePoolNames, &out.AutoscalerNodePoolNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AutoscalerNodePools != nil {
		in, out := &in.AutoscalerNodePools, &out.AutoscalerNodePools
		*out = make([]NodePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptionsHetzner.
func (in *OptionsHetzner) DeepCopy() *OptionsHetzner {
	if in == nil {
		return nil
	}
	out := new(OptionsHetzner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptionsKubernetes) DeepCopyInto(out *OptionsKubernetes) {
	*out = *in
	out.Persistence = in.Persistence
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptionsKubernetes.
func (in *OptionsKubernetes) DeepCopy() *OptionsKubernetes {
	if in == nil {
		return nil
	}
	out := new(OptionsKubernetes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptionsOmni) DeepCopyInto(out *OptionsOmni) {
	*out = *in
	if in.Machines != nil {
		in, out := &in.Machines, &out.Machines
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptionsOmni.
func (in *OptionsOmni) DeepCopy() *OptionsOmni {
	if in == nil {
		return nil
	}
	out := new(OptionsOmni)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptionsTalos) DeepCopyInto(out *OptionsTalos) {
	*out = *in
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraPortMappings != nil {
		in, out := &in.ExtraPortMappings, &out.ExtraPortMappings
		*out = make([]PortMapping, len(*in))
		copy(*out, *in)
	}
	out.DrainTimeout = in.DrainTimeout
	out.StorageHealthTimeout = in.StorageHealthTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptionsTalos.
func (in *OptionsTalos) DeepCopy() *OptionsTalos {
	if in == nil {
		return nil
	}
	out := new(OptionsTalos)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptionsVanilla) DeepCopyInto(out *OptionsVanilla) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptionsVanilla.
func (in *OptionsVanilla) DeepCopy() *OptionsVanilla {
	if in == nil {
		return nil
	}
	out := new(OptionsVanilla)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParsedRegistry) DeepCopyInto(out *ParsedRegistry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParsedRegistry.
func (in *ParsedRegistry) DeepCopy() *ParsedRegistry {
	if in == nil {
		return nil
	}
	out := new(ParsedRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodAutoscalerConfig) DeepCopyInto(out *PodAutoscalerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodAutoscalerConfig.
func (in *PodAutoscalerConfig) DeepCopy() *PodAutoscalerConfig {
	if in == nil {
		return nil
	}
	out := new(PodAutoscalerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortMapping) DeepCopyInto(out *PortMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortMapping.
func (in *PortMapping) DeepCopy() *PortMapping {
	if in == nil {
		return nil
	}
	out := new(PortMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSpec) DeepCopyInto(out *ProviderSpec) {
	*out = *in
	in.Hetzner.DeepCopyInto(&out.Hetzner)
	in.Omni.DeepCopyInto(&out.Omni)
	out.AWS = in.AWS
	out.GCP = in.GCP
	out.Azure = in.Azure
	out.Kubernetes = in.Kubernetes
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSpec.
func (in *ProviderSpec) DeepCopy() *ProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryCredentials) DeepCopyInto(out *RegistryCredentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryCredentials.
func (in *RegistryCredentials) DeepCopy() *RegistryCredentials {
	if in == nil {
		return nil
	}
	out := new(RegistryCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SOPS) DeepCopyInto(out *SOPS) {
	*out = *in
	out.Env = in.Env
	in.Extract.DeepCopyInto(&out.Extract)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SOPS.
func (in *SOPS) DeepCopy() *SOPS {
	if in == nil {
		return nil
	}
	out := new(SOPS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SOPSEnv) DeepCopyInto(out *SOPSEnv) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SOPSEnv.
func (in *SOPSEnv) DeepCopy() *SOPSEnv {
	if in == nil {
		return nil
	}
	out := new(SOPSEnv)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SOPSExtract) DeepCopyInto(out *SOPSExtract) {
	*out = *in
	if in.PublicKeys != nil {
		in, out := &in.PublicKeys, &out.PublicKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SOPSExtract.
func (in *SOPSExtract) DeepCopy() *SOPSExtract {
	if in == nil {
		return nil
	}
	out := new(SOPSExtract)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanConfig) DeepCopyInto(out *ScanConfig) {
	*out = *in
	if in.Frameworks != nil {
		in, out := &in.Frameworks, &out.Frameworks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ComplianceThreshold != nil {
		in, out := &in.ComplianceThreshold, &out.ComplianceThreshold
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanConfig.
func (in *ScanConfig) DeepCopy() *ScanConfig {
	if in == nil {
		return nil
	}
	out := new(ScanConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Spec) DeepCopyInto(out *Spec) {
	*out = *in
	in.Cluster.DeepCopyInto(&out.Cluster)
	in.Provider.DeepCopyInto(&out.Provider)
	in.Workload.DeepCopyInto(&out.Workload)
	out.Chat = in.Chat
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Spec.
func (in *Spec) DeepCopy() *Spec {
	if in == nil {
		return nil
	}
	out := new(Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationConfig) DeepCopyInto(out *ValidationConfig) {
	*out = *in
	if in.SkipKinds != nil {
		in, out := &in.SkipKinds, &out.SkipKinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SchemaLocations != nil {
		in, out := &in.SchemaLocations, &out.SchemaLocations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HelmRender != nil {
		in, out := &in.HelmRender, &out.HelmRender
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationConfig.
func (in *ValidationConfig) DeepCopy() *ValidationConfig {
	if in == nil {
		return nil
	}
	out := new(ValidationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatchConfig) DeepCopyInto(out *WatchConfig) {
	*out = *in
	if in.Hooks != nil {
		in, out := &in.Hooks, &out.Hooks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatchConfig.
func (in *WatchConfig) DeepCopy() *WatchConfig {
	if in == nil {
		return nil
	}
	out := new(WatchConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSpec) DeepCopyInto(out *WorkloadSpec) {
	*out = *in
	in.Flux.DeepCopyInto(&out.Flux)
	in.Watch.DeepCopyInto(&out.Watch)
	in.Validation.DeepCopyInto(&out.Validation)
	in.Scan.DeepCopyInto(&out.Scan)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSpec.
func (in *WorkloadSpec) DeepCopy() *WorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadSpec)
	in.DeepCopyInto(out)
	return out
}
