// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package configmanager

import (
	"github.com/devantler-tech/ksail/v5/pkg/fsutil/configmanager"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigManager creates a new instance of MockConfigManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigManager[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigManager[T] {
	m := &MockConfigManager[T]{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockConfigManager is an autogenerated mock type for the ConfigManager type
type MockConfigManager[T any] struct {
	mock.Mock
}

type MockConfigManager_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockConfigManager[T]) EXPECT() *MockConfigManager_Expecter[T] {
	return &MockConfigManager_Expecter[T]{mock: &_m.Mock}
}

// Load provides a mock function for the type MockConfigManager
func (_mock *MockConfigManager[T]) Load(opts configmanager.LoadOptions) (*T, error) {
	ret := _mock.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(configmanager.LoadOptions) (*T, error)); ok {
		return returnFunc(opts)
	}
	if returnFunc, ok := ret.Get(0).(func(configmanager.LoadOptions) *T); ok {
		r0 = returnFunc(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(configmanager.LoadOptions) error); ok {
		r1 = returnFunc(opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigManager_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockConfigManager_Load_Call[T any] struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - opts configmanager.LoadOptions
func (_e *MockConfigManager_Expecter[T]) Load(opts interface{}) *MockConfigManager_Load_Call[T] {
	return &MockConfigManager_Load_Call[T]{Call: _e.mock.On("Load", opts)}
}

func (_c *MockConfigManager_Load_Call[T]) Run(run func(opts configmanager.LoadOptions)) *MockConfigManager_Load_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 configmanager.LoadOptions
		if args[0] != nil {
			arg0 = args[0].(configmanager.LoadOptions)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigManager_Load_Call[T]) Return(v *T, err error) *MockConfigManager_Load_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockConfigManager_Load_Call[T]) RunAndReturn(run func(opts configmanager.LoadOptions) (*T, error)) *MockConfigManager_Load_Call[T] {
	_c.Call.Return(run)
	return _c
}
