// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package argocd

import (
	"context"

	"github.com/devantler-tech/ksail/v5/pkg/client/argocd"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInstaller creates a new instance of MockInstaller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstaller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstaller {
	mock := &MockInstaller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInstaller is an autogenerated mock type for the Installer type
type MockInstaller struct {
	mock.Mock
}

type MockInstaller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstaller) EXPECT() *MockInstaller_Expecter {
	return &MockInstaller_Expecter{mock: &_m.Mock}
}

// Install provides a mock function for the type MockInstaller
func (_mock *MockInstaller) Install(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Install")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInstaller_Install_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Install'
type MockInstaller_Install_Call struct {
	*mock.Call
}

// Install is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInstaller_Expecter) Install(ctx interface{}) *MockInstaller_Install_Call {
	return &MockInstaller_Install_Call{Call: _e.mock.On("Install", ctx)}
}

func (_c *MockInstaller_Install_Call) Run(run func(ctx context.Context)) *MockInstaller_Install_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInstaller_Install_Call) Return(err error) *MockInstaller_Install_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInstaller_Install_Call) RunAndReturn(run func(ctx context.Context) error) *MockInstaller_Install_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// Ensure provides a mock function for the type MockManager
func (_mock *MockManager) Ensure(ctx context.Context, opts argocd.EnsureOptions) error {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Ensure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, argocd.EnsureOptions) error); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_Ensure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ensure'
type MockManager_Ensure_Call struct {
	*mock.Call
}

// Ensure is a helper method to define mock.On call
//   - ctx context.Context
//   - opts argocd.EnsureOptions
func (_e *MockManager_Expecter) Ensure(ctx interface{}, opts interface{}) *MockManager_Ensure_Call {
	return &MockManager_Ensure_Call{Call: _e.mock.On("Ensure", ctx, opts)}
}

func (_c *MockManager_Ensure_Call) Run(run func(ctx context.Context, opts argocd.EnsureOptions)) *MockManager_Ensure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 argocd.EnsureOptions
		if args[1] != nil {
			arg1 = args[1].(argocd.EnsureOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_Ensure_Call) Return(err error) *MockManager_Ensure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_Ensure_Call) RunAndReturn(run func(ctx context.Context, opts argocd.EnsureOptions) error) *MockManager_Ensure_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTargetRevision provides a mock function for the type MockManager
func (_mock *MockManager) UpdateTargetRevision(ctx context.Context, opts argocd.UpdateTargetRevisionOptions) error {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTargetRevision")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, argocd.UpdateTargetRevisionOptions) error); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_UpdateTargetRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTargetRevision'
type MockManager_UpdateTargetRevision_Call struct {
	*mock.Call
}

// UpdateTargetRevision is a helper method to define mock.On call
//   - ctx context.Context
//   - opts argocd.UpdateTargetRevisionOptions
func (_e *MockManager_Expecter) UpdateTargetRevision(ctx interface{}, opts interface{}) *MockManager_UpdateTargetRevision_Call {
	return &MockManager_UpdateTargetRevision_Call{Call: _e.mock.On("UpdateTargetRevision", ctx, opts)}
}

func (_c *MockManager_UpdateTargetRevision_Call) Run(run func(ctx context.Context, opts argocd.UpdateTargetRevisionOptions)) *MockManager_UpdateTargetRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 argocd.UpdateTargetRevisionOptions
		if args[1] != nil {
			arg1 = args[1].(argocd.UpdateTargetRevisionOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_UpdateTargetRevision_Call) Return(err error) *MockManager_UpdateTargetRevision_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_UpdateTargetRevision_Call) RunAndReturn(run func(ctx context.Context, opts argocd.UpdateTargetRevisionOptions) error) *MockManager_UpdateTargetRevision_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStatusProvider creates a new instance of MockStatusProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatusProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatusProvider {
	mock := &MockStatusProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStatusProvider is an autogenerated mock type for the StatusProvider type
type MockStatusProvider struct {
	mock.Mock
}

type MockStatusProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatusProvider) EXPECT() *MockStatusProvider_Expecter {
	return &MockStatusProvider_Expecter{mock: &_m.Mock}
}

// GetStatus provides a mock function for the type MockStatusProvider
func (_mock *MockStatusProvider) GetStatus(ctx context.Context) (argocd.Status, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 argocd.Status
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (argocd.Status, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) argocd.Status); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(argocd.Status)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatusProvider_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockStatusProvider_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStatusProvider_Expecter) GetStatus(ctx interface{}) *MockStatusProvider_GetStatus_Call {
	return &MockStatusProvider_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx)}
}

func (_c *MockStatusProvider_GetStatus_Call) Run(run func(ctx context.Context)) *MockStatusProvider_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatusProvider_GetStatus_Call) Return(status argocd.Status, err error) *MockStatusProvider_GetStatus_Call {
	_c.Call.Return(status, err)
	return _c
}

func (_c *MockStatusProvider_GetStatus_Call) RunAndReturn(run func(ctx context.Context) (argocd.Status, error)) *MockStatusProvider_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}
