---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- patch: |-
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      name: all
    spec:
      install:
        crds: CreateReplace
      upgrade:
        crds: CreateReplace
  target:
    kind: HelmRelease
    labelSelector: helm.toolkit.fluxcd.io/crds=enabled
