name: KSail System Test
description: |
  Runs a full end-to-end system test of KSail, testing cluster lifecycle
  and workload management capabilities.

inputs:
  distribution:
    description: Kubernetes distribution (Vanilla, K3s, Talos)
    required: true
  provider:
    description: Infrastructure provider (Docker, Hetzner)
    required: false
    default: "Docker"
  args:
    description: Additional arguments for cluster init/create
    required: false
    default: ""
  init:
    description: Whether to run ksail cluster init before create
    required: false
    default: "false"
  test-workload-image:
    description: Image to use for workload create test
    required: false
    default: "traefik/whoami:latest"
  test-workload-name:
    description: Name for the test workload deployment
    required: false
    default: "whoami"
  apply-overlay-path:
    description: Path to kustomize overlay for workload apply test
    required: false
    default: ""
  gitops-path:
    description: Path for GitOps push (only if --gitops-engine in args)
    required: false
    default: "k8s"
  workload-timeout:
    description: Timeout for workload wait operations
    required: false
    default: "300s"
  hcloud-token:
    description: Hetzner Cloud API token (required when provider is Hetzner)
    required: false
    default: ""
  ghcr-user:
    description: GitHub Container Registry username (for external registry auth)
    required: false
    default: ""
  ghcr-token:
    description: GitHub Container Registry token (for external registry auth)
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: ðŸ”§ Resolve GHCR credentials in args
      id: resolve-args
      shell: bash
      env:
        ARGS: ${{ inputs.args }}
        GHCR_USER: ${{ inputs.ghcr-user }}
        GHCR_TOKEN: ${{ inputs.ghcr-token }}
      run: |
        # Inject GHCR credentials into --local-registry if it contains ghcr.io
        RESOLVED_ARGS="$ARGS"
        if [[ "$ARGS" == *"--local-registry"* ]] && [[ "$ARGS" == *"ghcr.io"* ]] && [[ -n "$GHCR_USER" ]] && [[ -n "$GHCR_TOKEN" ]]; then
          # Replace 'ghcr.io/' with 'user:token@ghcr.io/'
          RESOLVED_ARGS="${ARGS//ghcr.io\//${GHCR_USER}:${GHCR_TOKEN}@ghcr.io/}"
        fi
        echo "args=$RESOLVED_ARGS" >> "$GITHUB_OUTPUT"

    - name: ðŸ§ª ksail cluster init
      if: inputs.init == 'true'
      shell: bash
      env:
        DISTRIBUTION: ${{ inputs.distribution }}
        PROVIDER: ${{ inputs.provider }}
        ARGS: ${{ steps.resolve-args.outputs.args }}
        HCLOUD_TOKEN: ${{ inputs.hcloud-token }}
      run: |
        ksail cluster init --distribution "$DISTRIBUTION" --provider "$PROVIDER" $ARGS

    - name: ðŸ§ª ksail cluster create
      shell: bash
      env:
        INIT: ${{ inputs.init }}
        DISTRIBUTION: ${{ inputs.distribution }}
        PROVIDER: ${{ inputs.provider }}
        ARGS: ${{ steps.resolve-args.outputs.args }}
        HCLOUD_TOKEN: ${{ inputs.hcloud-token }}
      run: |
        if [ "$INIT" = "true" ]; then
          ksail cluster create
        else
          ksail cluster create --distribution "$DISTRIBUTION" --provider "$PROVIDER" $ARGS
        fi

    - name: ðŸ§ª ksail cluster list
      shell: bash
      env:
        HCLOUD_TOKEN: ${{ inputs.hcloud-token }}
      run: |
        ksail cluster list

    - name: ðŸ§ª ksail workload create
      id: workload-create
      shell: bash
      env:
        WORKLOAD_NAME: ${{ inputs.test-workload-name }}
        WORKLOAD_IMAGE: ${{ inputs.test-workload-image }}
        TIMEOUT: ${{ inputs.workload-timeout }}
        HCLOUD_TOKEN: ${{ inputs.hcloud-token }}
      run: |
        ksail workload create deployment "$WORKLOAD_NAME" --image="$WORKLOAD_IMAGE"
        ksail workload wait --for=condition=Available deployment/"$WORKLOAD_NAME" --timeout="$TIMEOUT"

    - name: ðŸ§ª ksail workload apply
      id: workload-apply
      if: inputs.apply-overlay-path != ''
      shell: bash
      env:
        OVERLAY_PATH: ${{ inputs.apply-overlay-path }}
        TIMEOUT: ${{ inputs.workload-timeout }}
        HCLOUD_TOKEN: ${{ inputs.hcloud-token }}
      run: ksail workload apply -k "$OVERLAY_PATH" --wait --timeout="$TIMEOUT"

    - name: ðŸ§ª ksail workload push and reconcile
      id: workload-push-reconcile
      if: contains(inputs.args, '--gitops-engine')
      shell: bash
      env:
        GITOPS_PATH: ${{ inputs.gitops-path }}
        HCLOUD_TOKEN: ${{ inputs.hcloud-token }}
        GHCR_USER: ${{ inputs.ghcr-user }}
        GHCR_TOKEN: ${{ inputs.ghcr-token }}
        ARGS: ${{ inputs.args }}
      run: |
        mkdir -p "$GITOPS_PATH"
        if [ ! -f "$GITOPS_PATH/kustomization.yaml" ]; then
          echo "apiVersion: kustomize.config.k8s.io/v1beta1" > "$GITOPS_PATH/kustomization.yaml"
          echo "kind: Kustomization" >> "$GITOPS_PATH/kustomization.yaml"
          echo "resources: []" >> "$GITOPS_PATH/kustomization.yaml"
        fi
        # Extract registry from args and inject credentials for push
        if [[ "$ARGS" == *"--local-registry"* ]] && [[ "$ARGS" == *"ghcr.io"* ]] && [[ -n "$GHCR_USER" ]] && [[ -n "$GHCR_TOKEN" ]]; then
          # Extract the registry path from args (e.g., ghcr.io/org/repo/path)
          REGISTRY_PATH=$(echo "$ARGS" | grep -oP '(?<=--local-registry\s)[^\s]+' | sed 's/.*@//')
          export KSAIL_REGISTRY="${GHCR_USER}:${GHCR_TOKEN}@${REGISTRY_PATH}"
        fi
        ksail workload push --path "$GITOPS_PATH/"
        ksail workload reconcile

    - name: ðŸž Debug workload failure
      if: failure() && (steps.workload-create.outcome == 'failure' || steps.workload-apply.outcome == 'failure' || steps.workload-push-reconcile.outcome == 'failure')
      uses: ./.github/actions/debug-kubernetes-failure
      with:
        kubectl-command: "ksail workload"

    - name: ðŸ§ª ksail cluster stop
      shell: bash
      env:
        HCLOUD_TOKEN: ${{ inputs.hcloud-token }}
      run: |
        ksail cluster stop

    - name: ðŸ§ª ksail cluster start
      shell: bash
      env:
        HCLOUD_TOKEN: ${{ inputs.hcloud-token }}
      run: |
        ksail cluster start

    - name: ðŸ§ª ksail cluster delete
      if: always()
      shell: bash
      env:
        HCLOUD_TOKEN: ${{ inputs.hcloud-token }}
      run: |
        ksail cluster delete
