name: KSail System Test
description: |
  Runs a full end-to-end system test of KSail, testing cluster lifecycle
  and workload management capabilities.

inputs:
  distribution:
    description: Kubernetes distribution (Vanilla, K3s, Talos, VCluster)
    required: true
  provider:
    description: Infrastructure provider (Docker, Hetzner, Omni)
    required: false
    default: "Docker"
  args:
    description: Additional arguments for cluster init/create
    required: false
    default: ""
  init:
    description: Whether to run ksail cluster init before create
    required: false
    default: "false"
  test-workload-image:
    description: Image to use for workload create test
    required: false
    default: "traefik/whoami:latest"
  test-workload-name:
    description: Name for the test workload deployment
    required: false
    default: "whoami"
  apply-overlay-path:
    description: Path to kustomize overlay for workload apply test
    required: false
    default: ""
  gitops-path:
    description: Path for GitOps push (only if --gitops-engine in args)
    required: false
    default: "k8s"
  workload-timeout:
    description: |
      Timeout for workload wait operations. Set to 10 minutes to handle
      intermittent delays in CI environments (image pulls, resource contention).
    required: false
    default: "600s"
  hcloud-token:
    description: Hetzner Cloud API token (required when provider is Hetzner)
    required: false
    default: ""
  omni-service-account-key:
    description: Omni service account key (required when provider is Omni)
    required: false
    default: ""
  omni-endpoint:
    description: Omni API endpoint URL (required when provider is Omni)
    required: false
    default: ""
  ghcr-user:
    description: GitHub Container Registry username (for external registry auth)
    required: false
    default: ""
  ghcr-token:
    description: GitHub Container Registry token (for external registry auth)
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: 🔧 Generate unique artifact tag
      id: generate-tag
      shell: bash
      env:
        DISTRIBUTION: ${{ inputs.distribution }}
        PROVIDER: ${{ inputs.provider }}
        INIT: ${{ inputs.init }}
        ARGS: ${{ inputs.args }}
      run: |
        # Generate unique tag: distribution-provider-init-sanitized_args-shortsha
        DIST_LOWER=$(echo "$DISTRIBUTION" | tr '[:upper:]' '[:lower:]')
        PROVIDER_LOWER=$(echo "$PROVIDER" | tr '[:upper:]' '[:lower:]')
        INIT_SUFFIX=$([ "$INIT" = "true" ] && echo "init" || echo "no-init")
        # Sanitize args: extract key values, remove special chars, lowercase
        ARGS_SANITIZED=$(echo "$ARGS" | sed 's/--[a-z-]*=\?//g' | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-' | sed 's/^-//;s/-$//' | cut -c1-30)
        SHORT_SHA="${GITHUB_SHA:0:7}"
        if [[ -n "$ARGS_SANITIZED" ]]; then
          TAG="${DIST_LOWER}-${PROVIDER_LOWER}-${INIT_SUFFIX}-${ARGS_SANITIZED}-${SHORT_SHA}"
        else
          TAG="${DIST_LOWER}-${PROVIDER_LOWER}-${INIT_SUFFIX}-${SHORT_SHA}"
        fi
        echo "tag=$TAG" >> "$GITHUB_OUTPUT"
        echo "Generated unique artifact tag: $TAG"

    - name: 🔧 Resolve GHCR credentials in args
      id: resolve-args
      shell: bash
      env:
        ARGS: ${{ inputs.args }}
        GHCR_USER: ${{ inputs.ghcr-user }}
        GHCR_TOKEN: ${{ inputs.ghcr-token }}
        ARTIFACT_TAG: ${{ steps.generate-tag.outputs.tag }}
      run: |
        # Inject GHCR credentials into --local-registry if it contains ghcr.io
        RESOLVED_ARGS="$ARGS"
        if [[ "$ARGS" == *"--local-registry"* ]] && [[ "$ARGS" == *"ghcr.io"* ]] && [[ -n "$GHCR_USER" ]] && [[ -n "$GHCR_TOKEN" ]]; then
          # Replace 'ghcr.io/' with 'user:token@ghcr.io/'
          RESOLVED_ARGS="${ARGS//ghcr.io\//${GHCR_USER}:${GHCR_TOKEN}@ghcr.io/}"
          # Append unique tag to avoid collisions between parallel CI runs
          # Format: user:token@ghcr.io/org/repo/path -> user:token@ghcr.io/org/repo/path:tag
          RESOLVED_ARGS="${RESOLVED_ARGS}:${ARTIFACT_TAG}"
        fi
        echo "args=$RESOLVED_ARGS" >> "$GITHUB_OUTPUT"

    - name: 🧪 ksail cluster init
      if: inputs.init == 'true'
      shell: bash
      env:
        DISTRIBUTION: ${{ inputs.distribution }}
        PROVIDER: ${{ inputs.provider }}
        ARGS: ${{ steps.resolve-args.outputs.args }}
        HCLOUD_TOKEN: ${{ inputs.hcloud-token }}
        OMNI_SERVICE_ACCOUNT_KEY: ${{ inputs.omni-service-account-key }}
      run: |
        # shellcheck disable=SC2086
        ksail cluster init --distribution "$DISTRIBUTION" --provider "$PROVIDER" $ARGS --force

    - name: 🔧 Configure Omni endpoint
      if: inputs.provider == 'Omni' && inputs.omni-endpoint != ''
      shell: bash
      env:
        OMNI_ENDPOINT: ${{ inputs.omni-endpoint }}
      run: |
        CONFIG_FILE="ksail.yaml"
        if [ ! -f "$CONFIG_FILE" ]; then
          # Create minimal config for non-init flow
          cat > "$CONFIG_FILE" <<'EOF'
        apiVersion: ksail.io/v1alpha1
        kind: Cluster
        spec:
          cluster:
            omni:
              endpoint: ""
        EOF
        fi
        # Inject Omni endpoint into spec.cluster.omni.endpoint
        # Use yq to set the field; install if not available
        if ! command -v yq &> /dev/null; then
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
        fi
        yq -i '.spec.cluster.omni.endpoint = env(OMNI_ENDPOINT)' "$CONFIG_FILE"
        echo "✅ Omni endpoint configured in $CONFIG_FILE"

    - name: 📥 Restore mirror cache
      id: restore-mirror-cache
      if: inputs.provider == 'Docker'
      uses: ./.github/actions/restore-mirror-cache

    - name: 🔍 Verify mirror volumes restored
      if: inputs.provider == 'Docker' && steps.restore-mirror-cache.outputs.cache-hit == 'true'
      shell: bash
      run: |
        echo "📦 Verifying mirror cache volumes (see issue #2075)..."
        REQUIRED_VOLUMES=("docker.io" "ghcr.io" "quay.io" "registry.k8s.io")
        MISSING_VOLUMES=()

        for vol in "${REQUIRED_VOLUMES[@]}"; do
          if docker volume inspect "$vol" > /dev/null 2>&1; then
            SIZE=$(docker run --rm -v "$vol":/vol busybox du -sh /vol 2>/dev/null | cut -f1 || echo "unknown")
            echo "  ✅ $vol (size: $SIZE)"
          else
            echo "  ❌ $vol - MISSING"
            MISSING_VOLUMES+=("$vol")
          fi
        done

        if [ ${#MISSING_VOLUMES[@]} -gt 0 ]; then
          echo "⚠️ Warning: ${#MISSING_VOLUMES[@]} mirror volumes missing: ${MISSING_VOLUMES[*]}"
          echo "   Images from these registries may need to be pulled directly."
        else
          echo "✅ All 4 mirror cache volumes present"
        fi

    - name: 📥 Restore Helm chart cache
      uses: ./.github/actions/restore-helm-cache

    - name: 📥 Pre-pull registry image
      if: inputs.provider == 'Docker'
      shell: bash
      run: |
        pulled=false
        for attempt in 1 2 3; do
          if docker pull registry:3; then
            echo "✅ registry:3 image pulled successfully"
            pulled=true
            break
          fi
          echo "⚠️ registry:3 pull attempt $attempt failed, retrying in 5s…"
          sleep 5
        done
        if [ "$pulled" = false ]; then
          echo "❌ Failed to pull registry:3 after 3 attempts"
          exit 1
        fi

    - name: 🧪 ksail cluster create
      id: cluster-create
      shell: bash
      env:
        INIT: ${{ inputs.init }}
        DISTRIBUTION: ${{ inputs.distribution }}
        PROVIDER: ${{ inputs.provider }}
        ARGS: ${{ steps.resolve-args.outputs.args }}
        HCLOUD_TOKEN: ${{ inputs.hcloud-token }}
        OMNI_SERVICE_ACCOUNT_KEY: ${{ inputs.omni-service-account-key }}
      run: |
        if [ "$INIT" = "true" ]; then
          ksail cluster create
        else
          # shellcheck disable=SC2086
          ksail cluster create --distribution "$DISTRIBUTION" --provider "$PROVIDER" $ARGS
        fi

    - name: 🧪 ksail cluster list
      shell: bash
      env:
        HCLOUD_TOKEN: ${{ inputs.hcloud-token }}
        OMNI_SERVICE_ACCOUNT_KEY: ${{ inputs.omni-service-account-key }}
        OMNI_ENDPOINT: ${{ inputs.omni-endpoint }}
      run: |
        ksail cluster list

    - name: 🧪 ksail workload create
      id: workload-create
      shell: bash
      env:
        WORKLOAD_NAME: ${{ inputs.test-workload-name }}
        WORKLOAD_IMAGE: ${{ inputs.test-workload-image }}
        TIMEOUT: ${{ inputs.workload-timeout }}
        HCLOUD_TOKEN: ${{ inputs.hcloud-token }}
        OMNI_SERVICE_ACCOUNT_KEY: ${{ inputs.omni-service-account-key }}
      run: |
        for attempt in 1 2 3; do
          if ksail workload create deployment "$WORKLOAD_NAME" --image="$WORKLOAD_IMAGE"; then
            break
          fi
          echo "⚠️ workload create attempt $attempt failed, retrying in 10s…"
          sleep 10
        done
        ksail workload wait --for=condition=Available deployment/"$WORKLOAD_NAME" --timeout="$TIMEOUT"

    - name: 🧪 ksail workload apply
      id: workload-apply
      if: inputs.apply-overlay-path != ''
      shell: bash
      env:
        OVERLAY_PATH: ${{ inputs.apply-overlay-path }}
        TIMEOUT: ${{ inputs.workload-timeout }}
        HCLOUD_TOKEN: ${{ inputs.hcloud-token }}
        OMNI_SERVICE_ACCOUNT_KEY: ${{ inputs.omni-service-account-key }}
      run: ksail workload apply -k "$OVERLAY_PATH" --wait --timeout="$TIMEOUT"

    - name: 🧪 ksail workload push and reconcile
      id: workload-push-reconcile
      if: contains(inputs.args, '--gitops-engine')
      shell: bash
      env:
        GITOPS_PATH: ${{ inputs.gitops-path }}
        HCLOUD_TOKEN: ${{ inputs.hcloud-token }}
        OMNI_SERVICE_ACCOUNT_KEY: ${{ inputs.omni-service-account-key }}
        GHCR_USER: ${{ inputs.ghcr-user }}
        GHCR_TOKEN: ${{ inputs.ghcr-token }}
      run: |
        mkdir -p "$GITOPS_PATH"
        if [ ! -f "$GITOPS_PATH/kustomization.yaml" ]; then
          echo "apiVersion: kustomize.config.k8s.io/v1beta1" > "$GITOPS_PATH/kustomization.yaml"
          echo "kind: Kustomization" >> "$GITOPS_PATH/kustomization.yaml"
          echo "resources: []" >> "$GITOPS_PATH/kustomization.yaml"
        fi
        ksail workload push --path "$GITOPS_PATH/"
        ksail workload reconcile

    - name: 🧪 ksail cluster update --dry-run
      id: cluster-update-dry-run
      shell: bash
      env:
        DISTRIBUTION: ${{ inputs.distribution }}
        PROVIDER: ${{ inputs.provider }}
        ARGS: ${{ steps.resolve-args.outputs.args }}
        HCLOUD_TOKEN: ${{ inputs.hcloud-token }}
        OMNI_SERVICE_ACCOUNT_KEY: ${{ inputs.omni-service-account-key }}
      run: |
        # shellcheck disable=SC2086
        ksail cluster update --dry-run --distribution "$DISTRIBUTION" --provider "$PROVIDER" $ARGS

    - name: 🧪 ksail cluster update
      id: cluster-update
      shell: bash
      env:
        DISTRIBUTION: ${{ inputs.distribution }}
        PROVIDER: ${{ inputs.provider }}
        ARGS: ${{ steps.resolve-args.outputs.args }}
        HCLOUD_TOKEN: ${{ inputs.hcloud-token }}
        OMNI_SERVICE_ACCOUNT_KEY: ${{ inputs.omni-service-account-key }}
      run: |
        # shellcheck disable=SC2086
        ksail cluster update --force --distribution "$DISTRIBUTION" --provider "$PROVIDER" $ARGS

    - name: 🐞 Debug Kubernetes failure
      if: failure() && (steps.cluster-create.outcome == 'failure' || steps.workload-create.outcome == 'failure' || steps.workload-apply.outcome == 'failure' || steps.workload-push-reconcile.outcome == 'failure' || steps.cluster-update-dry-run.outcome == 'failure' || steps.cluster-update.outcome == 'failure')
      uses: ./.github/actions/debug-kubernetes-failure
      with:
        kubectl-command: "ksail workload"

    - name: 🧪 ksail cluster stop
      shell: bash
      env:
        HCLOUD_TOKEN: ${{ inputs.hcloud-token }}
        OMNI_SERVICE_ACCOUNT_KEY: ${{ inputs.omni-service-account-key }}
      run: |
        ksail cluster stop

    - name: 🧪 ksail cluster start
      shell: bash
      env:
        HCLOUD_TOKEN: ${{ inputs.hcloud-token }}
        OMNI_SERVICE_ACCOUNT_KEY: ${{ inputs.omni-service-account-key }}
      run: |
        timeout 600 ksail cluster start

    - name: 🧪 ksail cluster delete
      if: always()
      shell: bash
      env:
        HCLOUD_TOKEN: ${{ inputs.hcloud-token }}
        OMNI_SERVICE_ACCOUNT_KEY: ${{ inputs.omni-service-account-key }}
      run: |
        ksail cluster delete
