---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- patch: |-
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: all
    spec:
      decryption:
        provider: sops
        secretRef:
          name: sops-age
  target:
    kind: Kustomization
    labelSelector: kustomize.toolkit.fluxcd.io/sops=enabled
