name: Restore Helm Cache
description: |
  Restores the pre-warmed Helm chart cache created by warm-helm-cache.
  Use this in system test jobs to benefit from the warmed cache.

  The cache key is computed by hashing installer source files, ensuring
  restore jobs can find the cache created by warm-helm-cache.

inputs:
  cache-version:
    description: |
      Version salt for cache key. Must match warm-helm-cache.
    required: false
    default: "v1"

outputs:
  cache-hit:
    description: Whether the cache was found and restored
    value: ${{ steps.restore-cache.outputs.cache-hit || 'false' }}

runs:
  using: composite
  steps:
    - name: 🔑 Generate cache key
      id: generate-key
      shell: bash
      env:
        CACHE_VERSION: ${{ inputs.cache-version }}
        RUNNER_OS: ${{ runner.os }}
        RUNNER_ARCH: ${{ runner.arch }}
      run: |
        # Same key computation as warm-helm-cache for identical cache lookup
        INSTALLER_HASH=$(find pkg/svc/installer -name 'installer.go' -exec sha256sum {} + | sort | sha256sum | cut -c1-12)
        CACHE_KEY="helm-cache-${CACHE_VERSION}-${INSTALLER_HASH}-${RUNNER_OS}-${RUNNER_ARCH}"
        echo "cache-key=$CACHE_KEY" >> "$GITHUB_OUTPUT"

    - name: 📥 Restore Helm chart cache
      id: restore-cache
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ~/.cache/helm/content
          ~/.cache/helm/repository
          ~/.config/helm/repositories.yaml
        key: ${{ steps.generate-key.outputs.cache-key }}
        restore-keys: |
          helm-cache-${{ inputs.cache-version }}-${{ runner.os }}-${{ runner.arch }}-

    - name: ℹ️ Cache miss notice
      if: steps.restore-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "⚠️ Helm chart cache not found. Charts will be downloaded directly."
        echo "   This may increase test duration and risk rate limits."
        echo "   The warm-helm-cache job should run before system tests."
