---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apps.yaml
- infrastructure.yaml
- infrastructure-controllers.yaml
- variables.yaml
components:
- ../../../components/flux-kustomization-post-build-variables-label
