name: Debug Kubernetes Failure
description: |
  Outputs diagnostic information for debugging Kubernetes cluster failures.
  Shows disk usage, node status, pod status, recent events, and GitOps resource statuses (FluxInstance, OCIRepository, ArgoCD Application).

inputs:
  kubectl-command:
    description: The kubectl command or wrapper to use (e.g., "kubectl", "ksail workload")
    required: false
    default: "kubectl"
  show-disk-usage:
    description: Show host and Docker disk usage
    required: false
    default: "true"
  show-nodes:
    description: Show node status and conditions
    required: false
    default: "true"
  show-pods:
    description: Show pod status
    required: false
    default: "true"
  show-events:
    description: Show recent cluster events
    required: false
    default: "true"
  events-limit:
    description: Number of recent events to show
    required: false
    default: "50"
  namespace:
    description: Namespace to query (empty for all namespaces)
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: ðŸž Debug Kubernetes failure
      shell: bash
      env:
        KUBECTL_CMD: ${{ inputs.kubectl-command }}
        NAMESPACE: ${{ inputs.namespace }}
        SHOW_DISK_USAGE: ${{ inputs.show-disk-usage }}
        SHOW_NODES: ${{ inputs.show-nodes }}
        SHOW_PODS: ${{ inputs.show-pods }}
        SHOW_EVENTS: ${{ inputs.show-events }}
        EVENTS_LIMIT: ${{ inputs.events-limit }}
      run: |
        NS_FLAG=""
        if [ -n "$NAMESPACE" ]; then
          NS_FLAG="-n $NAMESPACE"
        fi

        if [ "$SHOW_DISK_USAGE" = "true" ]; then
          echo "=== Disk Usage ==="
          df -h /
          echo ""
          echo "=== Docker Disk Usage ==="
          docker system df || true
          echo ""
        fi

        if [ "$SHOW_NODES" = "true" ]; then
          echo "=== Node Status ==="
          $KUBECTL_CMD get nodes -o wide || true
          echo ""
          echo "=== Node Describe (conditions) ==="
          $KUBECTL_CMD describe nodes | grep -A 20 "Conditions:" || true
          echo ""
        fi

        if [ "$SHOW_PODS" = "true" ]; then
          echo "=== Pod Status ==="
          $KUBECTL_CMD get pods $NS_FLAG -o wide || true
          echo ""
        fi

        if [ "$SHOW_EVENTS" = "true" ]; then
          echo "=== Pod Events ==="
          $KUBECTL_CMD get events $NS_FLAG --sort-by='.lastTimestamp' | tail -"$EVENTS_LIMIT" || true
          echo ""
        fi

        # GitOps resource status for debugging Flux and ArgoCD deployments
        # Note: Use plain kubectl for api-resources since ksail workload doesn't support it
        
        echo "=== Flux Operator Status ==="
        # Check for Flux Operator pods (installed before FluxInstance CRD exists)
        FLUX_OPERATOR_PODS=$($KUBECTL_CMD get pods -n flux-system -l app.kubernetes.io/name=flux-operator -o name 2>/dev/null || true)
        if [ -n "$FLUX_OPERATOR_PODS" ]; then
          $KUBECTL_CMD get pods -n flux-system -l app.kubernetes.io/name=flux-operator -o wide
          echo ""
          echo "=== Flux Operator Pod Logs ==="
          $KUBECTL_CMD logs -n flux-system -l app.kubernetes.io/name=flux-operator --tail=100 2>/dev/null || true
        else
          echo "No Flux Operator pods found in flux-system namespace"
        fi
        echo ""
        
        echo "=== FluxInstance Status ==="
        # Check if the CRD exists first (use kubectl directly for api-resources)
        if kubectl api-resources --api-group=fluxcd.controlplane.io 2>/dev/null | grep -q fluxinstance; then
          echo "FluxInstance CRD is registered"
          FLUX_INSTANCES=$($KUBECTL_CMD get fluxinstance -A -o name 2>/dev/null || true)
          if [ -n "$FLUX_INSTANCES" ]; then
            $KUBECTL_CMD get fluxinstance -A -o wide
            echo ""
            echo "=== FluxInstance Details ==="
            $KUBECTL_CMD describe fluxinstance -A
          else
            echo "FluxInstance CRD exists but no FluxInstance resources found"
          fi
        else
          echo "FluxInstance CRD not registered (Flux Operator may not be installed)"
        fi
        echo ""

        echo "=== OCIRepository Status ==="
        # Check if the CRD exists first (use kubectl directly for api-resources)
        if kubectl api-resources --api-group=source.toolkit.fluxcd.io 2>/dev/null | grep -q ocirepository; then
          echo "OCIRepository CRD is registered"
          OCI_REPOS=$($KUBECTL_CMD get ocirepository -A -o name 2>/dev/null || true)
          if [ -n "$OCI_REPOS" ]; then
            $KUBECTL_CMD get ocirepository -A -o wide
            echo ""
            echo "=== OCIRepository Details ==="
            $KUBECTL_CMD describe ocirepository -A
          else
            echo "OCIRepository CRD exists but no OCIRepository resources found"
          fi
        else
          echo "OCIRepository CRD not registered (Flux source-controller may not be installed)"
        fi
        echo ""

        echo "=== Flux Controllers Status ==="
        # Check for Flux controllers (source-controller, kustomize-controller, etc.)
        FLUX_CONTROLLERS=$($KUBECTL_CMD get pods -n flux-system -l app.kubernetes.io/part-of=flux -o name 2>/dev/null || true)
        if [ -n "$FLUX_CONTROLLERS" ]; then
          $KUBECTL_CMD get pods -n flux-system -l app.kubernetes.io/part-of=flux -o wide
          echo ""
          echo "=== Flux Controller Events ==="
          $KUBECTL_CMD get events -n flux-system --sort-by='.lastTimestamp' --field-selector involvedObject.kind=Pod | tail -30 || true
        else
          echo "No Flux controller pods found (FluxInstance may not have reconciled yet)"
        fi
        echo ""

        echo "=== ArgoCD Application Status ==="
        # Check if the CRD exists first (use kubectl directly for api-resources)
        if kubectl api-resources --api-group=argoproj.io 2>/dev/null | grep -q application; then
          echo "ArgoCD Application CRD is registered"
          ARGO_APPS=$($KUBECTL_CMD get application -A -o name 2>/dev/null || true)
          if [ -n "$ARGO_APPS" ]; then
            $KUBECTL_CMD get application -A -o wide
            echo ""
            echo "=== ArgoCD Application Details ==="
            $KUBECTL_CMD describe application -A
          else
            echo "ArgoCD Application CRD exists but no Application resources found"
          fi
        else
          echo "ArgoCD Application CRD not registered (ArgoCD may not be installed)"
        fi
        echo ""
