name: Cache Helm Charts
description: |
  Caches the Helm repository index and chart data to reduce external HTTP
  requests during CI, mitigating 429 rate-limit errors when many parallel
  system test jobs hit the same chart registries.

outputs:
  cache-hit:
    description: Whether the cache was found and restored
    value: ${{ steps.restore-cache.outputs.cache-hit || 'false' }}

runs:
  using: composite
  steps:
    - name: 📥 Restore Helm chart cache
      id: restore-cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ~/.cache/helm/repository
          ~/.config/helm/registry
        key: helm-cache-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('go.mod') }}
        restore-keys: |
          helm-cache-${{ runner.os }}-${{ runner.arch }}-
