// Package schemas contains the KSail JSON schema and its generator.
//
// The schema file (ksail-config.schema.json) is generated by gen_schema.go
// which reflects on the v1alpha1.Cluster type to produce a JSON Schema.
// Run `go generate ./schemas/...` to regenerate.
//
//go:generate go run gen_schema.go
package schemas
