source 'https://rubygems.org'

gem "jekyll", "~> 4.4.1"
gem "webrick", "~> 1.9"
gem "bigdecimal", "~> 4.0"

group :jekyll_plugins do
  gem "jekyll-gfm-admonitions", "~> 1.2.0"
  gem "jekyll-optional-front-matter", "~> 0.3.2"
  gem "jekyll-relative-links", "~> 0.7.0"
end

gem "just-the-docs", "~> 0.10.1"
