// Copyright (c) KSail contributors. All rights reserved.
// Licensed under the PolyForm Shield License 1.0.0. See LICENSE in the project root.

package docs

import (
	"fmt"
	"maps"
	"regexp"
	"slices"
	"strings"

	"github.com/devantler-tech/ksail/v7/pkg/cli/annotations"
	"github.com/devantler-tech/ksail/v7/pkg/toolgen"
	"github.com/spf13/cobra"
)

// AutoGenTag marks generated documentation pages so readers and tooling know
// not to edit them by hand.
const AutoGenTag = "{/* This page is auto-generated by go generate ./docs/... — DO NOT EDIT */}"

// partialAutoGenTag marks generated MDX partials imported by hand-written pages.
const partialAutoGenTag = "{/* This file is auto-generated by go generate ./docs/... — DO NOT EDIT */}"

const (
	helpCommandName       = "help"
	completionCommandName = "completion"
)

// CaptureHelp returns the rendered help text for a Cobra command.
func CaptureHelp(command *cobra.Command) string {
	var buf strings.Builder

	command.SetOut(&buf)
	command.SetErr(&buf)

	// Force help to be generated.
	_ = command.Help()

	return buf.String()
}

// SanitizeHelpText replaces user-specific home directory paths
// (e.g. "/Users/name/...") with "~" so generated pages are machine-independent.
func SanitizeHelpText(text string) string {
	return regexp.MustCompile(`"/(?:Users|home)/[^/]+/`).ReplaceAllString(text, `"~/`)
}

// RenderCLIIndexPage renders the generated cli-flags/index.mdx landing page:
// frontmatter, the sanitized root help output, and a Command Groups list
// derived from the visible top-level commands (one link per generated
// <name>-root page).
func RenderCLIIndexPage(root *cobra.Command) string {
	// Register the default help and completion commands so the captured help
	// output matches what the released binary prints.
	root.InitDefaultHelpCmd()
	root.InitDefaultCompletionCmd()

	var builder strings.Builder

	builder.WriteString("---\n")
	builder.WriteString("title: CLI Flags\n")
	builder.WriteString(
		"description: Complete CLI reference for all KSail commands and their flags.\n",
	)
	builder.WriteString("---\n\n")
	builder.WriteString(AutoGenTag)
	builder.WriteString("\n\n")
	builder.WriteString("KSail provides a comprehensive CLI for managing Kubernetes clusters and ")
	builder.WriteString("workloads. Below is the root command help output.\n\n")
	builder.WriteString("```text\n")
	builder.WriteString(SanitizeHelpText(CaptureHelp(root)))
	builder.WriteString("\n```\n\n")
	builder.WriteString("## Command Groups\n\n")
	builder.WriteString("Explore the CLI documentation for each command group:\n\n")

	for _, sub := range visibleCommandGroups(root) {
		fmt.Fprintf(&builder, "- **[ksail %s](/cli-flags/%s/%s-root/)** – %s\n",
			sub.Name(), sub.Name(), sub.Name(), sub.Short)
	}

	builder.WriteString("\nThe global `--config` flag selects an alternate configuration file — ")
	builder.WriteString("see [Multi-Environment Workflows](/guides/multi-environment/).\n")

	return builder.String()
}

// HiddenFromDocs reports whether c must be excluded from the generated
// documentation surface: Hidden commands (deprecated flat delegates,
// experimental-gated commands, and internal entrypoints such as steer-agent /
// operator) plus the cobra help and completion helpers — none of which get a
// generated page. Shared by the index/MCP renderers and the gen_docs walker so
// the two can never drift.
func HiddenFromDocs(c *cobra.Command) bool {
	return c.Hidden || c.Name() == helpCommandName || c.Name() == completionCommandName
}

// visibleCommandGroups returns root's visible top-level commands, excluding
// the help and completion helpers (which have no generated pages).
func visibleCommandGroups(root *cobra.Command) []*cobra.Command {
	var groups []*cobra.Command

	for _, sub := range root.Commands() {
		if HiddenFromDocs(sub) {
			continue
		}

		groups = append(groups, sub)
	}

	return groups
}

// RenderMCPToolsPartial renders the generated MDX partial documenting the MCP
// tool surface: the consolidated tool inventory, the excluded commands, and a
// per-tool subcommand table. It is imported by src/content/docs/mcp.mdx.
func RenderMCPToolsPartial(root *cobra.Command) string {
	tools := toolgen.GenerateTools(root, toolgen.DefaultOptions())
	slices.SortFunc(tools, func(left, right toolgen.ToolDefinition) int {
		return strings.Compare(left.Name, right.Name)
	})

	var builder strings.Builder

	builder.WriteString(partialAutoGenTag)
	builder.WriteString("\n\n")
	fmt.Fprintf(&builder, "The MCP server generates tools from the KSail command tree, "+
		"consolidating commands by permission level into **%d tools**:\n\n",
		len(tools))
	writeToolSummaryTable(&builder, tools)
	writeExcludedCommands(&builder, root)
	builder.WriteString("Each tool takes a **subcommand parameter** selecting the operation, ")
	builder.WriteString("plus the merged flags of its subcommands. Subcommands marked below ")
	builder.WriteString("also accept positional arguments via the `args` parameter.\n\n")

	for _, tool := range tools {
		writeToolSection(&builder, tool)
	}

	return strings.TrimRight(builder.String(), "\n") + "\n"
}

// writeToolSummaryTable renders the tool-inventory overview table.
func writeToolSummaryTable(builder *strings.Builder, tools []toolgen.ToolDefinition) {
	builder.WriteString("| Tool | Access | Description | Subcommand parameter |\n")
	builder.WriteString("| ---- | ------ | ----------- | -------------------- |\n")

	for _, tool := range tools {
		param := "–"
		if tool.SubcommandParam != "" {
			param = "`" + tool.SubcommandParam + "`"
		}

		fmt.Fprintf(builder,
			"| `%s` | %s | %s | %s |\n",
			tool.Name, accessLabel(tool), mdxTableCell(tool.Description), param)
	}

	builder.WriteString("\n")
}

// accessLabel returns the human-readable permission level for a tool.
func accessLabel(tool toolgen.ToolDefinition) string {
	if tool.RequiresPermission {
		return "Write"
	}

	return "Read-only"
}

// writeExcludedCommands renders the list of top-level commands that are not
// exposed as MCP tools (excluded via toolgen.DefaultOptions or the
// ai.toolgen.exclude annotation).
func writeExcludedCommands(builder *strings.Builder, root *cobra.Command) {
	builder.WriteString(
		"These commands are not exposed as tools " +
			"(interactive or long-running commands and shell helpers): ",
	)

	for index, name := range excludedCommandNames(root) {
		if index > 0 {
			builder.WriteString(", ")
		}

		builder.WriteString("`" + name + "`")
	}

	builder.WriteString(".\n\n")
}

// excludedCommandNames returns the sorted top-level command names excluded
// from tool generation.
func excludedCommandNames(root *cobra.Command) []string {
	excluded := map[string]bool{}

	for _, path := range toolgen.DefaultOptions().ExcludeCommands {
		// Strip the root command; the bare root entry has no name to list.
		rest, hasSubcommand := strings.CutPrefix(path, "ksail ")
		if !hasSubcommand {
			continue
		}

		excluded[strings.Fields(rest)[0]] = true
	}

	for _, sub := range root.Commands() {
		if sub.Annotations[annotations.AnnotationExclude] == "true" {
			excluded[sub.Name()] = true
		}
	}

	return slices.Sorted(maps.Keys(excluded))
}

// writeToolSection renders one tool's heading, summary line, and subcommand table.
func writeToolSection(builder *strings.Builder, tool toolgen.ToolDefinition) {
	builder.WriteString("### " + tool.Name + "\n\n")
	builder.WriteString(toolSummaryLine(tool))

	if !tool.IsConsolidated || len(tool.Subcommands) == 0 {
		return
	}

	builder.WriteString("| Subcommand | Description | Accepts `args` |\n")
	builder.WriteString("| ---------- | ----------- | -------------- |\n")

	for _, name := range slices.Sorted(maps.Keys(tool.Subcommands)) {
		sub := tool.Subcommands[name]

		acceptsArgs := "No"
		if sub.AcceptsArgs {
			acceptsArgs = "Yes"
		}

		fmt.Fprintf(builder,
			"| `%s` | %s | %s |\n",
			name, mdxTableCell(sub.Description), acceptsArgs)
	}

	builder.WriteString("\n")
}

// toolSummaryLine builds the sentence describing a tool's origin and selector.
func toolSummaryLine(tool toolgen.ToolDefinition) string {
	access := "write"
	if !tool.RequiresPermission {
		access = "read-only"
	}

	line := fmt.Sprintf(
		"%s — %s subcommands of `%s`.",
		mdxTableCell(tool.Description), access, tool.CommandPath,
	)

	if tool.IsConsolidated && tool.SubcommandParam != "" {
		line += fmt.Sprintf(" Select the operation via the `%s` parameter.", tool.SubcommandParam)
	}

	return line + "\n\n"
}
