package kubeadmbootstrap_test

import (
	"errors"
	"io"
	"strings"
	"testing"

	kubeadmbootstrap "github.com/devantler-tech/ksail/v7/pkg/svc/bootstrap/kubeadm"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

// validCACertHash is a full SHA-256 CA pin (64 hex chars), the form kubeadm's
// token discovery requires, used as a valid fixture.
const validCACertHash = "sha256:" +
	"0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"

// parsedInit mirrors the InitConfiguration subset Render emits.
type parsedInit struct {
	APIVersion      string `yaml:"apiVersion"`
	Kind            string `yaml:"kind"`
	BootstrapTokens []struct {
		Token string `yaml:"token"`
	} `yaml:"bootstrapTokens"`
}

// parsedCluster mirrors the ClusterConfiguration subset Render emits.
type parsedCluster struct {
	APIVersion           string `yaml:"apiVersion"`
	Kind                 string `yaml:"kind"`
	KubernetesVersion    string `yaml:"kubernetesVersion"`
	ControlPlaneEndpoint string `yaml:"controlPlaneEndpoint"`
	Networking           *struct {
		PodSubnet     string `yaml:"podSubnet"`
		ServiceSubnet string `yaml:"serviceSubnet"`
	} `yaml:"networking"`
	APIServer *struct {
		CertSANs []string `yaml:"certSANs"` //nolint:tagliatelle // kubeadm's schema mandates the key "certSANs".
	} `yaml:"apiServer"`
}

// parsedJoin mirrors the JoinConfiguration subset Render emits.
type parsedJoin struct {
	APIVersion string `yaml:"apiVersion"`
	Kind       string `yaml:"kind"`
	Discovery  struct {
		BootstrapToken struct {
			APIServerEndpoint string   `yaml:"apiServerEndpoint"`
			Token             string   `yaml:"token"`
			CACertHashes      []string `yaml:"caCertHashes"`
		} `yaml:"bootstrapToken"`
	} `yaml:"discovery"`
	ControlPlane *struct{} `yaml:"controlPlane"`
}

// decodeDocs asserts the stream carries the managed-file header and decodes its
// YAML documents into nodes, so tests assert on parsed documents rather than on
// brittle substrings.
func decodeDocs(t *testing.T, stream string) []yaml.Node {
	t.Helper()

	require.True(t,
		strings.HasPrefix(stream, "# Generated by ksail — kubeadm"),
		"stream must begin with the managed-file header",
	)

	decoder := yaml.NewDecoder(strings.NewReader(stream))

	var nodes []yaml.Node

	for {
		var node yaml.Node

		err := decoder.Decode(&node)
		if errors.Is(err, io.EOF) {
			break
		}

		require.NoError(t, err, "every document must be valid YAML")

		nodes = append(nodes, node)
	}

	return nodes
}

func TestRenderServerInit(t *testing.T) {
	t.Parallel()

	stream, err := kubeadmbootstrap.Render(kubeadmbootstrap.NodeConfig{
		Role:                 kubeadmbootstrap.RoleServerInit,
		Token:                "abcdef.0123456789abcdef",
		KubernetesVersion:    "v1.31.0",
		ControlPlaneEndpoint: "k8s.example.com:6443",
		CertSANs:             []string{"k8s.example.com"},
		PodSubnet:            "10.244.0.0/16",
		ServiceSubnet:        "10.96.0.0/12",
	})
	require.NoError(t, err)

	docs := decodeDocs(t, stream)
	require.Len(t, docs, 2, "the initialising control plane renders Init + Cluster configurations")

	var initCfg parsedInit

	require.NoError(t, docs[0].Decode(&initCfg))
	assert.Equal(t, "kubeadm.k8s.io/v1beta4", initCfg.APIVersion)
	assert.Equal(t, "InitConfiguration", initCfg.Kind)
	require.Len(t, initCfg.BootstrapTokens, 1)
	assert.Equal(t, "abcdef.0123456789abcdef", initCfg.BootstrapTokens[0].Token)

	var clusterCfg parsedCluster

	require.NoError(t, docs[1].Decode(&clusterCfg))
	assert.Equal(t, "ClusterConfiguration", clusterCfg.Kind)
	assert.Equal(t, "v1.31.0", clusterCfg.KubernetesVersion)
	assert.Equal(t, "k8s.example.com:6443", clusterCfg.ControlPlaneEndpoint)
	require.NotNil(t, clusterCfg.Networking)
	assert.Equal(t, "10.244.0.0/16", clusterCfg.Networking.PodSubnet)
	assert.Equal(t, "10.96.0.0/12", clusterCfg.Networking.ServiceSubnet)
	require.NotNil(t, clusterCfg.APIServer)
	assert.Equal(t, []string{"k8s.example.com"}, clusterCfg.APIServer.CertSANs)
}

func TestRenderServerInitMinimalOmitsEmptyClusterKeys(t *testing.T) {
	t.Parallel()

	stream, err := kubeadmbootstrap.Render(kubeadmbootstrap.NodeConfig{
		Role:  kubeadmbootstrap.RoleServerInit,
		Token: "abcdef.0123456789abcdef",
	})
	require.NoError(t, err)

	docs := decodeDocs(t, stream)
	require.Len(t, docs, 2)

	var clusterCfg parsedCluster

	require.NoError(t, docs[1].Decode(&clusterCfg))
	assert.Equal(t, "ClusterConfiguration", clusterCfg.Kind)
	assert.Empty(t, clusterCfg.KubernetesVersion, "kubernetes version is omitted when unset")
	assert.Nil(t, clusterCfg.Networking, "the networking block is omitted when no subnet is set")
	assert.Nil(t, clusterCfg.APIServer, "the apiServer block is omitted when no cert SAN is set")
}

func TestRenderServerJoinsAsControlPlane(t *testing.T) {
	t.Parallel()

	stream, err := kubeadmbootstrap.Render(kubeadmbootstrap.NodeConfig{
		Role:              kubeadmbootstrap.RoleServer,
		Token:             "abcdef.0123456789abcdef",
		APIServerEndpoint: "10.0.0.1:6443",
		CACertHashes:      []string{validCACertHash},
	})
	require.NoError(t, err)

	docs := decodeDocs(t, stream)
	require.Len(t, docs, 1, "a joining node renders a single JoinConfiguration")

	var joinCfg parsedJoin

	require.NoError(t, docs[0].Decode(&joinCfg))
	assert.Equal(t, "JoinConfiguration", joinCfg.Kind)
	assert.Equal(t, "10.0.0.1:6443", joinCfg.Discovery.BootstrapToken.APIServerEndpoint)
	assert.Equal(t, "abcdef.0123456789abcdef", joinCfg.Discovery.BootstrapToken.Token)
	assert.Equal(t, []string{validCACertHash}, joinCfg.Discovery.BootstrapToken.CACertHashes)
	assert.NotNil(t, joinCfg.ControlPlane, "an additional server joins as a control plane")
}

func TestRenderAgentJoinsAsWorker(t *testing.T) {
	t.Parallel()

	stream, err := kubeadmbootstrap.Render(kubeadmbootstrap.NodeConfig{
		Role:              kubeadmbootstrap.RoleAgent,
		Token:             "abcdef.0123456789abcdef",
		APIServerEndpoint: "10.0.0.1:6443",
		CACertHashes:      []string{validCACertHash},
	})
	require.NoError(t, err)

	docs := decodeDocs(t, stream)
	require.Len(t, docs, 1)

	var joinCfg parsedJoin

	require.NoError(t, docs[0].Decode(&joinCfg))
	assert.Equal(t, "JoinConfiguration", joinCfg.Kind)
	assert.Equal(t, "10.0.0.1:6443", joinCfg.Discovery.BootstrapToken.APIServerEndpoint)
	assert.Nil(t, joinCfg.ControlPlane, "a worker joins with no control-plane block")
}

func TestRenderSortsAndDropsEmptyListEntries(t *testing.T) {
	t.Parallel()

	stream, err := kubeadmbootstrap.Render(kubeadmbootstrap.NodeConfig{
		Role:     kubeadmbootstrap.RoleServerInit,
		Token:    "abcdef.0123456789abcdef",
		CertSANs: []string{"z.example.com", "", "a.example.com"},
	})
	require.NoError(t, err)

	docs := decodeDocs(t, stream)
	require.Len(t, docs, 2)

	var clusterCfg parsedCluster

	require.NoError(t, docs[1].Decode(&clusterCfg))
	require.NotNil(t, clusterCfg.APIServer)
	assert.Equal(t, []string{"a.example.com", "z.example.com"}, clusterCfg.APIServer.CertSANs,
		"cert SANs are sorted and empty entries dropped for deterministic output")
}

func TestRenderJoinSortsCACertHashes(t *testing.T) {
	t.Parallel()

	hashA := "sha256:" + strings.Repeat("a", 64)
	hashB := "sha256:" + strings.Repeat("b", 64)

	stream, err := kubeadmbootstrap.Render(kubeadmbootstrap.NodeConfig{
		Role:              kubeadmbootstrap.RoleAgent,
		Token:             "abcdef.0123456789abcdef",
		APIServerEndpoint: "10.0.0.1:6443",
		CACertHashes:      []string{hashB, hashA},
	})
	require.NoError(t, err)

	docs := decodeDocs(t, stream)

	var joinCfg parsedJoin

	require.NoError(t, docs[0].Decode(&joinCfg))

	want := []string{hashA, hashB}
	assert.Equal(t, want, joinCfg.Discovery.BootstrapToken.CACertHashes,
		"CA cert hashes are sorted for deterministic output")
}

//nolint:funlen // table-driven test enumerating the validation cases.
func TestRenderRejectsInvalidConfigs(t *testing.T) {
	t.Parallel()

	cases := map[string]struct {
		cfg     kubeadmbootstrap.NodeConfig
		wantErr error
	}{
		"invalid role": {
			cfg:     kubeadmbootstrap.NodeConfig{Role: "bootstrapper", Token: "t"},
			wantErr: kubeadmbootstrap.ErrInvalidRole,
		},
		"missing token": {
			cfg:     kubeadmbootstrap.NodeConfig{Role: kubeadmbootstrap.RoleServerInit},
			wantErr: kubeadmbootstrap.ErrMissingToken,
		},
		"server-init with join fields": {
			cfg: kubeadmbootstrap.NodeConfig{
				Role:              kubeadmbootstrap.RoleServerInit,
				Token:             "t",
				APIServerEndpoint: "10.0.0.1:6443",
			},
			wantErr: kubeadmbootstrap.ErrServerInitWithJoinFields,
		},
		"join missing endpoint": {
			cfg: kubeadmbootstrap.NodeConfig{
				Role:         kubeadmbootstrap.RoleAgent,
				Token:        "t",
				CACertHashes: []string{validCACertHash},
			},
			wantErr: kubeadmbootstrap.ErrMissingAPIServerEndpoint,
		},
		"join invalid endpoint (no port)": {
			cfg: kubeadmbootstrap.NodeConfig{
				Role:              kubeadmbootstrap.RoleAgent,
				Token:             "t",
				APIServerEndpoint: "10.0.0.1",
				CACertHashes:      []string{validCACertHash},
			},
			wantErr: kubeadmbootstrap.ErrInvalidAPIServerEndpoint,
		},
		"join invalid endpoint (non-numeric port)": {
			cfg: kubeadmbootstrap.NodeConfig{
				Role:              kubeadmbootstrap.RoleAgent,
				Token:             "t",
				APIServerEndpoint: "10.0.0.1:https",
				CACertHashes:      []string{validCACertHash},
			},
			wantErr: kubeadmbootstrap.ErrInvalidAPIServerEndpoint,
		},
		"join missing CA hashes": {
			cfg: kubeadmbootstrap.NodeConfig{
				Role:              kubeadmbootstrap.RoleServer,
				Token:             "t",
				APIServerEndpoint: "10.0.0.1:6443",
			},
			wantErr: kubeadmbootstrap.ErrMissingCACertHashes,
		},
		"join invalid CA hash (no prefix)": {
			cfg: kubeadmbootstrap.NodeConfig{
				Role:              kubeadmbootstrap.RoleServer,
				Token:             "t",
				APIServerEndpoint: "10.0.0.1:6443",
				CACertHashes:      []string{"deadbeef"},
			},
			wantErr: kubeadmbootstrap.ErrInvalidCACertHash,
		},
		"join invalid CA hash (non-hex digest)": {
			cfg: kubeadmbootstrap.NodeConfig{
				Role:              kubeadmbootstrap.RoleServer,
				Token:             "t",
				APIServerEndpoint: "10.0.0.1:6443",
				CACertHashes:      []string{"sha256:" + strings.Repeat("z", 64)},
			},
			wantErr: kubeadmbootstrap.ErrInvalidCACertHash,
		},
		"join invalid CA hash (too short)": {
			cfg: kubeadmbootstrap.NodeConfig{
				Role:              kubeadmbootstrap.RoleServer,
				Token:             "t",
				APIServerEndpoint: "10.0.0.1:6443",
				CACertHashes:      []string{"sha256:deadbeef"},
			},
			wantErr: kubeadmbootstrap.ErrInvalidCACertHash,
		},
		"join with cluster-wide option": {
			cfg: kubeadmbootstrap.NodeConfig{
				Role:              kubeadmbootstrap.RoleAgent,
				Token:             "t",
				APIServerEndpoint: "10.0.0.1:6443",
				CACertHashes:      []string{validCACertHash},
				PodSubnet:         "10.244.0.0/16",
			},
			wantErr: kubeadmbootstrap.ErrServerInitOnlyOption,
		},
	}

	for name, testCase := range cases {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			_, err := kubeadmbootstrap.Render(testCase.cfg)
			require.ErrorIs(t, err, testCase.wantErr)
		})
	}
}
