package kubeadmbootstrap

import (
	"fmt"
	"net"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

// header is prepended to every rendered config so an operator inspecting a node
// can see the file is ksail-managed rather than hand-written.
const header = "# Generated by ksail — kubeadm node configuration. Do not edit.\n"

// apiVersion is the kubeadm config schema this package emits. v1beta4 is the
// current GA schema (Kubernetes 1.31+).
const apiVersion = "kubeadm.k8s.io/v1beta4"

// caCertHashPrefix is the only hash algorithm kubeadm's token discovery accepts.
const caCertHashPrefix = "sha256:"

// caCertHashHexLen is the number of hex characters in a full SHA-256 digest
// (32 bytes). kubeadm rejects a discovery hash that is not a full digest, so a
// shorter (or longer) hex string is caught here at render time rather than at
// join time.
const caCertHashHexLen = 64

// Role is a kubeadm node's role within the cluster. It selects the shape of the
// rendered config: an Init/Cluster configuration that starts a cluster, or a
// Join configuration (with or without a control-plane block) that joins one.
type Role string

const (
	// RoleServerInit is the first control-plane node, which initialises a new
	// cluster (rendered as InitConfiguration + ClusterConfiguration) and joins no
	// existing control plane.
	RoleServerInit Role = "server-init"
	// RoleServer is an additional control-plane node that joins the cluster the
	// RoleServerInit node started, via its APIServerEndpoint (rendered as a
	// JoinConfiguration carrying a controlPlane block).
	RoleServer Role = "server"
	// RoleAgent is a worker node that joins the cluster via its APIServerEndpoint
	// and runs no control-plane components (rendered as a JoinConfiguration with no
	// controlPlane block).
	RoleAgent Role = "agent"
)

// NodeConfig is the typed input for [Render]: everything needed to render one
// kubeadm node's bring-up configuration. It performs no I/O. The role vocabulary
// (server-init/server/agent) is shared with the k3sbootstrap renderer so a
// provisioner can dispatch either distribution from one node-topology plan.
type NodeConfig struct {
	// Role is the node's role in the cluster (required). It governs which other
	// fields are valid — see the per-field notes and the package's sentinel errors.
	Role Role
	// Token is the shared bootstrap token used to issue (on the initialising
	// control plane) or redeem (on a joining node) the join credential (required
	// for all roles).
	Token string

	// KubernetesVersion pins the control-plane image set (e.g. "v1.31.0"). Optional
	// and cluster-wide: valid only for RoleServerInit; kubeadm picks a default when
	// empty.
	KubernetesVersion string
	// ControlPlaneEndpoint is the stable "host:port" the cluster advertises for its
	// API server (e.g. a load balancer or floating IP), enabling later
	// control-plane nodes to join. Optional and cluster-wide: valid only for
	// RoleServerInit.
	ControlPlaneEndpoint string
	// CertSANs are extra Subject Alternative Names added to the API server
	// certificate. Cluster-wide: valid only for RoleServerInit. Rendered in sorted
	// order for determinism.
	CertSANs []string
	// PodSubnet is the pod network CIDR. Cluster-wide: valid only for
	// RoleServerInit.
	PodSubnet string
	// ServiceSubnet is the service network CIDR. Cluster-wide: valid only for
	// RoleServerInit.
	ServiceSubnet string

	// APIServerEndpoint is the "host:port" of an existing control plane a joining
	// node registers against. Required for RoleServer and RoleAgent; must be empty
	// for RoleServerInit (which starts the cluster).
	APIServerEndpoint string
	// CACertHashes are the pinned "sha256:<hex>" cluster-CA hashes a joining node
	// verifies during token discovery. Required (at least one) for RoleServer and
	// RoleAgent; must be empty for RoleServerInit. Rendered in sorted order for
	// determinism.
	CACertHashes []string
}

// bootstrapToken is one entry of an InitConfiguration's bootstrapTokens list.
type bootstrapToken struct {
	Token string `yaml:"token"`
}

// initConfiguration is the subset of kubeadm's InitConfiguration this package
// emits for the cluster-initialising control plane.
type initConfiguration struct {
	APIVersion      string           `yaml:"apiVersion"`
	Kind            string           `yaml:"kind"`
	BootstrapTokens []bootstrapToken `yaml:"bootstrapTokens"`
}

// networking is the subset of ClusterConfiguration.networking this package emits.
type networking struct {
	PodSubnet     string `yaml:"podSubnet,omitempty"`
	ServiceSubnet string `yaml:"serviceSubnet,omitempty"`
}

// apiServerConfig is the subset of ClusterConfiguration.apiServer this package
// emits.
type apiServerConfig struct {
	//nolint:tagliatelle // kubeadm's schema mandates the key "certSANs".
	CertSANs []string `yaml:"certSANs,omitempty"`
}

// clusterConfiguration is the subset of kubeadm's ClusterConfiguration this
// package emits. omitempty keeps the document to exactly the keys the caller set.
type clusterConfiguration struct {
	APIVersion           string           `yaml:"apiVersion"`
	Kind                 string           `yaml:"kind"`
	KubernetesVersion    string           `yaml:"kubernetesVersion,omitempty"`
	ControlPlaneEndpoint string           `yaml:"controlPlaneEndpoint,omitempty"`
	Networking           *networking      `yaml:"networking,omitempty"`
	APIServer            *apiServerConfig `yaml:"apiServer,omitempty"`
}

// bootstrapTokenDiscovery is the token-discovery block of a JoinConfiguration.
type bootstrapTokenDiscovery struct {
	APIServerEndpoint string   `yaml:"apiServerEndpoint"`
	Token             string   `yaml:"token"`
	CACertHashes      []string `yaml:"caCertHashes"`
}

// discovery wraps the token-discovery block kubeadm uses to find and
// authenticate the cluster.
type discovery struct {
	BootstrapToken bootstrapTokenDiscovery `yaml:"bootstrapToken"`
}

// joinConfiguration is the subset of kubeadm's JoinConfiguration this package
// emits. A non-nil ControlPlane (an empty block) marks a control-plane join;
// its absence marks a worker join.
type joinConfiguration struct {
	APIVersion   string        `yaml:"apiVersion"`
	Kind         string        `yaml:"kind"`
	Discovery    discovery     `yaml:"discovery"`
	ControlPlane *controlPlane `yaml:"controlPlane,omitempty"`
}

// controlPlane is the marker block whose presence tells kubeadm to join as a
// control plane. It is intentionally empty: kubeadm fills the local API endpoint
// defaults, and this slice does not yet surface per-node overrides.
type controlPlane struct{}

// Render maps cfg to the kubeadm config document(s) for that node: an
// InitConfiguration + ClusterConfiguration pair for the cluster-initialising
// control plane, or a single JoinConfiguration for a joining node. The returned
// string is a complete YAML stream (prefixed with a managed-file header,
// multiple documents separated by "---") suitable for delivery via cloud-init
// write_files.
//
// Render is pure and never returns a partially-valid document: any configuration
// error (see the package's sentinel errors) is reported instead. Because the
// output is YAML rather than a shell command, values are encoded by the YAML
// marshaller and carry no shell-quoting or injection surface.
func Render(cfg NodeConfig) (string, error) {
	err := cfg.validate()
	if err != nil {
		return "", err
	}

	if cfg.Role == RoleServerInit {
		return renderInit(cfg)
	}

	return renderJoin(cfg)
}

// renderInit renders the InitConfiguration + ClusterConfiguration pair for the
// cluster-initialising control plane.
func renderInit(cfg NodeConfig) (string, error) {
	initCfg := initConfiguration{
		APIVersion:      apiVersion,
		Kind:            "InitConfiguration",
		BootstrapTokens: []bootstrapToken{{Token: cfg.Token}},
	}

	clusterCfg := clusterConfiguration{
		APIVersion:           apiVersion,
		Kind:                 "ClusterConfiguration",
		KubernetesVersion:    cfg.KubernetesVersion,
		ControlPlaneEndpoint: cfg.ControlPlaneEndpoint,
		Networking:           newNetworking(cfg.PodSubnet, cfg.ServiceSubnet),
		APIServer:            newAPIServerConfig(cfg.CertSANs),
	}

	return marshalDocuments(initCfg, clusterCfg)
}

// renderJoin renders the JoinConfiguration for a joining control-plane or worker
// node.
func renderJoin(cfg NodeConfig) (string, error) {
	joinCfg := joinConfiguration{
		APIVersion: apiVersion,
		Kind:       "JoinConfiguration",
		Discovery: discovery{
			BootstrapToken: bootstrapTokenDiscovery{
				APIServerEndpoint: cfg.APIServerEndpoint,
				Token:             cfg.Token,
				CACertHashes:      sortedCopy(cfg.CACertHashes),
			},
		},
	}

	if cfg.Role == RoleServer {
		joinCfg.ControlPlane = &controlPlane{}
	}

	return marshalDocuments(joinCfg)
}

// newNetworking returns a *networking when either subnet is set, or nil so the
// networking key is omitted entirely.
func newNetworking(podSubnet, serviceSubnet string) *networking {
	if podSubnet == "" && serviceSubnet == "" {
		return nil
	}

	return &networking{PodSubnet: podSubnet, ServiceSubnet: serviceSubnet}
}

// newAPIServerConfig returns an *apiServerConfig when any cert SAN is set, or nil
// so the apiServer key is omitted entirely.
func newAPIServerConfig(certSANs []string) *apiServerConfig {
	sans := sortedCopy(certSANs)
	if len(sans) == 0 {
		return nil
	}

	return &apiServerConfig{CertSANs: sans}
}

// marshalDocuments encodes each document to YAML and joins them into a single
// header-prefixed, "---"-separated stream.
func marshalDocuments(docs ...any) (string, error) {
	var builder strings.Builder

	builder.WriteString(header)

	for index, doc := range docs {
		if index > 0 {
			builder.WriteString("---\n")
		}

		out, err := yaml.Marshal(doc)
		if err != nil {
			// Unreachable in practice: every document is a fixed struct of strings and
			// string slices, which yaml.Marshal cannot fail to encode. Surfaced rather
			// than dropped so a future schema change that breaks this is not silently
			// ignored.
			return "", fmt.Errorf("marshalling kubeadm config: %w", err)
		}

		builder.Write(out)
	}

	return builder.String(), nil
}

// validate enforces the per-role rules before rendering: a token is always
// required; the cluster-initialising control plane joins nothing while the other
// roles must name a valid endpoint and at least one CA pin; and a joining node
// may not carry cluster-wide options.
func (cfg NodeConfig) validate() error {
	if !cfg.Role.valid() {
		return ErrInvalidRole
	}

	if cfg.Token == "" {
		return ErrMissingToken
	}

	if cfg.Role == RoleServerInit {
		return cfg.validateServerInit()
	}

	return cfg.validateJoin()
}

// valid reports whether r is one of the three recognised node roles.
func (r Role) valid() bool {
	switch r {
	case RoleServerInit, RoleServer, RoleAgent:
		return true
	default:
		return false
	}
}

// validateServerInit rejects join-only fields on the cluster-initialising
// control plane, which starts a cluster rather than joining one.
func (cfg NodeConfig) validateServerInit() error {
	if cfg.APIServerEndpoint != "" || len(cfg.CACertHashes) > 0 {
		return ErrServerInitWithJoinFields
	}

	return nil
}

// validateJoin requires a joining node to name a well-formed control-plane
// endpoint and at least one valid CA pin, and rejects cluster-wide options that
// have no effect on a joining node.
func (cfg NodeConfig) validateJoin() error {
	if cfg.hasServerInitOnlyOptions() {
		return ErrServerInitOnlyOption
	}

	err := validateAPIServerEndpoint(cfg.APIServerEndpoint)
	if err != nil {
		return err
	}

	return validateCACertHashes(cfg.CACertHashes)
}

// hasServerInitOnlyOptions reports whether cfg carries any cluster-wide option,
// none of which a joining node may set.
func (cfg NodeConfig) hasServerInitOnlyOptions() bool {
	return cfg.KubernetesVersion != "" ||
		cfg.ControlPlaneEndpoint != "" ||
		len(cfg.CertSANs) > 0 ||
		cfg.PodSubnet != "" ||
		cfg.ServiceSubnet != ""
}

// validateAPIServerEndpoint requires a joining node's endpoint to be a host:port
// with a non-empty host and a numeric port, so a node is never rendered with an
// endpoint it could not dial.
func validateAPIServerEndpoint(endpoint string) error {
	if endpoint == "" {
		return ErrMissingAPIServerEndpoint
	}

	host, port, err := net.SplitHostPort(endpoint)
	if err != nil || host == "" {
		return ErrInvalidAPIServerEndpoint
	}

	portNum, err := strconv.Atoi(port)
	if err != nil || portNum < 1 || portNum > 65535 {
		return ErrInvalidAPIServerEndpoint
	}

	return nil
}

// validateCACertHashes requires at least one pin and rejects any that is not in
// the "sha256:<hex>" form kubeadm's token discovery expects.
func validateCACertHashes(hashes []string) error {
	pins := sortedCopy(hashes)
	if len(pins) == 0 {
		return ErrMissingCACertHashes
	}

	for _, pin := range pins {
		if !validCACertHash(pin) {
			return ErrInvalidCACertHash
		}
	}

	return nil
}

// validCACertHash reports whether pin is a "sha256:" prefix followed by a full
// 64-character lowercase-hex SHA-256 digest. A shorter hex string (e.g.
// "sha256:deadbeef") is rejected: kubeadm requires a full digest, so accepting a
// truncated one would render a config it fails to join with.
func validCACertHash(pin string) bool {
	digest, found := strings.CutPrefix(pin, caCertHashPrefix)
	if !found || len(digest) != caCertHashHexLen {
		return false
	}

	for _, char := range digest {
		isHex := (char >= '0' && char <= '9') || (char >= 'a' && char <= 'f')
		if !isHex {
			return false
		}
	}

	return true
}

// sortedCopy returns a sorted copy of values with empty entries dropped, so the
// rendered list is deterministic and free of blank items. It never mutates the
// caller's slice and returns nil for an all-empty input so the key is omitted.
func sortedCopy(values []string) []string {
	out := make([]string, 0, len(values))

	for _, value := range values {
		if value != "" {
			out = append(out, value)
		}
	}

	if len(out) == 0 {
		return nil
	}

	sort.Strings(out)

	return out
}
