package kubeadmbootstrap_test

import (
	"testing"

	kubeadmbootstrap "github.com/devantler-tech/ksail/v7/pkg/svc/bootstrap/kubeadm"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// sampleConfig is a stand-in for a rendered kubeadm config document. RenderInstall
// treats it as opaque bytes it drops on the node, so its exact contents are
// irrelevant — only that it is non-empty and carried through verbatim.
const sampleConfig = "# Generated by ksail — kubeadm node configuration. Do not edit.\n" +
	"apiVersion: kubeadm.k8s.io/v1beta4\nkind: InitConfiguration\n"

func TestRenderInstallServerInitRepository(t *testing.T) {
	t.Parallel()

	install, err := kubeadmbootstrap.RenderInstall(kubeadmbootstrap.InstallConfig{
		KubernetesVersion: "v1.31.0",
		Role:              kubeadmbootstrap.RoleServerInit,
		Config:            sampleConfig,
	})
	require.NoError(t, err)

	require.Len(t, install.AptSources, 1)
	source := install.AptSources[0]
	assert.Equal(t, "kubernetes", source.Name)
	assert.Equal(t,
		"deb [signed-by=$KEY_FILE] "+
			"https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /",
		source.Source,
		"the deb line points at the version's minor track and is scoped to the embedded key",
	)
	assert.Contains(t,
		source.Key,
		"-----BEGIN PGP PUBLIC KEY BLOCK-----",
		"the signing key is the embedded, ASCII-armored community key trusted declaratively",
	)
	assert.NotContains(t,
		source.Key,
		"Release.key",
		"the key is embedded material, never a URL fetched at runtime",
	)
}

func TestRenderInstallPackages(t *testing.T) {
	t.Parallel()

	install, err := kubeadmbootstrap.RenderInstall(kubeadmbootstrap.InstallConfig{
		KubernetesVersion: "v1.31.0",
		Role:              kubeadmbootstrap.RoleServerInit,
		Config:            sampleConfig,
	})
	require.NoError(t, err)

	assert.Equal(t,
		[]string{"containerd", "kubelet", "kubeadm", "kubectl"},
		install.Packages,
		"the container runtime installs before the kube* components, in a deterministic order",
	)
}

func TestRenderInstallDropsConfig(t *testing.T) {
	t.Parallel()

	install, err := kubeadmbootstrap.RenderInstall(kubeadmbootstrap.InstallConfig{
		KubernetesVersion: "v1.31.0",
		Role:              kubeadmbootstrap.RoleServerInit,
		Config:            sampleConfig,
	})
	require.NoError(t, err)

	require.Len(t, install.Files, 1)
	file := install.Files[0]
	assert.Equal(t, kubeadmbootstrap.ConfigPath, file.Path)
	assert.Equal(t, "0600", file.Permissions, "the config carries the token, so it is root-only")
	assert.Equal(t, sampleConfig, file.Content, "the rendered config is carried verbatim")
}

func TestRenderInstallServerInitBootstrapsWithInit(t *testing.T) {
	t.Parallel()

	install, err := kubeadmbootstrap.RenderInstall(kubeadmbootstrap.InstallConfig{
		KubernetesVersion: "v1.31.0",
		Role:              kubeadmbootstrap.RoleServerInit,
		Config:            sampleConfig,
	})
	require.NoError(t, err)

	assert.Equal(t, []string{
		"systemctl enable --now containerd",
		"apt-mark hold kubelet kubeadm kubectl",
		"kubeadm init --config " + kubeadmbootstrap.ConfigPath +
			" && mkdir -p /var/lib/ksail && touch " + kubeadmbootstrap.BootstrapSentinelPath,
	}, install.Commands)
}

func TestRenderInstallJoiningNodesBootstrapWithJoin(t *testing.T) {
	t.Parallel()

	for _, role := range []kubeadmbootstrap.Role{
		kubeadmbootstrap.RoleServer,
		kubeadmbootstrap.RoleAgent,
	} {
		install, err := kubeadmbootstrap.RenderInstall(kubeadmbootstrap.InstallConfig{
			KubernetesVersion: "v1.31.0",
			Role:              role,
			Config:            sampleConfig,
		})
		require.NoError(t, err, "role %q", role)

		require.NotEmpty(t, install.Commands)
		assert.Equal(t,
			"kubeadm join --config "+kubeadmbootstrap.ConfigPath+
				" && mkdir -p /var/lib/ksail && touch "+kubeadmbootstrap.BootstrapSentinelPath,
			install.Commands[len(install.Commands)-1],
			"a joining node (%q) runs `kubeadm join`, not `kubeadm init`, and chains "+
				"the completion sentinel so it appears only on success",
			role,
		)
	}
}

func TestRenderInstallMinorTrack(t *testing.T) {
	t.Parallel()

	for version, wantTrack := range map[string]string{
		"v1.31.0": "v1.31",
		"v1.30":   "v1.30", // no patch component
		"v1.33.7": "v1.33",
		"v2.0.0":  "v2.0",
	} {
		install, err := kubeadmbootstrap.RenderInstall(kubeadmbootstrap.InstallConfig{
			KubernetesVersion: version,
			Role:              kubeadmbootstrap.RoleServerInit,
			Config:            sampleConfig,
		})
		require.NoError(t, err, "version %q", version)

		wantSource := "deb [signed-by=$KEY_FILE] " +
			"https://pkgs.k8s.io/core:/stable:/" + wantTrack + "/deb/ /"
		assert.Equal(t, wantSource, install.AptSources[0].Source, "version %q track", version)
	}
}

// installErrorCase pairs a rejected InstallConfig with the sentinel RenderInstall
// must report for it.
type installErrorCase struct {
	cfg     kubeadmbootstrap.InstallConfig
	wantErr error
}

// installErrorCases enumerates every RenderInstall rejection: a valid config with
// exactly one field made invalid, mapped to the sentinel it must surface. Kept out
// of the test body so the table's size does not inflate the test's length.
func installErrorCases() map[string]installErrorCase {
	initRole := kubeadmbootstrap.RoleServerInit
	withVersion := func(v string) kubeadmbootstrap.InstallConfig {
		return kubeadmbootstrap.InstallConfig{
			KubernetesVersion: v,
			Role:              initRole,
			Config:            sampleConfig,
		}
	}
	invalidVersion := kubeadmbootstrap.ErrInvalidKubernetesVersion

	return map[string]installErrorCase{
		"missing version": {
			cfg:     kubeadmbootstrap.InstallConfig{Role: initRole, Config: sampleConfig},
			wantErr: kubeadmbootstrap.ErrMissingKubernetesVersion,
		},
		"version without v prefix":        {cfg: withVersion("1.31.0"), wantErr: invalidVersion},
		"version with too few components": {cfg: withVersion("v1"), wantErr: invalidVersion},
		"version with non-numeric major":  {cfg: withVersion("vx.31"), wantErr: invalidVersion},
		"version with non-numeric minor":  {cfg: withVersion("v1.beta"), wantErr: invalidVersion},
		"version with empty minor":        {cfg: withVersion("v1."), wantErr: invalidVersion},
		"invalid role": {
			cfg: kubeadmbootstrap.InstallConfig{
				KubernetesVersion: "v1.31.0",
				Role:              kubeadmbootstrap.Role("worker"),
				Config:            sampleConfig,
			},
			wantErr: kubeadmbootstrap.ErrInvalidRole,
		},
		"missing config": {
			cfg:     kubeadmbootstrap.InstallConfig{KubernetesVersion: "v1.31.0", Role: initRole},
			wantErr: kubeadmbootstrap.ErrMissingConfig,
		},
	}
}

func TestRenderInstallErrors(t *testing.T) {
	t.Parallel()

	for name, testCase := range installErrorCases() {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			install, err := kubeadmbootstrap.RenderInstall(testCase.cfg)
			require.ErrorIs(t, err, testCase.wantErr)
			assert.Equal(
				t,
				kubeadmbootstrap.Install{},
				install,
				"a rejected config renders no partial install",
			)
		})
	}
}

func TestRenderInstallIsDeterministic(t *testing.T) {
	t.Parallel()

	cfg := kubeadmbootstrap.InstallConfig{
		KubernetesVersion: "v1.31.0",
		Role:              kubeadmbootstrap.RoleServerInit,
		Config:            sampleConfig,
	}

	first, err := kubeadmbootstrap.RenderInstall(cfg)
	require.NoError(t, err)

	second, err := kubeadmbootstrap.RenderInstall(cfg)
	require.NoError(t, err)

	assert.Equal(t, first, second, "RenderInstall is pure: equal input renders equal output")
}

// TestRenderInstallErrorsAreDistinct guards the sentinels the install path adds so
// a caller can branch on the specific misconfiguration.
func TestRenderInstallErrorsAreDistinct(t *testing.T) {
	t.Parallel()

	sentinels := []error{
		kubeadmbootstrap.ErrMissingKubernetesVersion,
		kubeadmbootstrap.ErrInvalidKubernetesVersion,
		kubeadmbootstrap.ErrMissingConfig,
	}

	for outer := range sentinels {
		for inner := range sentinels {
			if outer == inner {
				continue
			}

			assert.NotErrorIs(t, sentinels[outer], sentinels[inner],
				"install sentinels must be distinct errors")
		}
	}
}
