package backup

import (
	"archive/tar"
	"compress/gzip"
	"os"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// This file follows the repo's export_test.go convention: black-box test files
// (package backup_test) reach the engine's unexported helpers through these
// thin re-exports, keeping the tests external while still covering internals.

// Exported permission-mode constants for tests.
const (
	DirPerm  = dirPerm
	FilePerm = filePerm
)

// WriteMetadata exposes writeMetadata for testing.
func WriteMetadata(metadata *BackupMetadata, path string) error {
	return writeMetadata(metadata, path)
}

// ReadBackupMetadata exposes readBackupMetadata for testing.
func ReadBackupMetadata(tmpDir string) (*BackupMetadata, error) {
	return readBackupMetadata(tmpDir)
}

// CreateTarball exposes createTarball for testing.
func CreateTarball(sourceDir, targetPath string, compressionLevel int) error {
	return createTarball(sourceDir, targetPath, compressionLevel)
}

// CommitTarball exposes commitTarball for testing.
func CommitTarball(
	tarWriter *tar.Writer,
	gzipWriter *gzip.Writer,
	outFile *os.File,
	tmpPath, targetPath string,
) error {
	return commitTarball(tarWriter, gzipWriter, outFile, tmpPath, targetPath)
}

// ExtractBackupArchive exposes extractBackupArchive for testing.
func ExtractBackupArchive(inputPath string) (string, *BackupMetadata, error) {
	return extractBackupArchive(inputPath)
}

// ValidateTarEntry exposes validateTarEntry for testing.
func ValidateTarEntry(header *tar.Header, destDir string) (string, error) {
	return validateTarEntry(header, destDir)
}

// SanitizeYAMLOutput exposes sanitizeYAMLOutput for testing.
func SanitizeYAMLOutput(output string) (string, error) {
	return sanitizeYAMLOutput(output)
}

// IsHelmReleaseSecret exposes isHelmReleaseSecret for testing.
func IsHelmReleaseSecret(obj *unstructured.Unstructured) bool {
	return isHelmReleaseSecret(obj)
}

// RemoveAutoGeneratedJobLabels exposes removeAutoGeneratedJobLabels for testing.
func RemoveAutoGeneratedJobLabels(obj *unstructured.Unstructured, fields ...string) {
	removeAutoGeneratedJobLabels(obj, fields...)
}

// RemoveServiceClusterIPs exposes removeServiceClusterIPs for testing.
func RemoveServiceClusterIPs(obj *unstructured.Unstructured) {
	removeServiceClusterIPs(obj)
}

// CountYAMLDocuments exposes countYAMLDocuments for testing.
func CountYAMLDocuments(content string) int {
	return countYAMLDocuments(content)
}

// FilterExcludedTypes exposes filterExcludedTypes for testing.
func FilterExcludedTypes(resourceTypes, excludeTypes []string) []string {
	return filterExcludedTypes(resourceTypes, excludeTypes)
}

// BackupResourceTypes exposes backupResourceTypes for testing.
func BackupResourceTypes() []string {
	return backupResourceTypes()
}

// ClusterScopedResourceTypes exposes clusterScopedResourceTypes for testing.
func ClusterScopedResourceTypes() map[string]bool {
	return clusterScopedResourceTypes()
}

// DeriveBackupName exposes deriveBackupName for testing.
func DeriveBackupName(inputPath string) string {
	return deriveBackupName(inputPath)
}

// AddLabelsToDocument exposes addLabelsToDocument for testing.
func AddLabelsToDocument(doc, backupName, restoreName string) (string, error) {
	return addLabelsToDocument(doc, backupName, restoreName)
}

// SplitYAMLDocuments exposes splitYAMLDocuments for testing.
func SplitYAMLDocuments(content string) []string {
	return splitYAMLDocuments(content)
}

// InjectRestoreLabels exposes injectRestoreLabels for testing.
func InjectRestoreLabels(filePath, backupName, restoreName string) (string, error) {
	return injectRestoreLabels(filePath, backupName, restoreName)
}

// IsEmptyYAML exposes isEmptyYAML for testing.
func IsEmptyYAML(path string) bool {
	return isEmptyYAML(path)
}

// ClassifyRestoreError exposes classifyRestoreError for testing.
func ClassifyRestoreError(err error, stderr, policy string) error {
	return classifyRestoreError(err, stderr, policy)
}

// AllLinesContain exposes allLinesContain for testing.
func AllLinesContain(output, substr string) bool {
	return allLinesContain(output, substr)
}
