package backup

import (
	"fmt"
	"strings"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	sigsyaml "sigs.k8s.io/yaml"
)

// sanitizeYAMLOutput removes server-assigned metadata fields from kubectl
// output to produce portable, apply-able manifests. Fields stripped include
// resourceVersion, uid, selfLink, creationTimestamp, managedFields, and
// the entire status block.
func sanitizeYAMLOutput(output string) (string, error) {
	var obj unstructured.Unstructured

	err := sigsyaml.Unmarshal([]byte(output), &obj.Object)
	if err != nil {
		// If we can't parse it, return the original output unchanged.
		return output, nil //nolint:nilerr // non-parseable output is kept as-is
	}

	kind := obj.GetKind()
	if strings.HasSuffix(kind, "List") {
		return sanitizeList(&obj)
	}

	if isHelmReleaseSecret(&obj) {
		return "", nil
	}

	sanitizeObject(&obj)

	result, err := sigsyaml.Marshal(obj.Object)
	if err != nil {
		return output, nil //nolint:nilerr // marshal failure falls back to original
	}

	return string(result), nil
}

func sanitizeList(list *unstructured.Unstructured) (string, error) {
	items, found, err := unstructured.NestedSlice(
		list.Object, "items",
	)
	if err != nil || !found {
		// No items found; sanitize the list object itself.
		sanitizeObject(list)

		result, marshalErr := sigsyaml.Marshal(list.Object)
		if marshalErr != nil {
			return "", fmt.Errorf("failed to marshal list: %w", marshalErr)
		}

		return string(result), nil
	}

	var builder strings.Builder

	// Pre-allocate capacity: estimate ~256 bytes per item for YAML output
	// plus separator overhead.
	const estimatedBytesPerItem = 256
	builder.Grow(len(items) * estimatedBytesPerItem)

	wroteAny := false

	for _, item := range items {
		itemMap, ok := item.(map[string]any)
		if !ok {
			continue // Skip malformed items that aren't maps
		}

		obj := &unstructured.Unstructured{Object: itemMap}

		if isHelmReleaseSecret(obj) {
			continue
		}

		sanitizeObject(obj)

		data, marshalErr := sigsyaml.Marshal(obj.Object)
		if marshalErr != nil {
			continue // Skip items that can't be marshaled
		}

		if wroteAny {
			builder.WriteString("---\n")
		}

		builder.Write(data)

		wroteAny = true
	}

	return builder.String(), nil
}

func sanitizeObject(obj *unstructured.Unstructured) {
	// Remove server-assigned metadata fields
	unstructured.RemoveNestedField(
		obj.Object, "metadata", "resourceVersion",
	)
	unstructured.RemoveNestedField(obj.Object, "metadata", "uid")
	unstructured.RemoveNestedField(obj.Object, "metadata", "selfLink")
	unstructured.RemoveNestedField(
		obj.Object, "metadata", "creationTimestamp",
	)
	unstructured.RemoveNestedField(
		obj.Object, "metadata", "managedFields",
	)
	unstructured.RemoveNestedField(
		obj.Object, "metadata", "generation",
	)

	// Remove last-applied-configuration annotation — it can be very large
	// (duplicates the entire resource body) and causes annotation-size-limit
	// errors (>262144 bytes) on restore for resources with large specs
	// such as ArgoCD CRDs or Helm-managed resources.
	annotations := obj.GetAnnotations()
	if _, ok := annotations["kubectl.kubernetes.io/last-applied-configuration"]; ok {
		delete(annotations, "kubectl.kubernetes.io/last-applied-configuration")

		if len(annotations) == 0 {
			obj.SetAnnotations(nil)
		} else {
			obj.SetAnnotations(annotations)
		}
	}

	// Remove status block
	unstructured.RemoveNestedField(obj.Object, "status")

	// For Jobs, remove auto-generated selector and controller-uid labels.
	// Kubernetes auto-generates spec.selector with a controller-uid label
	// that is tied to the original Job's UID. Restoring with these fields
	// fails because the selector is immutable and the UID won't match.
	if obj.GetKind() == "Job" {
		unstructured.RemoveNestedField(
			obj.Object, "spec", "selector",
		)
		// Also remove the matching label from the pod template so the
		// new auto-generated selector will work correctly.
		removeAutoGeneratedJobLabels(
			obj,
			"spec", "template", "metadata", "labels",
		)
	}

	// For Services, remove cluster-assigned ClusterIP fields. These are
	// ephemeral values assigned by the cluster's service CIDR allocator
	// and are not portable across clusters. Restoring with them causes
	// "provided IP is already allocated" errors when the service already
	// exists. Headless services (clusterIP: "None") are preserved.
	if obj.GetKind() == "Service" {
		removeServiceClusterIPs(obj)
	}
}

// removeAutoGeneratedJobLabels removes batch.kubernetes.io/controller-uid
// and controller-uid labels from the given nested field path.
func removeAutoGeneratedJobLabels(
	obj *unstructured.Unstructured, fields ...string,
) {
	labels, found, err := unstructured.NestedStringMap(
		obj.Object, fields...,
	)
	if err != nil || !found {
		return
	}

	delete(labels, "batch.kubernetes.io/controller-uid")
	delete(labels, "controller-uid")

	if len(labels) == 0 {
		unstructured.RemoveNestedField(obj.Object, fields...)
	} else {
		_ = unstructured.SetNestedStringMap(
			obj.Object, labels, fields...,
		)
	}
}

// removeServiceClusterIPs strips spec.clusterIP and spec.clusterIPs from a
// Service object unless it is a headless service (clusterIP: "None").
func removeServiceClusterIPs(obj *unstructured.Unstructured) {
	clusterIP, found, _ := unstructured.NestedString(
		obj.Object, "spec", "clusterIP",
	)

	// Headless services use "None" — preserve that value.
	if found && clusterIP == "None" {
		return
	}

	unstructured.RemoveNestedField(obj.Object, "spec", "clusterIP")
	unstructured.RemoveNestedField(obj.Object, "spec", "clusterIPs")
}

// isHelmReleaseSecret returns true if the object is a Helm release Secret
// (type "helm.sh/release.v1"). These internal Helm state objects should not
// be backed up as they are regenerated automatically when Helm releases are
// reapplied.
func isHelmReleaseSecret(obj *unstructured.Unstructured) bool {
	if obj.GetKind() != "Secret" {
		return false
	}

	secretType, _, _ := unstructured.NestedString(obj.Object, "type")

	return secretType == "helm.sh/release.v1" //nolint:gosec // Kubernetes Secret type identifier, not credentials
}

// countYAMLDocuments counts the Kubernetes documents in a YAML string,
// unwrapping kubectl List wrappers.
func countYAMLDocuments(content string) int {
	count := 0
	isListWrapper := false

	for line := range strings.SplitSeq(content, "\n") {
		trimmed := strings.TrimSpace(line)

		// Count list items via "- apiVersion:" (indented in kubectl output).
		if strings.HasPrefix(trimmed, "- apiVersion:") {
			count++

			continue
		}

		// Count top-level documents via non-indented "kind:" lines.
		// Indented kind: lines belong to list items already counted above.
		if strings.HasPrefix(line, "kind:") {
			count++

			if !isListWrapper {
				kindValue := strings.TrimSpace(
					strings.TrimPrefix(line, "kind:"),
				)

				isListWrapper = strings.HasSuffix(kindValue, "List")
			}
		}
	}

	// Subtract the List wrapper kind if items were counted.
	if isListWrapper && count > 1 {
		count--
	}

	if count == 0 {
		return 1
	}

	return count
}
