// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package helm

import (
	"context"
	"time"

	"github.com/devantler-tech/ksail/v5/pkg/client/helm"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	mock := &MockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter {
	return &MockInterface_Expecter{mock: &_m.Mock}
}

// AddRepository provides a mock function for the type MockInterface
func (_mock *MockInterface) AddRepository(ctx context.Context, entry *helm.RepositoryEntry, timeout time.Duration) error {
	ret := _mock.Called(ctx, entry, timeout)

	if len(ret) == 0 {
		panic("no return value specified for AddRepository")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *helm.RepositoryEntry, time.Duration) error); ok {
		r0 = returnFunc(ctx, entry, timeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_AddRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRepository'
type MockInterface_AddRepository_Call struct {
	*mock.Call
}

// AddRepository is a helper method to define mock.On call
//   - ctx context.Context
//   - entry *helm.RepositoryEntry
//   - timeout time.Duration
func (_e *MockInterface_Expecter) AddRepository(ctx interface{}, entry interface{}, timeout interface{}) *MockInterface_AddRepository_Call {
	return &MockInterface_AddRepository_Call{Call: _e.mock.On("AddRepository", ctx, entry, timeout)}
}

func (_c *MockInterface_AddRepository_Call) Run(run func(ctx context.Context, entry *helm.RepositoryEntry, timeout time.Duration)) *MockInterface_AddRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *helm.RepositoryEntry
		if args[1] != nil {
			arg1 = args[1].(*helm.RepositoryEntry)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInterface_AddRepository_Call) Return(err error) *MockInterface_AddRepository_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_AddRepository_Call) RunAndReturn(run func(ctx context.Context, entry *helm.RepositoryEntry, timeout time.Duration) error) *MockInterface_AddRepository_Call {
	_c.Call.Return(run)
	return _c
}

// InstallChart provides a mock function for the type MockInterface
func (_mock *MockInterface) InstallChart(ctx context.Context, spec *helm.ChartSpec) (*helm.ReleaseInfo, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for InstallChart")
	}

	var r0 *helm.ReleaseInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *helm.ChartSpec) (*helm.ReleaseInfo, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *helm.ChartSpec) *helm.ReleaseInfo); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*helm.ReleaseInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *helm.ChartSpec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_InstallChart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallChart'
type MockInterface_InstallChart_Call struct {
	*mock.Call
}

// InstallChart is a helper method to define mock.On call
//   - ctx context.Context
//   - spec *helm.ChartSpec
func (_e *MockInterface_Expecter) InstallChart(ctx interface{}, spec interface{}) *MockInterface_InstallChart_Call {
	return &MockInterface_InstallChart_Call{Call: _e.mock.On("InstallChart", ctx, spec)}
}

func (_c *MockInterface_InstallChart_Call) Run(run func(ctx context.Context, spec *helm.ChartSpec)) *MockInterface_InstallChart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *helm.ChartSpec
		if args[1] != nil {
			arg1 = args[1].(*helm.ChartSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInterface_InstallChart_Call) Return(releaseInfo *helm.ReleaseInfo, err error) *MockInterface_InstallChart_Call {
	_c.Call.Return(releaseInfo, err)
	return _c
}

func (_c *MockInterface_InstallChart_Call) RunAndReturn(run func(ctx context.Context, spec *helm.ChartSpec) (*helm.ReleaseInfo, error)) *MockInterface_InstallChart_Call {
	_c.Call.Return(run)
	return _c
}

// InstallOrUpgradeChart provides a mock function for the type MockInterface
func (_mock *MockInterface) InstallOrUpgradeChart(ctx context.Context, spec *helm.ChartSpec) (*helm.ReleaseInfo, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for InstallOrUpgradeChart")
	}

	var r0 *helm.ReleaseInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *helm.ChartSpec) (*helm.ReleaseInfo, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *helm.ChartSpec) *helm.ReleaseInfo); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*helm.ReleaseInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *helm.ChartSpec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_InstallOrUpgradeChart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallOrUpgradeChart'
type MockInterface_InstallOrUpgradeChart_Call struct {
	*mock.Call
}

// InstallOrUpgradeChart is a helper method to define mock.On call
//   - ctx context.Context
//   - spec *helm.ChartSpec
func (_e *MockInterface_Expecter) InstallOrUpgradeChart(ctx interface{}, spec interface{}) *MockInterface_InstallOrUpgradeChart_Call {
	return &MockInterface_InstallOrUpgradeChart_Call{Call: _e.mock.On("InstallOrUpgradeChart", ctx, spec)}
}

func (_c *MockInterface_InstallOrUpgradeChart_Call) Run(run func(ctx context.Context, spec *helm.ChartSpec)) *MockInterface_InstallOrUpgradeChart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *helm.ChartSpec
		if args[1] != nil {
			arg1 = args[1].(*helm.ChartSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInterface_InstallOrUpgradeChart_Call) Return(releaseInfo *helm.ReleaseInfo, err error) *MockInterface_InstallOrUpgradeChart_Call {
	_c.Call.Return(releaseInfo, err)
	return _c
}

func (_c *MockInterface_InstallOrUpgradeChart_Call) RunAndReturn(run func(ctx context.Context, spec *helm.ChartSpec) (*helm.ReleaseInfo, error)) *MockInterface_InstallOrUpgradeChart_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseExists provides a mock function for the type MockInterface
func (_mock *MockInterface) ReleaseExists(ctx context.Context, releaseName string, namespace string) (bool, error) {
	ret := _mock.Called(ctx, releaseName, namespace)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, releaseName, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, releaseName, namespace)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, releaseName, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_ReleaseExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseExists'
type MockInterface_ReleaseExists_Call struct {
	*mock.Call
}

// ReleaseExists is a helper method to define mock.On call
//   - ctx context.Context
//   - releaseName string
//   - namespace string
func (_e *MockInterface_Expecter) ReleaseExists(ctx interface{}, releaseName interface{}, namespace interface{}) *MockInterface_ReleaseExists_Call {
	return &MockInterface_ReleaseExists_Call{Call: _e.mock.On("ReleaseExists", ctx, releaseName, namespace)}
}

func (_c *MockInterface_ReleaseExists_Call) Run(run func(ctx context.Context, releaseName string, namespace string)) *MockInterface_ReleaseExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInterface_ReleaseExists_Call) Return(b bool, err error) *MockInterface_ReleaseExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockInterface_ReleaseExists_Call) RunAndReturn(run func(ctx context.Context, releaseName string, namespace string) (bool, error)) *MockInterface_ReleaseExists_Call {
	_c.Call.Return(run)
	return _c
}

// TemplateChart provides a mock function for the type MockInterface
func (_mock *MockInterface) TemplateChart(ctx context.Context, spec *helm.ChartSpec) (string, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for TemplateChart")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *helm.ChartSpec) (string, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *helm.ChartSpec) string); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *helm.ChartSpec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_TemplateChart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TemplateChart'
type MockInterface_TemplateChart_Call struct {
	*mock.Call
}

// TemplateChart is a helper method to define mock.On call
//   - ctx context.Context
//   - spec *helm.ChartSpec
func (_e *MockInterface_Expecter) TemplateChart(ctx interface{}, spec interface{}) *MockInterface_TemplateChart_Call {
	return &MockInterface_TemplateChart_Call{Call: _e.mock.On("TemplateChart", ctx, spec)}
}

func (_c *MockInterface_TemplateChart_Call) Run(run func(ctx context.Context, spec *helm.ChartSpec)) *MockInterface_TemplateChart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *helm.ChartSpec
		if args[1] != nil {
			arg1 = args[1].(*helm.ChartSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInterface_TemplateChart_Call) Return(s string, err error) *MockInterface_TemplateChart_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockInterface_TemplateChart_Call) RunAndReturn(run func(ctx context.Context, spec *helm.ChartSpec) (string, error)) *MockInterface_TemplateChart_Call {
	_c.Call.Return(run)
	return _c
}

// UninstallRelease provides a mock function for the type MockInterface
func (_mock *MockInterface) UninstallRelease(ctx context.Context, releaseName string, namespace string) error {
	ret := _mock.Called(ctx, releaseName, namespace)

	if len(ret) == 0 {
		panic("no return value specified for UninstallRelease")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, releaseName, namespace)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_UninstallRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UninstallRelease'
type MockInterface_UninstallRelease_Call struct {
	*mock.Call
}

// UninstallRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - releaseName string
//   - namespace string
func (_e *MockInterface_Expecter) UninstallRelease(ctx interface{}, releaseName interface{}, namespace interface{}) *MockInterface_UninstallRelease_Call {
	return &MockInterface_UninstallRelease_Call{Call: _e.mock.On("UninstallRelease", ctx, releaseName, namespace)}
}

func (_c *MockInterface_UninstallRelease_Call) Run(run func(ctx context.Context, releaseName string, namespace string)) *MockInterface_UninstallRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInterface_UninstallRelease_Call) Return(err error) *MockInterface_UninstallRelease_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_UninstallRelease_Call) RunAndReturn(run func(ctx context.Context, releaseName string, namespace string) error) *MockInterface_UninstallRelease_Call {
	_c.Call.Return(run)
	return _c
}
