name: Assets

on:
  schedule:
    - cron: "59 23 * * *"
  workflow_dispatch:

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ⤵️ Get binaries
        run: |
          ./scripts/get_wrapped_binaries.sh
      - name: ✍🏻 Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update binaries
          title: Update binaries
          body: |
            This PR updates the binaries used by KSail to the latest version.
          branch: update-binaries
          delete-branch: true
          labels: dependencies
          reviewers: devantler
          assignees: devantler
          signoff: true
