name: Release
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    uses: devantler-tech/reusable-workflows/.github/workflows/create-release.yaml@ad99c16f59e9e205d1cbd4d511c949aa353670b7 # v5.0.0
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
