name: Release
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    uses: devantler-tech/reusable-workflows/.github/workflows/create-release.yaml@699cae1d98f6e2759cce88bb243fc5ae6578e007 # v5.1.0
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
